"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "org.hl7.fhir.utilities/src/main/resources/source/rendering-phrases-en.po",
    "translation": "org.hl7.fhir.utilities/src/main/resources/source/rendering-phrases-%two_letters_code%.po"
  },
  {
    "source": "org.hl7.fhir.utilities/src/main/resources/source/validator-messages-en.po",
    "translation": "org.hl7.fhir.utilities/src/main/resources/source/validator-messages-%two_letters_code%.po"
  }
]
