trigger: none

pr:
- master
- release

# Different users have different machine setups, we run the build three times, on ubuntu, osx, and windows
jobs:
  - template: pull-request-pipeline-parameterized.yml
    parameters:
      images:
        - name: ubuntu-latest
          jdkVersions:  [ '1.8', '1.11' ]
        - name: macos-latest
          jdkVersions: [ '1.8', '1.11', '1.17']
        - name: windows-2019
          jdkVersions: [ '1.8', '1.11', '1.17']