jobs:
  - ${{ each image in parameters.images }}:
      - job:

        displayName: ${{image.displayName}}
        
        pool:
          vmImage: ${{image.vmImage}}
        
        variables:
          currentImage: ${{image.vmImage}}
          codecov: $(CODECOV_TOKEN)
          VERSION:
          JAVA_TOOL_OPTIONS: ${{image.javaToolOptions}}

        steps:
          # Runs 'mvn clean install'
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '${{image.jdkVersion}}'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'install'

          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '${{image.jdkVersion}}'
              jdkArchitectureOption: 'x64'
              options: '-pl org.hl7.fhir.validation.cli'
              publishJUnitResults: false
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'exec:exec'

          # Upload test results to codecov    
          - script: bash <(curl https://codecov.io/bash) -t $(codecov)
            displayName: 'codecov Bash Uploader'
            condition: eq(variables.currentImage, 'ubuntu-latest')

          # Publishes the test results to build artifacts.
          - task: PublishCodeCoverageResults@1
            displayName: 'Publish JaCoCo test results'
            condition: eq(variables.currentImage, 'ubuntu-latest')
            inputs:
              codeCoverageTool: 'JaCoCo'
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/org.hl7.fhir.report/target/site/jacoco-aggregate/jacoco.xml'
              reportDirectory: '$(System.DefaultWorkingDirectory)/org.hl7.fhir.report/target/site/jacoco-aggregate/'
