trigger: none

pr:
- master
- release

jobs:
- template: pull-request-pipeline-parameterized.yml
  parameters:
    imageName: [ 'ubuntu-latest', 'macos-latest', 'windows-2019' ]
    jdkVersion: [ '1.8', '1.11', '1.17']