trigger: none

pr:
- master
- release

jobs:
- template: pull-request-pipeline-parameterized.yml
  parameters:
    images:
    - name: ubuntu-latest
      jdkVersions:  [ '1.8', '1.11' ]
    - name: macos-latest
      jdkVersions: [ '1.8', '1.11', '1.17']
    - name: windows-2019
      jdkVersions: [ '1.8', '1.11', '1.17']