package org.hl7.fhir.convertors;

import org.hl7.fhir.utilities.Utilities;

public class VersionConvertorResourceNameMapper {

  public static String mapName3to5(String name) {
    if (Utilities.noString(name)) { return null; } 
    if (name.equals("Account")) { return "Account"; }
    if (name.equals("ActivityDefinition")) { return "ActivityDefinition"; }
    if (name.equals("AdverseEvent")) { return "AdverseEvent"; }
    if (name.equals("AllergyIntolerance")) { return "AllergyIntolerance"; }
    if (name.equals("Appointment")) { return "Appointment"; }
    if (name.equals("AppointmentResponse")) { return "AppointmentResponse"; }
    if (name.equals("AuditEvent")) { return "AuditEvent"; }
    if (name.equals("Basic")) { return "Basic"; }
    if (name.equals("Binary")) { return "Binary"; }
    if (name.equals("BodySite")) { return "BodyStructure"; }
    if (name.equals("Bundle")) { return "Bundle"; }
    if (name.equals("CapabilityStatement")) { return "CapabilityStatement"; }
    if (name.equals("CarePlan")) { return "CarePlan"; }
    if (name.equals("CareTeam")) { return "CareTeam"; }
    if (name.equals("ChargeItem")) { return "ChargeItem"; }
    if (name.equals("Claim")) { return "Claim"; }
    if (name.equals("ClaimResponse")) { return "ClaimResponse"; }
    if (name.equals("ClinicalImpression")) { return "ClinicalImpression"; }
    if (name.equals("CodeSystem")) { return "CodeSystem"; }
    if (name.equals("Communication")) { return "Communication"; }
    if (name.equals("CommunicationRequest")) { return "CommunicationRequest"; }
    if (name.equals("CompartmentDefinition")) { return "CompartmentDefinition"; }
    if (name.equals("Composition")) { return "Composition"; }
    if (name.equals("ConceptMap")) { return "ConceptMap"; }
    if (name.equals("Condition")) { return "Condition"; }
    if (name.equals("Consent")) { return "Consent"; }
    if (name.equals("Contract")) { return "Contract"; }
    if (name.equals("Coverage")) { return "Coverage"; }
    if (name.equals("DataElement")) { return " StructureDefinition"; }
    if (name.equals("EligibilityRequest")) { return "CoverageEligibilityRequest"; }
    if (name.equals("EligibilityResponse")) { return "CoverageEligibilityResponse"; }
    if (name.equals("DetectedIssue")) { return "DetectedIssue"; }
    if (name.equals("Device")) { return "Device"; }
    if (name.equals("DeviceComponent")) { return null; }
    if (name.equals("DeviceMetric")) { return "DeviceMetric"; }
    if (name.equals("DeviceRequest")) { return "DeviceRequest"; }
    if (name.equals("DeviceUseStatement")) { return "DeviceUseStatement"; }
    if (name.equals("DiagnosticReport")) { return "DiagnosticReport"; }
    if (name.equals("DocumentManifest")) { return "DocumentManifest"; }
    if (name.equals("DocumentReference")) { return "DocumentReference"; }
    if (name.equals("Encounter")) { return "Encounter"; }
    if (name.equals("Endpoint")) { return "Endpoint"; }
    if (name.equals("EnrollmentRequest")) { return "EnrollmentRequest"; }
    if (name.equals("EnrollmentResponse")) { return "EnrollmentResponse"; }
    if (name.equals("EpisodeOfCare")) { return "EpisodeOfCare"; }
    if (name.equals("ExpansionProfile")) { return "Parameters"; }
    if (name.equals("ExplanationOfBenefit")) { return "ExplanationOfBenefit"; }
    if (name.equals("FamilyMemberHistory")) { return "FamilyMemberHistory"; }
    if (name.equals("Flag")) { return "Flag"; }
    if (name.equals("Goal")) { return "Goal"; }
    if (name.equals("GraphDefinition")) { return "GraphDefinition"; }
    if (name.equals("Group")) { return "Group"; }
    if (name.equals("GuidanceResponse")) { return "GuidanceResponse"; }
    if (name.equals("HealthcareService")) { return "HealthcareService"; }
    if (name.equals("ImagingManifest")) { return null; }
    if (name.equals("ImagingStudy")) { return "ImagingStudy"; }
    if (name.equals("Immunization")) { return "Immunization"; }
    if (name.equals("ImmunizationRecommendation")) { return "ImmunizationRecommendation"; }
    if (name.equals("ImplementationGuide")) { return "ImplementationGuide"; }
    if (name.equals("Library")) { return "Library"; }
    if (name.equals("Linkage")) { return "Linkage"; }
    if (name.equals("List")) { return "List"; }
    if (name.equals("Location")) { return "Location"; }
    if (name.equals("Measure")) { return "Measure"; }
    if (name.equals("MeasureReport")) { return "MeasureReport"; }
    if (name.equals("Media")) { return "Media"; }
    if (name.equals("Medication")) { return "Medication"; }
    if (name.equals("MedicationAdministration")) { return "MedicationAdministration"; }
    if (name.equals("MedicationDispense")) { return "MedicationDispense"; }
    if (name.equals("MedicationRequest")) { return "MedicationRequest"; }
    if (name.equals("MedicationStatement")) { return "MedicationUsage"; }
    if (name.equals("MessageDefinition")) { return "MessageDefinition"; }
    if (name.equals("MessageHeader")) { return "MessageHeader"; }
    if (name.equals("Sequence")) { return "MolecularSequence"; }
    if (name.equals("NamingSystem")) { return "NamingSystem"; }
    if (name.equals("NutritionOrder")) { return "NutritionOrder"; }
    if (name.equals("Observation")) { return "Observation"; }
    if (name.equals("OperationDefinition")) { return "OperationDefinition"; }
    if (name.equals("OperationOutcome")) { return "OperationOutcome"; }
    if (name.equals("Organization")) { return "Organization"; }
    if (name.equals("Parameters")) { return "Parameters"; }
    if (name.equals("Patient")) { return "Patient"; }
    if (name.equals("PaymentNotice")) { return "PaymentNotice"; }
    if (name.equals("PaymentReconciliation")) { return "PaymentReconciliation"; }
    if (name.equals("Person")) { return "Person"; }
    if (name.equals("PlanDefinition")) { return "PlanDefinition"; }
    if (name.equals("Practitioner")) { return "Practitioner"; }
    if (name.equals("PractitionerRole")) { return "PractitionerRole"; }
    if (name.equals("Procedure")) { return "Procedure"; }
    if (name.equals("ProcessRequest")) { return "Task"; }
    if (name.equals("ProcessResponse")) { return "Task"; }
    if (name.equals("Provenance")) { return "Provenance"; }
    if (name.equals("Questionnaire")) { return "Questionnaire"; }
    if (name.equals("QuestionnaireResponse")) { return "QuestionnaireResponse"; }
    if (name.equals("ReferralRequest")) { return "ServiceRequest"; }
    if (name.equals("RelatedPerson")) { return "RelatedPerson"; }
    if (name.equals("RequestGroup")) { return "RequestGroup"; }
    if (name.equals("ResearchStudy")) { return "ResearchStudy"; }
    if (name.equals("ResearchSubject")) { return "ResearchSubject"; }
    if (name.equals("RiskAssessment")) { return "RiskAssessment"; }
    if (name.equals("Schedule")) { return "Schedule"; }
    if (name.equals("SearchParameter")) { return "SearchParameter"; }
    if (name.equals("ServiceDefinition")) { return null; }
    if (name.equals("ProcedureRequest")) { return "ServiceRequest"; }
    if (name.equals("Slot")) { return "Slot"; }
    if (name.equals("Specimen")) { return "Specimen"; }
    if (name.equals("StructureDefinition")) { return "StructureDefinition"; }
    if (name.equals("StructureMap")) { return "StructureMap"; }
    if (name.equals("Subscription")) { return "Subscription"; }
    if (name.equals("Substance")) { return "Substance"; }
    if (name.equals("SupplyDelivery")) { return "SupplyDelivery"; }
    if (name.equals("SupplyRequest")) { return "SupplyRequest"; }
    if (name.equals("Task")) { return "Task"; }
    if (name.equals("TestReport")) { return "TestReport"; }
    if (name.equals("TestScript")) { return "TestScript"; }
    if (name.equals("ValueSet")) { return "ValueSet"; }
    if (name.equals("VisionPrescription")) { return "VisionPrescription"; }
    return null;
  }

  public static String mapName5to3(String name) {
    if (Utilities.noString(name)) { return null; } 
    if (name.equals("Account")) { return "Account"; }
    if (name.equals("ActivityDefinition")) { return "ActivityDefinition"; }
    if (name.equals("AdverseEvent")) { return "AdverseEvent"; }
    if (name.equals("AllergyIntolerance")) { return "AllergyIntolerance"; }
    if (name.equals("Appointment")) { return "Appointment"; }
    if (name.equals("AppointmentResponse")) { return "AppointmentResponse"; }
    if (name.equals("AuditEvent")) { return "AuditEvent"; }
    if (name.equals("Basic")) { return "Basic"; }
    if (name.equals("Binary")) { return "Binary"; }
    if (name.equals("BiologicallyDerivedProduct")) { return null; }
    if (name.equals("BodyStructure")) { return "BodySite"; }
    if (name.equals("Bundle")) { return "Bundle"; }
    if (name.equals("CapabilityStatement")) { return "CapabilityStatement"; }
    if (name.equals("CarePlan")) { return "CarePlan"; }
    if (name.equals("CareTeam")) { return "CareTeam"; }
    if (name.equals("CatalogEntry")) { return null; }
    if (name.equals("ChargeItem")) { return "ChargeItem"; }
    if (name.equals("ChargeItemDefinition")) { return null; }
    if (name.equals("Claim")) { return "Claim"; }
    if (name.equals("ClaimResponse")) { return "ClaimResponse"; }
    if (name.equals("ClinicalImpression")) { return "ClinicalImpression"; }
    if (name.equals("CodeSystem")) { return "CodeSystem"; }
    if (name.equals("Communication")) { return "Communication"; }
    if (name.equals("CommunicationRequest")) { return "CommunicationRequest"; }
    if (name.equals("CompartmentDefinition")) { return "CompartmentDefinition"; }
    if (name.equals("Composition")) { return "Composition"; }
    if (name.equals("ConceptMap")) { return "ConceptMap"; }
    if (name.equals("Condition")) { return "Condition"; }
    if (name.equals("Consent")) { return "Consent"; }
    if (name.equals("Contract")) { return "Contract"; }
    if (name.equals("Coverage")) { return "Coverage"; }
    if (name.equals("CoverageEligibilityRequest")) { return "EligibilityRequest"; }
    if (name.equals("CoverageEligibilityResponse")) { return "EligibilityResponse"; }
    if (name.equals("DetectedIssue")) { return "DetectedIssue"; }
    if (name.equals("Device")) { return "Device"; }
    if (name.equals("DeviceDefinition")) { return null; }
    if (name.equals("DeviceMetric")) { return "DeviceMetric"; }
    if (name.equals("DeviceRequest")) { return "DeviceRequest"; }
    if (name.equals("DeviceUseStatement")) { return "DeviceUseStatement"; }
    if (name.equals("DiagnosticReport")) { return "DiagnosticReport"; }
    if (name.equals("DocumentManifest")) { return "DocumentManifest"; }
    if (name.equals("DocumentReference")) { return "DocumentReference"; }
    if (name.equals("EffectEvidenceSynthesis")) { return null; }
    if (name.equals("Encounter")) { return "Encounter"; }
    if (name.equals("Endpoint")) { return "Endpoint"; }
    if (name.equals("EnrollmentRequest")) { return "EnrollmentRequest"; }
    if (name.equals("EnrollmentResponse")) { return "EnrollmentResponse"; }
    if (name.equals("EpisodeOfCare")) { return "EpisodeOfCare"; }
    if (name.equals("EventDefinition")) { return null; }
    if (name.equals("ExampleScenario")) { return null; }
    if (name.equals("ExplanationOfBenefit")) { return "ExplanationOfBenefit"; }
    if (name.equals("FamilyMemberHistory")) { return "FamilyMemberHistory"; }
    if (name.equals("Flag")) { return "Flag"; }
    if (name.equals("Goal")) { return "Goal"; }
    if (name.equals("GraphDefinition")) { return "GraphDefinition"; }
    if (name.equals("Group")) { return "Group"; }
    if (name.equals("GuidanceResponse")) { return "GuidanceResponse"; }
    if (name.equals("HealthcareService")) { return "HealthcareService"; }
    if (name.equals("ImagingStudy")) { return "ImagingStudy"; }
    if (name.equals("Immunization")) { return "Immunization"; }
    if (name.equals("ImmunizationEvaluation")) { return null; }
    if (name.equals("ImmunizationRecommendation")) { return "ImmunizationRecommendation"; }
    if (name.equals("ImplementationGuide")) { return "ImplementationGuide"; }
    if (name.equals("InsurancePlan")) { return null; }
    if (name.equals("Invoice")) { return null; }
    if (name.equals("Library")) { return "Library"; }
    if (name.equals("Linkage")) { return "Linkage"; }
    if (name.equals("List")) { return "List"; }
    if (name.equals("Location")) { return "Location"; }
    if (name.equals("Measure")) { return "Measure"; }
    if (name.equals("MeasureReport")) { return "MeasureReport"; }
    if (name.equals("Media")) { return "Media"; }
    if (name.equals("Medication")) { return "Medication"; }
    if (name.equals("MedicationAdministration")) { return "MedicationAdministration"; }
    if (name.equals("MedicationDispense")) { return "MedicationDispense"; }
    if (name.equals("MedicationKnowledge")) { return null; }
    if (name.equals("MedicationRequest")) { return "MedicationRequest"; }
    if (name.equals("MedicationUsage")) { return "MedicationStatement"; }
    if (name.equals("MedicinalProduct")) { return null; }
    if (name.equals("MedicinalProductAuthorization")) { return null; }
    if (name.equals("MedicinalProductContraindication")) { return null; }
    if (name.equals("MedicinalProductIndication")) { return null; }
    if (name.equals("MedicinalProductIngredient")) { return null; }
    if (name.equals("MedicinalProductInteraction")) { return null; }
    if (name.equals("MedicinalProductManufactured")) { return null; }
    if (name.equals("MedicinalProductPackaged")) { return null; }
    if (name.equals("MedicinalProductPharmaceutical")) { return null; }
    if (name.equals("MedicinalProductUndesirableEffect")) { return null; }
    if (name.equals("MessageDefinition")) { return "MessageDefinition"; }
    if (name.equals("MessageHeader")) { return "MessageHeader"; }
    if (name.equals("MolecularSequence")) { return "Sequence"; }
    if (name.equals("NamingSystem")) { return "NamingSystem"; }
    if (name.equals("NutritionOrder")) { return "NutritionOrder"; }
    if (name.equals("Observation")) { return "Observation"; }
    if (name.equals("ObservationDefinition")) { return null; }
    if (name.equals("OperationDefinition")) { return "OperationDefinition"; }
    if (name.equals("OperationOutcome")) { return "OperationOutcome"; }
    if (name.equals("Organization")) { return "Organization"; }
    if (name.equals("OrganizationAffiliation")) { return null; }
    if (name.equals("Parameters")) { return "Parameters"; }
    if (name.equals("Patient")) { return "Patient"; }
    if (name.equals("PaymentNotice")) { return "PaymentNotice"; }
    if (name.equals("PaymentReconciliation")) { return "PaymentReconciliation"; }
    if (name.equals("Person")) { return "Person"; }
    if (name.equals("PlanDefinition")) { return "PlanDefinition"; }
    if (name.equals("Practitioner")) { return "Practitioner"; }
    if (name.equals("PractitionerRole")) { return "PractitionerRole"; }
    if (name.equals("Procedure")) { return "Procedure"; }
    if (name.equals("Provenance")) { return "Provenance"; }
    if (name.equals("Questionnaire")) { return "Questionnaire"; }
    if (name.equals("QuestionnaireResponse")) { return "QuestionnaireResponse"; }
    if (name.equals("RelatedPerson")) { return "RelatedPerson"; }
    if (name.equals("RequestGroup")) { return "RequestGroup"; }
    if (name.equals("ResearchStudy")) { return "ResearchStudy"; }
    if (name.equals("ResearchSubject")) { return "ResearchSubject"; }
    if (name.equals("RiskAssessment")) { return "RiskAssessment"; }
    if (name.equals("Schedule")) { return "Schedule"; }
    if (name.equals("SearchParameter")) { return "SearchParameter"; }
    if (name.equals("ServiceRequest")) { return "ProcedureRequest"; }
    //     if (name.equals("ServiceRequest")) { return "ReferralRequest"; }
    if (name.equals("Slot")) { return "Slot"; }
    if (name.equals("Specimen")) { return "Specimen"; }
    if (name.equals("SpecimenDefinition")) { return null; }
    if (name.equals("StructureDefinition")) { return "StructureDefinition"; }
    // if (name.equals("StructureDefinition")) { return "DataElement"; }
    if (name.equals("StructureMap")) { return "StructureMap"; }
    if (name.equals("Subscription")) { return "Subscription"; }
    if (name.equals("Substance")) { return "Substance"; }
    if (name.equals("SubstancePolymer")) { return null; }
    if (name.equals("SubstanceReferenceInformation")) { return null; }
    if (name.equals("SubstanceSpecification")) { return null; }
    if (name.equals("SupplyDelivery")) { return "SupplyDelivery"; }
    if (name.equals("SupplyRequest")) { return "SupplyRequest"; }
    if (name.equals("Task")) { return "Task"; }
    if (name.equals("TerminologyCapabilities")) { return null; }
    if (name.equals("TestReport")) { return "TestReport"; }
    if (name.equals("TestScript")) { return "TestScript"; }
    if (name.equals("ValueSet")) { return "ValueSet"; }
    if (name.equals("VerificationResult")) { return null; }
    if (name.equals("VisionPrescription")) { return "VisionPrescription"; }
    return null;
  }


  public static String mapName3to4(String name) {
    if (Utilities.noString(name)) { return null; } 
    if (name.equals("Account")) { return "Account"; }
    if (name.equals("ActivityDefinition")) { return "ActivityDefinition"; }
    if (name.equals("AdverseEvent")) { return "AdverseEvent"; }
    if (name.equals("AllergyIntolerance")) { return "AllergyIntolerance"; }
    if (name.equals("Appointment")) { return "Appointment"; }
    if (name.equals("AppointmentResponse")) { return "AppointmentResponse"; }
    if (name.equals("AuditEvent")) { return "AuditEvent"; }
    if (name.equals("Basic")) { return "Basic"; }
    if (name.equals("Binary")) { return "Binary"; }
    if (name.equals("BodySite")) { return "BodyStructure"; }
    if (name.equals("Bundle")) { return "Bundle"; }
    if (name.equals("CapabilityStatement")) { return "CapabilityStatement"; }
    if (name.equals("CarePlan")) { return "CarePlan"; }
    if (name.equals("CareTeam")) { return "CareTeam"; }
    if (name.equals("ChargeItem")) { return "ChargeItem"; }
    if (name.equals("Claim")) { return "Claim"; }
    if (name.equals("ClaimResponse")) { return "ClaimResponse"; }
    if (name.equals("ClinicalImpression")) { return "ClinicalImpression"; }
    if (name.equals("CodeSystem")) { return "CodeSystem"; }
    if (name.equals("Communication")) { return "Communication"; }
    if (name.equals("CommunicationRequest")) { return "CommunicationRequest"; }
    if (name.equals("CompartmentDefinition")) { return "CompartmentDefinition"; }
    if (name.equals("Composition")) { return "Composition"; }
    if (name.equals("ConceptMap")) { return "ConceptMap"; }
    if (name.equals("Condition")) { return "Condition"; }
    if (name.equals("Consent")) { return "Consent"; }
    if (name.equals("Contract")) { return "Contract"; }
    if (name.equals("Coverage")) { return "Coverage"; }
    if (name.equals("DataElement")) { return " StructureDefinition"; }
    if (name.equals("EligibilityRequest")) { return "CoverageEligibilityRequest"; }
    if (name.equals("EligibilityResponse")) { return "CoverageEligibilityResponse"; }
    if (name.equals("DetectedIssue")) { return "DetectedIssue"; }
    if (name.equals("Device")) { return "Device"; }
    if (name.equals("DeviceComponent")) { return null; }
    if (name.equals("DeviceMetric")) { return "DeviceMetric"; }
    if (name.equals("DeviceRequest")) { return "DeviceRequest"; }
    if (name.equals("DeviceUseStatement")) { return "DeviceUseStatement"; }
    if (name.equals("DiagnosticReport")) { return "DiagnosticReport"; }
    if (name.equals("DocumentManifest")) { return "DocumentManifest"; }
    if (name.equals("DocumentReference")) { return "DocumentReference"; }
    if (name.equals("Encounter")) { return "Encounter"; }
    if (name.equals("Endpoint")) { return "Endpoint"; }
    if (name.equals("EnrollmentRequest")) { return "EnrollmentRequest"; }
    if (name.equals("EnrollmentResponse")) { return "EnrollmentResponse"; }
    if (name.equals("EpisodeOfCare")) { return "EpisodeOfCare"; }
    if (name.equals("ExpansionProfile")) { return "Parameters"; }
    if (name.equals("ExplanationOfBenefit")) { return "ExplanationOfBenefit"; }
    if (name.equals("FamilyMemberHistory")) { return "FamilyMemberHistory"; }
    if (name.equals("Flag")) { return "Flag"; }
    if (name.equals("Goal")) { return "Goal"; }
    if (name.equals("GraphDefinition")) { return "GraphDefinition"; }
    if (name.equals("Group")) { return "Group"; }
    if (name.equals("GuidanceResponse")) { return "GuidanceResponse"; }
    if (name.equals("HealthcareService")) { return "HealthcareService"; }
    if (name.equals("ImagingManifest")) { return null; }
    if (name.equals("ImagingStudy")) { return "ImagingStudy"; }
    if (name.equals("Immunization")) { return "Immunization"; }
    if (name.equals("ImmunizationRecommendation")) { return "ImmunizationRecommendation"; }
    if (name.equals("ImplementationGuide")) { return "ImplementationGuide"; }
    if (name.equals("Library")) { return "Library"; }
    if (name.equals("Linkage")) { return "Linkage"; }
    if (name.equals("List")) { return "List"; }
    if (name.equals("Location")) { return "Location"; }
    if (name.equals("Measure")) { return "Measure"; }
    if (name.equals("MeasureReport")) { return "MeasureReport"; }
    if (name.equals("Media")) { return "Media"; }
    if (name.equals("Medication")) { return "Medication"; }
    if (name.equals("MedicationAdministration")) { return "MedicationAdministration"; }
    if (name.equals("MedicationDispense")) { return "MedicationDispense"; }
    if (name.equals("MedicationRequest")) { return "MedicationRequest"; }
    if (name.equals("MedicationStatement")) { return "MedicationStatement"; }
    if (name.equals("MessageDefinition")) { return "MessageDefinition"; }
    if (name.equals("MessageHeader")) { return "MessageHeader"; }
    if (name.equals("Sequence")) { return "MolecularSequence"; }
    if (name.equals("NamingSystem")) { return "NamingSystem"; }
    if (name.equals("NutritionOrder")) { return "NutritionOrder"; }
    if (name.equals("Observation")) { return "Observation"; }
    if (name.equals("OperationDefinition")) { return "OperationDefinition"; }
    if (name.equals("OperationOutcome")) { return "OperationOutcome"; }
    if (name.equals("Organization")) { return "Organization"; }
    if (name.equals("Parameters")) { return "Parameters"; }
    if (name.equals("Patient")) { return "Patient"; }
    if (name.equals("PaymentNotice")) { return "PaymentNotice"; }
    if (name.equals("PaymentReconciliation")) { return "PaymentReconciliation"; }
    if (name.equals("Person")) { return "Person"; }
    if (name.equals("PlanDefinition")) { return "PlanDefinition"; }
    if (name.equals("Practitioner")) { return "Practitioner"; }
    if (name.equals("PractitionerRole")) { return "PractitionerRole"; }
    if (name.equals("Procedure")) { return "Procedure"; }
    if (name.equals("ProcessRequest")) { return "Task"; }
    if (name.equals("ProcessResponse")) { return "Task"; }
    if (name.equals("Provenance")) { return "Provenance"; }
    if (name.equals("Questionnaire")) { return "Questionnaire"; }
    if (name.equals("QuestionnaireResponse")) { return "QuestionnaireResponse"; }
    if (name.equals("ReferralRequest")) { return "ServiceRequest"; }
    if (name.equals("RelatedPerson")) { return "RelatedPerson"; }
    if (name.equals("RequestGroup")) { return "RequestGroup"; }
    if (name.equals("ResearchStudy")) { return "ResearchStudy"; }
    if (name.equals("ResearchSubject")) { return "ResearchSubject"; }
    if (name.equals("RiskAssessment")) { return "RiskAssessment"; }
    if (name.equals("Schedule")) { return "Schedule"; }
    if (name.equals("SearchParameter")) { return "SearchParameter"; }
    if (name.equals("ServiceDefinition")) { return null; }
    if (name.equals("ProcedureRequest")) { return "ServiceRequest"; }
    if (name.equals("Slot")) { return "Slot"; }
    if (name.equals("Specimen")) { return "Specimen"; }
    if (name.equals("StructureDefinition")) { return "StructureDefinition"; }
    if (name.equals("StructureMap")) { return "StructureMap"; }
    if (name.equals("Subscription")) { return "Subscription"; }
    if (name.equals("Substance")) { return "Substance"; }
    if (name.equals("SupplyDelivery")) { return "SupplyDelivery"; }
    if (name.equals("SupplyRequest")) { return "SupplyRequest"; }
    if (name.equals("Task")) { return "Task"; }
    if (name.equals("TestReport")) { return "TestReport"; }
    if (name.equals("TestScript")) { return "TestScript"; }
    if (name.equals("ValueSet")) { return "ValueSet"; }
    if (name.equals("VisionPrescription")) { return "VisionPrescription"; }
    return null;
  }

  public static String mapName4to3(String name) {
    if (Utilities.noString(name)) { return null; } 
    if (name.equals("Account")) { return "Account"; }
    if (name.equals("ActivityDefinition")) { return "ActivityDefinition"; }
    if (name.equals("AdverseEvent")) { return "AdverseEvent"; }
    if (name.equals("AllergyIntolerance")) { return "AllergyIntolerance"; }
    if (name.equals("Appointment")) { return "Appointment"; }
    if (name.equals("AppointmentResponse")) { return "AppointmentResponse"; }
    if (name.equals("AuditEvent")) { return "AuditEvent"; }
    if (name.equals("Basic")) { return "Basic"; }
    if (name.equals("Binary")) { return "Binary"; }
    if (name.equals("BiologicallyDerivedProduct")) { return null; }
    if (name.equals("BodyStructure")) { return "BodySite"; }
    if (name.equals("Bundle")) { return "Bundle"; }
    if (name.equals("CapabilityStatement")) { return "CapabilityStatement"; }
    if (name.equals("CarePlan")) { return "CarePlan"; }
    if (name.equals("CareTeam")) { return "CareTeam"; }
    if (name.equals("CatalogEntry")) { return null; }
    if (name.equals("ChargeItem")) { return "ChargeItem"; }
    if (name.equals("ChargeItemDefinition")) { return null; }
    if (name.equals("Claim")) { return "Claim"; }
    if (name.equals("ClaimResponse")) { return "ClaimResponse"; }
    if (name.equals("ClinicalImpression")) { return "ClinicalImpression"; }
    if (name.equals("CodeSystem")) { return "CodeSystem"; }
    if (name.equals("Communication")) { return "Communication"; }
    if (name.equals("CommunicationRequest")) { return "CommunicationRequest"; }
    if (name.equals("CompartmentDefinition")) { return "CompartmentDefinition"; }
    if (name.equals("Composition")) { return "Composition"; }
    if (name.equals("ConceptMap")) { return "ConceptMap"; }
    if (name.equals("Condition")) { return "Condition"; }
    if (name.equals("Consent")) { return "Consent"; }
    if (name.equals("Contract")) { return "Contract"; }
    if (name.equals("Coverage")) { return "Coverage"; }
    if (name.equals("CoverageEligibilityRequest")) { return "EligibilityRequest"; }
    if (name.equals("CoverageEligibilityResponse")) { return "EligibilityResponse"; }
    if (name.equals("DetectedIssue")) { return "DetectedIssue"; }
    if (name.equals("Device")) { return "Device"; }
    if (name.equals("DeviceDefinition")) { return null; }
    if (name.equals("DeviceMetric")) { return "DeviceMetric"; }
    if (name.equals("DeviceRequest")) { return "DeviceRequest"; }
    if (name.equals("DeviceUseStatement")) { return "DeviceUseStatement"; }
    if (name.equals("DiagnosticReport")) { return "DiagnosticReport"; }
    if (name.equals("DocumentManifest")) { return "DocumentManifest"; }
    if (name.equals("DocumentReference")) { return "DocumentReference"; }
    if (name.equals("EffectEvidenceSynthesis")) { return null; }
    if (name.equals("Encounter")) { return "Encounter"; }
    if (name.equals("Endpoint")) { return "Endpoint"; }
    if (name.equals("EnrollmentRequest")) { return "EnrollmentRequest"; }
    if (name.equals("EnrollmentResponse")) { return "EnrollmentResponse"; }
    if (name.equals("EpisodeOfCare")) { return "EpisodeOfCare"; }
    if (name.equals("EventDefinition")) { return null; }
    if (name.equals("ExampleScenario")) { return null; }
    if (name.equals("ExplanationOfBenefit")) { return "ExplanationOfBenefit"; }
    if (name.equals("FamilyMemberHistory")) { return "FamilyMemberHistory"; }
    if (name.equals("Flag")) { return "Flag"; }
    if (name.equals("Goal")) { return "Goal"; }
    if (name.equals("GraphDefinition")) { return "GraphDefinition"; }
    if (name.equals("Group")) { return "Group"; }
    if (name.equals("GuidanceResponse")) { return "GuidanceResponse"; }
    if (name.equals("HealthcareService")) { return "HealthcareService"; }
    if (name.equals("ImagingStudy")) { return "ImagingStudy"; }
    if (name.equals("Immunization")) { return "Immunization"; }
    if (name.equals("ImmunizationEvaluation")) { return null; }
    if (name.equals("ImmunizationRecommendation")) { return "ImmunizationRecommendation"; }
    if (name.equals("ImplementationGuide")) { return "ImplementationGuide"; }
    if (name.equals("InsurancePlan")) { return null; }
    if (name.equals("Invoice")) { return null; }
    if (name.equals("Library")) { return "Library"; }
    if (name.equals("Linkage")) { return "Linkage"; }
    if (name.equals("List")) { return "List"; }
    if (name.equals("Location")) { return "Location"; }
    if (name.equals("Measure")) { return "Measure"; }
    if (name.equals("MeasureReport")) { return "MeasureReport"; }
    if (name.equals("Media")) { return "Media"; }
    if (name.equals("Medication")) { return "Medication"; }
    if (name.equals("MedicationAdministration")) { return "MedicationAdministration"; }
    if (name.equals("MedicationDispense")) { return "MedicationDispense"; }
    if (name.equals("MedicationKnowledge")) { return null; }
    if (name.equals("MedicationRequest")) { return "MedicationRequest"; }
    if (name.equals("MedicationStatement")) { return "MedicationStatement"; }
    if (name.equals("MedicinalProduct")) { return null; }
    if (name.equals("MedicinalProductAuthorization")) { return null; }
    if (name.equals("MedicinalProductContraindication")) { return null; }
    if (name.equals("MedicinalProductIndication")) { return null; }
    if (name.equals("MedicinalProductIngredient")) { return null; }
    if (name.equals("MedicinalProductInteraction")) { return null; }
    if (name.equals("MedicinalProductManufactured")) { return null; }
    if (name.equals("MedicinalProductPackaged")) { return null; }
    if (name.equals("MedicinalProductPharmaceutical")) { return null; }
    if (name.equals("MedicinalProductUndesirableEffect")) { return null; }
    if (name.equals("MessageDefinition")) { return "MessageDefinition"; }
    if (name.equals("MessageHeader")) { return "MessageHeader"; }
    if (name.equals("MolecularSequence")) { return "Sequence"; }
    if (name.equals("NamingSystem")) { return "NamingSystem"; }
    if (name.equals("NutritionOrder")) { return "NutritionOrder"; }
    if (name.equals("Observation")) { return "Observation"; }
    if (name.equals("ObservationDefinition")) { return null; }
    if (name.equals("OperationDefinition")) { return "OperationDefinition"; }
    if (name.equals("OperationOutcome")) { return "OperationOutcome"; }
    if (name.equals("Organization")) { return "Organization"; }
    if (name.equals("OrganizationAffiliation")) { return null; }
    if (name.equals("Parameters")) { return "Parameters"; }
    if (name.equals("Patient")) { return "Patient"; }
    if (name.equals("PaymentNotice")) { return "PaymentNotice"; }
    if (name.equals("PaymentReconciliation")) { return "PaymentReconciliation"; }
    if (name.equals("Person")) { return "Person"; }
    if (name.equals("PlanDefinition")) { return "PlanDefinition"; }
    if (name.equals("Practitioner")) { return "Practitioner"; }
    if (name.equals("PractitionerRole")) { return "PractitionerRole"; }
    if (name.equals("Procedure")) { return "Procedure"; }
    if (name.equals("Provenance")) { return "Provenance"; }
    if (name.equals("Questionnaire")) { return "Questionnaire"; }
    if (name.equals("QuestionnaireResponse")) { return "QuestionnaireResponse"; }
    if (name.equals("RelatedPerson")) { return "RelatedPerson"; }
    if (name.equals("RequestGroup")) { return "RequestGroup"; }
    if (name.equals("ResearchStudy")) { return "ResearchStudy"; }
    if (name.equals("ResearchSubject")) { return "ResearchSubject"; }
    if (name.equals("RiskAssessment")) { return "RiskAssessment"; }
    if (name.equals("Schedule")) { return "Schedule"; }
    if (name.equals("SearchParameter")) { return "SearchParameter"; }
    if (name.equals("ServiceRequest")) { return "ProcedureRequest"; }
    //     if (name.equals("ServiceRequest")) { return "ReferralRequest"; }
    if (name.equals("Slot")) { return "Slot"; }
    if (name.equals("Specimen")) { return "Specimen"; }
    if (name.equals("SpecimenDefinition")) { return null; }
    if (name.equals("StructureDefinition")) { return "StructureDefinition"; }
    // if (name.equals("StructureDefinition")) { return "DataElement"; }
    if (name.equals("StructureMap")) { return "StructureMap"; }
    if (name.equals("Subscription")) { return "Subscription"; }
    if (name.equals("Substance")) { return "Substance"; }
    if (name.equals("SubstancePolymer")) { return null; }
    if (name.equals("SubstanceReferenceInformation")) { return null; }
    if (name.equals("SubstanceSpecification")) { return null; }
    if (name.equals("SupplyDelivery")) { return "SupplyDelivery"; }
    if (name.equals("SupplyRequest")) { return "SupplyRequest"; }
    if (name.equals("Task")) { return "Task"; }
    if (name.equals("TerminologyCapabilities")) { return null; }
    if (name.equals("TestReport")) { return "TestReport"; }
    if (name.equals("TestScript")) { return "TestScript"; }
    if (name.equals("ValueSet")) { return "ValueSet"; }
    if (name.equals("VerificationResult")) { return null; }
    if (name.equals("VisionPrescription")) { return "VisionPrescription"; }
    return null;
  }

  public static String mapName2to3(String name) {
    if (Utilities.noString(name)) { return null; } 
    if (name.equals("AllergyIntolerance")) { return "AllergyIntolerance"; }
    if (name.equals("Appointment")) { return "Appointment"; }
    if (name.equals("AppointmentResponse")) { return "AppointmentResponse"; }
    if (name.equals("AuditEvent")) { return "AuditEvent"; }
    if (name.equals("Basic")) { return "Basic"; }
    if (name.equals("Binary")) { return "Binary"; }
    if (name.equals("BodySite")) { return "BodySite"; }
    if (name.equals("Bundle")) { return "Bundle"; }
    if (name.equals("Conformance")) { return "CapabilityStatement"; }
    if (name.equals("CarePlan")) { return "CarePlan"; }
    if (name.equals("Claim")) { return "Claim"; }
    if (name.equals("ClaimResponse")) { return "ClaimResponse"; }
    if (name.equals("ClinicalImpression")) { return "ClinicalImpression"; }
    if (name.equals("Communication")) { return "Communication"; }
    if (name.equals("CommunicationRequest")) { return "CommunicationRequest"; }
    if (name.equals("Composition")) { return "Composition"; }
    if (name.equals("ConceptMap")) { return "ConceptMap"; }
    if (name.equals("Condition")) { return "Condition"; }
    if (name.equals("Contract")) { return "Contract"; }
    if (name.equals("Coverage")) { return "Coverage"; }
    if (name.equals("DataElement")) { return "DataElement"; }
    if (name.equals("EligibilityRequest")) { return "EligibilityRequest"; }
    if (name.equals("EligibilityResponse")) { return "EligibilityResponse"; }
    if (name.equals("DetectedIssue")) { return "DetectedIssue"; }
    if (name.equals("Device")) { return "Device"; }
    if (name.equals("DeviceComponent")) { return "DeviceComponent"; }
    if (name.equals("DeviceMetric")) { return "DeviceMetric"; }
    if (name.equals("DeviceUseRequest")) { return "DeviceRequest"; }
    if (name.equals("DeviceUseStatement")) { return "DeviceUseStatement"; }
    if (name.equals("DiagnosticOrder")) { return "ProcedureRequest"; }
    if (name.equals("DiagnosticReport")) { return "DiagnosticReport"; }
    if (name.equals("DocumentManifest")) { return "DocumentManifest"; }
    if (name.equals("DocumentReference")) { return "DocumentReference"; }
    if (name.equals("Encounter")) { return "Encounter"; }
    if (name.equals("EnrollmentRequest")) { return "EnrollmentRequest"; }
    if (name.equals("EnrollmentResponse")) { return "EnrollmentResponse"; }
    if (name.equals("EpisodeOfCare")) { return "EpisodeOfCare"; }
    if (name.equals("ExplanationOfBenefit")) { return "ExplanationOfBenefit"; }
    if (name.equals("FamilyMemberHistory")) { return "FamilyMemberHistory"; }
    if (name.equals("Flag")) { return "Flag"; }
    if (name.equals("Goal")) { return "Goal"; }
    if (name.equals("Group")) { return "Group"; }
    if (name.equals("HealthcareService")) { return "HealthcareService"; }
    if (name.equals("ImagingObjectSelection")) { return null; } // != ImagingManifest
    if (name.equals("ImagingStudy")) { return "ImagingStudy"; }
    if (name.equals("Immunization")) { return "Immunization"; }
    if (name.equals("ImmunizationRecommendation")) { return "ImmunizationRecommendation"; }
    if (name.equals("ImplementationGuide")) { return "ImplementationGuide"; }
    if (name.equals("List")) { return "List"; }
    if (name.equals("Location")) { return "Location"; }
    if (name.equals("Media")) { return "Media"; }
    if (name.equals("Medication")) { return "Medication"; }
    if (name.equals("MedicationAdministration")) { return "MedicationAdministration"; }
    if (name.equals("MedicationDispense")) { return "MedicationDispense"; }
    if (name.equals("MedicationOrder")) { return "MedicationRequest"; }
    if (name.equals("MedicationStatement")) { return "MedicationStatement"; }
    if (name.equals("MessageHeader")) { return "MessageHeader"; }
    if (name.equals("NamingSystem")) { return "NamingSystem"; }
    if (name.equals("NutritionOrder")) { return "NutritionOrder"; }
    if (name.equals("Observation")) { return "Observation"; }
    if (name.equals("OperationDefinition")) { return "OperationDefinition"; }
    if (name.equals("OperationOutcome")) { return "OperationOutcome"; }
    if (name.equals("Order")) { return "Task"; }
    if (name.equals("OrderResponse")) { return "Task"; }
    if (name.equals("Organization")) { return "Organization"; }
    if (name.equals("Parameters")) { return "Parameters"; }
    if (name.equals("Patient")) { return "Patient"; }
    if (name.equals("PaymentNotice")) { return "PaymentNotice"; }
    if (name.equals("PaymentReconciliation")) { return "PaymentReconciliation"; }
    if (name.equals("Person")) { return "Person"; }
    if (name.equals("Practitioner")) { return "Practitioner"; }
    if (name.equals("Procedure")) { return "Procedure"; }
    if (name.equals("ProcessRequest")) { return "ProcessRequest"; }
    if (name.equals("ProcessResponse")) { return "ProcessResponse"; }
    if (name.equals("Provenance")) { return "Provenance"; }
    if (name.equals("Questionnaire")) { return "Questionnaire"; }
    if (name.equals("QuestionnaireResponse")) { return "QuestionnaireResponse"; }
    if (name.equals("ReferralRequest")) { return "ReferralRequest"; }
    if (name.equals("RelatedPerson")) { return "RelatedPerson"; }
    if (name.equals("RiskAssessment")) { return "RiskAssessment"; }
    if (name.equals("Schedule")) { return "Schedule"; }
    if (name.equals("SearchParameter")) { return "SearchParameter"; }
    if (name.equals("ProcedureRequest")) { return "ProcedureRequest"; }
    if (name.equals("Slot")) { return "Slot"; }
    if (name.equals("Specimen")) { return "Specimen"; }
    if (name.equals("StructureDefinition")) { return "StructureDefinition"; }
    if (name.equals("Subscription")) { return "Subscription"; }
    if (name.equals("Substance")) { return "Substance"; }
    if (name.equals("SupplyDelivery")) { return "SupplyDelivery"; }
    if (name.equals("SupplyRequest")) { return "SupplyRequest"; }
    if (name.equals("TestScript")) { return "TestScript"; }
    if (name.equals("ValueSet")) { return "ValueSet"; }
    // if (name.equals("ValueSet")) { return "CodeSystem"; }
    if (name.equals("VisionPrescription")) { return "VisionPrescription"; }
    return null;
  }

  public static String mapName3to2(String name) {
    if (Utilities.noString(name)) { return null; } 
    if (name.equals("Account")) { return null; }
    if (name.equals("ActivityDefinition")) { return null; }
    if (name.equals("AdverseEvent")) { return null; }
    if (name.equals("AllergyIntolerance")) { return "AllergyIntolerance"; }
    if (name.equals("Appointment")) { return "Appointment"; }
    if (name.equals("AppointmentResponse")) { return "AppointmentResponse"; }
    if (name.equals("AuditEvent")) { return "AuditEvent"; }
    if (name.equals("Basic")) { return "Basic"; }
    if (name.equals("Binary")) { return "Binary"; }
    if (name.equals("BodySite")) { return "BodySite"; }
    if (name.equals("Bundle")) { return "Bundle"; }
    if (name.equals("CapabilityStatement")) { return "Conformance"; }
    if (name.equals("CarePlan")) { return "CarePlan"; }
    if (name.equals("CareTeam")) { return null; }
    if (name.equals("ChargeItem")) { return null; }
    if (name.equals("Claim")) { return "Claim"; }
    if (name.equals("ClaimResponse")) { return "ClaimResponse"; }
    if (name.equals("ClinicalImpression")) { return "ClinicalImpression"; }
    if (name.equals("CodeSystem")) { return "ValueSet"; }
    if (name.equals("Communication")) { return "Communication"; }
    if (name.equals("CommunicationRequest")) { return "CommunicationRequest"; }
    if (name.equals("CompartmentDefinition")) { return null; }
    if (name.equals("Composition")) { return "Composition"; }
    if (name.equals("ConceptMap")) { return "ConceptMap"; }
    if (name.equals("Condition")) { return "Condition"; }
    if (name.equals("Consent")) { return null; }
    if (name.equals("Contract")) { return "Contract"; }
    if (name.equals("Coverage")) { return "Coverage"; }
    if (name.equals("DataElement")) { return "DataElement"; }
    if (name.equals("EligibilityRequest")) { return "EligibilityRequest"; }
    if (name.equals("EligibilityResponse")) { return "EligibilityResponse"; }
    if (name.equals("DetectedIssue")) { return "DetectedIssue"; }
    if (name.equals("Device")) { return "Device"; }
    if (name.equals("DeviceComponent")) { return "DeviceComponent"; }
    if (name.equals("DeviceMetric")) { return "DeviceMetric"; }
    if (name.equals("DeviceRequest")) { return "DeviceUseRequest"; }
    if (name.equals("DeviceUseStatement")) { return "DeviceUseStatement"; }
    if (name.equals("ProcedureRequest")) { return "DiagnosticOrder"; }
    if (name.equals("DiagnosticReport")) { return "DiagnosticReport"; }
    if (name.equals("DocumentManifest")) { return "DocumentManifest"; }
    if (name.equals("DocumentReference")) { return "DocumentReference"; }
    if (name.equals("Encounter")) { return "Encounter"; }
    if (name.equals("Endpoint")) { return null; }
    if (name.equals("EnrollmentRequest")) { return "EnrollmentRequest"; }
    if (name.equals("EnrollmentResponse")) { return "EnrollmentResponse"; }
    if (name.equals("EpisodeOfCare")) { return "EpisodeOfCare"; }
    if (name.equals("ExpansionProfile")) { return null; }
    if (name.equals("ExplanationOfBenefit")) { return "ExplanationOfBenefit"; }
    if (name.equals("FamilyMemberHistory")) { return "FamilyMemberHistory"; }
    if (name.equals("Flag")) { return "Flag"; }
    if (name.equals("Goal")) { return "Goal"; }
    if (name.equals("GraphDefinition")) { return null; }
    if (name.equals("Group")) { return "Group"; }
    if (name.equals("GuidanceResponse")) { return null; }
    if (name.equals("HealthcareService")) { return "HealthcareService"; }
    if (name.equals("ImagingManifest")) { return null; } // != ImagingObjectSelection
    if (name.equals("ImagingStudy")) { return "ImagingStudy"; }
    if (name.equals("Immunization")) { return "Immunization"; }
    if (name.equals("ImmunizationRecommendation")) { return "ImmunizationRecommendation"; }
    if (name.equals("ImplementationGuide")) { return "ImplementationGuide"; }
    if (name.equals("Library")) { return null; }
    if (name.equals("Linkage")) { return null; }
    if (name.equals("List")) { return "List"; }
    if (name.equals("Location")) { return "Location"; }
    if (name.equals("Measure")) { return null; }
    if (name.equals("MeasureReport")) { return null; }
    if (name.equals("Media")) { return "Media"; }
    if (name.equals("Medication")) { return "Medication"; }
    if (name.equals("MedicationAdministration")) { return "MedicationAdministration"; }
    if (name.equals("MedicationDispense")) { return "MedicationDispense"; }
    if (name.equals("MedicationRequest")) { return "MedicationOrder"; }
    if (name.equals("MedicationStatement")) { return "MedicationStatement"; }
    if (name.equals("MessageDefinition")) { return null; }
    if (name.equals("MessageHeader")) { return "MessageHeader"; }
    if (name.equals("Sequence")) { return null; }
    if (name.equals("NamingSystem")) { return "NamingSystem"; }
    if (name.equals("NutritionOrder")) { return "NutritionOrder"; }
    if (name.equals("Observation")) { return "Observation"; }
    if (name.equals("OperationDefinition")) { return "OperationDefinition"; }
    if (name.equals("OperationOutcome")) { return "OperationOutcome"; }
    if (name.equals("Task")) { return "Order"; }
    // if (name.equals("Task")) { return "OrderResponse"; }
    if (name.equals("Organization")) { return "Organization"; }
    if (name.equals("Parameters")) { return "Parameters"; }
    if (name.equals("Patient")) { return "Patient"; }
    if (name.equals("PaymentNotice")) { return "PaymentNotice"; }
    if (name.equals("PaymentReconciliation")) { return "PaymentReconciliation"; }
    if (name.equals("Person")) { return "Person"; }
    if (name.equals("PlanDefinition")) { return null; }
    if (name.equals("Practitioner")) { return "Practitioner"; }
    if (name.equals("PractitionerRole")) { return null; }
    if (name.equals("Procedure")) { return "Procedure"; }
    if (name.equals("ProcessRequest")) { return "ProcessRequest"; }
    if (name.equals("ProcessResponse")) { return "ProcessResponse"; }
    if (name.equals("Provenance")) { return "Provenance"; }
    if (name.equals("Questionnaire")) { return "Questionnaire"; }
    if (name.equals("QuestionnaireResponse")) { return "QuestionnaireResponse"; }
    if (name.equals("ReferralRequest")) { return "ReferralRequest"; }
    if (name.equals("RelatedPerson")) { return "RelatedPerson"; }
    if (name.equals("RequestGroup")) { return null; }
    if (name.equals("ResearchStudy")) { return null; }
    if (name.equals("ResearchSubject")) { return null; }
    if (name.equals("RiskAssessment")) { return "RiskAssessment"; }
    if (name.equals("Schedule")) { return "Schedule"; }
    if (name.equals("SearchParameter")) { return "SearchParameter"; }
    if (name.equals("ServiceDefinition")) { return null; }
    if (name.equals("ProcedureRequest")) { return "ProcedureRequest"; }
    if (name.equals("Slot")) { return "Slot"; }
    if (name.equals("Specimen")) { return "Specimen"; }
    if (name.equals("StructureDefinition")) { return "StructureDefinition"; }
    if (name.equals("StructureMap")) { return null; }
    if (name.equals("Subscription")) { return "Subscription"; }
    if (name.equals("Substance")) { return "Substance"; }
    if (name.equals("SupplyDelivery")) { return "SupplyDelivery"; }
    if (name.equals("SupplyRequest")) { return "SupplyRequest"; }
    if (name.equals("Task")) { return null; }
    if (name.equals("TestReport")) { return null; }
    if (name.equals("TestScript")) { return "TestScript"; }
    if (name.equals("ValueSet")) { return "ValueSet"; }
    if (name.equals("VisionPrescription")) { return "VisionPrescription"; }
    return null;
  }


}
