// This file is generated code - do not edit it.
//
// Generated by the HL7 FHIR code generator (org.hl7.fhir.core: core code generator)
// from hl7.fhir.r6.core#6.0.0-ballot5 (version 6.0.0-ballot5)
// on Sun, Aug 16, 2026 10:17+1000.
//
// Any changes made here will be lost the next time the generator is run. To change
// this file, change the definitions it is generated from, or change the generator.
package org.hl7.fhir.model.core;

/*
  Copyright (c) 2011+, HL7, Inc.
  All rights reserved.
  
  Redistribution and use in source and binary forms, with or without modification,
  are permitted provided that the following conditions are met:
  
   * Redistributions of source code must retain the above copyright notice, this
     list of conditions and the following disclaimer
   * Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation
     and/or other materials provided with the distribution.
   * Neither the name of HL7 nor the names of its contributors may be used to 
     endorse or promote products derived from this software without specific 
     prior written permission.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.
  */

import java.util.*;
import org.hl7.fhir.utilities.Utilities;
import org.hl7.fhir.model.core.Enumerations.*;
import org.hl7.fhir.instance.model.api.IBaseDatatypeElement;
import java.util.EnumSet;
import org.hl7.fhir.model.*;
import org.hl7.fhir.model.Base.CopyObjectOptions;
import org.hl7.fhir.exceptions.FHIRException;
import org.hl7.fhir.instance.model.api.ICompositeType;
import ca.uhn.fhir.model.api.annotation.Child;
import ca.uhn.fhir.model.api.annotation.ChildOrder;
import ca.uhn.fhir.model.api.annotation.DatatypeDef;
import ca.uhn.fhir.model.api.annotation.Description;
import ca.uhn.fhir.model.api.annotation.Block;

/**
 * ContactPoint Type: Details for all kinds of technology mediated contact points for a person or organization, including telephone, email, etc.
 */
@DatatypeDef(name="ContactPoint")
@javax.annotation.processing.Generated(value = "org.hl7.fhir.core.generator.engine.JavaCoreGenerator", comments = "generated from hl7.fhir.r6.core#6.0.0-ballot5")
public class ContactPoint extends DataType implements ICompositeType {

    public enum ContactPointSystem {
        /**
         * The value is a telephone number used for voice calls. Use of full international numbers starting with + is recommended to enable automatic dialing support but not required.
         */
        PHONE, 
        /**
         * The value is a fax machine. Use of full international numbers starting with + is recommended to enable automatic dialing support but not required.
         */
        FAX, 
        /**
         * The value is an email address.
         */
        EMAIL, 
        /**
         * The value is a pager number. These may be local pager numbers that are only usable on a particular pager system.
         */
        PAGER, 
        /**
         * A contact that is not a phone, fax, pager or email address and is expressed as a URL.  This is intended for various institutional or personal contacts including web sites, blogs, Skype, Twitter, Facebook, etc. Do not use for email addresses.
         */
        URL, 
        /**
         * A contact that can be used for sending a sms message (e.g. mobile phones, some landlines).
         */
        SMS, 
        /**
         * A contact that is not a phone, fax, page or email address and is not expressible as a URL.  E.g. Internal mail address.  This SHOULD NOT be used for contacts that are expressible as a URL (e.g. Skype, Twitter, Facebook, etc.)  Extensions may be used to distinguish "other" contact types.
         */
        OTHER, 
        /**
         * added to help the parsers with the generic types
         */
        NULL;
        public static ContactPointSystem fromCode(String codeString) throws FHIRException {
            if (codeString == null || "".equals(codeString))
                return null;
        if ("phone".equals(codeString))
          return PHONE;
        if ("fax".equals(codeString))
          return FAX;
        if ("email".equals(codeString))
          return EMAIL;
        if ("pager".equals(codeString))
          return PAGER;
        if ("url".equals(codeString))
          return URL;
        if ("sms".equals(codeString))
          return SMS;
        if ("other".equals(codeString))
          return OTHER;
        if (Configuration.isAcceptInvalidEnums())
          return null;
        else
          throw new FHIRException("Unknown ContactPointSystem code '"+codeString+"'");
        }
        public String toCode() {
          switch (this) {
            case PHONE: return "phone";
            case FAX: return "fax";
            case EMAIL: return "email";
            case PAGER: return "pager";
            case URL: return "url";
            case SMS: return "sms";
            case OTHER: return "other";
            case NULL: return null;
            default: return "?";
          }
        }
        public String getSystem() {
          switch (this) {
            case PHONE: return "http://hl7.org/fhir/contact-point-system";
            case FAX: return "http://hl7.org/fhir/contact-point-system";
            case EMAIL: return "http://hl7.org/fhir/contact-point-system";
            case PAGER: return "http://hl7.org/fhir/contact-point-system";
            case URL: return "http://hl7.org/fhir/contact-point-system";
            case SMS: return "http://hl7.org/fhir/contact-point-system";
            case OTHER: return "http://hl7.org/fhir/contact-point-system";
            case NULL: return null;
            default: return "?";
          }
        }
        public String getDefinition() {
          switch (this) {
            case PHONE: return "The value is a telephone number used for voice calls. Use of full international numbers starting with + is recommended to enable automatic dialing support but not required.";
            case FAX: return "The value is a fax machine. Use of full international numbers starting with + is recommended to enable automatic dialing support but not required.";
            case EMAIL: return "The value is an email address.";
            case PAGER: return "The value is a pager number. These may be local pager numbers that are only usable on a particular pager system.";
            case URL: return "A contact that is not a phone, fax, pager or email address and is expressed as a URL.  This is intended for various institutional or personal contacts including web sites, blogs, Skype, Twitter, Facebook, etc. Do not use for email addresses.";
            case SMS: return "A contact that can be used for sending a sms message (e.g. mobile phones, some landlines).";
            case OTHER: return "A contact that is not a phone, fax, page or email address and is not expressible as a URL.  E.g. Internal mail address.  This SHOULD NOT be used for contacts that are expressible as a URL (e.g. Skype, Twitter, Facebook, etc.)  Extensions may be used to distinguish \"other\" contact types.";
            case NULL: return null;
            default: return "?";
          }
        }
        public String getDisplay() {
          switch (this) {
            case PHONE: return "Phone";
            case FAX: return "Fax";
            case EMAIL: return "Email";
            case PAGER: return "Pager";
            case URL: return "URL";
            case SMS: return "SMS";
            case OTHER: return "Other";
            case NULL: return null;
            default: return "?";
          }
        }
    }

  public static class ContactPointSystemEnumFactory implements EnumFactory<ContactPointSystem> {
    private final IModelContext modelContext;
    public ContactPointSystemEnumFactory(IModelContext modelContext) {
      this.modelContext = modelContext;
    }
    public ContactPointSystemEnumFactory() {
      this(null);
    }
    public ContactPointSystem fromCode(String codeString) throws IllegalArgumentException {
      if (codeString == null || "".equals(codeString))
            if (codeString == null || "".equals(codeString))
                return null;
        if ("phone".equals(codeString))
          return ContactPointSystem.PHONE;
        if ("fax".equals(codeString))
          return ContactPointSystem.FAX;
        if ("email".equals(codeString))
          return ContactPointSystem.EMAIL;
        if ("pager".equals(codeString))
          return ContactPointSystem.PAGER;
        if ("url".equals(codeString))
          return ContactPointSystem.URL;
        if ("sms".equals(codeString))
          return ContactPointSystem.SMS;
        if ("other".equals(codeString))
          return ContactPointSystem.OTHER;
        throw new IllegalArgumentException("Unknown ContactPointSystem code '"+codeString+"'");
        }
        public Enumeration<ContactPointSystem> fromType(PrimitiveType<?> code) throws FHIRException {
          if (code == null)
            return null;
          if (code.isEmpty())
            return new Enumeration<ContactPointSystem>(modelContext, this, ContactPointSystem.NULL, code);
          String codeString = ((PrimitiveType) code).asStringValue();
          if (codeString == null || "".equals(codeString))
            return new Enumeration<ContactPointSystem>(modelContext, this, ContactPointSystem.NULL, code);
        if ("phone".equals(codeString))
          return new Enumeration<ContactPointSystem>(modelContext, this, ContactPointSystem.PHONE, code);
        if ("fax".equals(codeString))
          return new Enumeration<ContactPointSystem>(modelContext, this, ContactPointSystem.FAX, code);
        if ("email".equals(codeString))
          return new Enumeration<ContactPointSystem>(modelContext, this, ContactPointSystem.EMAIL, code);
        if ("pager".equals(codeString))
          return new Enumeration<ContactPointSystem>(modelContext, this, ContactPointSystem.PAGER, code);
        if ("url".equals(codeString))
          return new Enumeration<ContactPointSystem>(modelContext, this, ContactPointSystem.URL, code);
        if ("sms".equals(codeString))
          return new Enumeration<ContactPointSystem>(modelContext, this, ContactPointSystem.SMS, code);
        if ("other".equals(codeString))
          return new Enumeration<ContactPointSystem>(modelContext, this, ContactPointSystem.OTHER, code);
        throw new FHIRException("Unknown ContactPointSystem code '"+codeString+"'");
        }
    public String toCode(ContactPointSystem code) {
      if (code == ContactPointSystem.PHONE)
        return "phone";
      if (code == ContactPointSystem.FAX)
        return "fax";
      if (code == ContactPointSystem.EMAIL)
        return "email";
      if (code == ContactPointSystem.PAGER)
        return "pager";
      if (code == ContactPointSystem.URL)
        return "url";
      if (code == ContactPointSystem.SMS)
        return "sms";
      if (code == ContactPointSystem.OTHER)
        return "other";
      return "?";
      }
    public String toSystem(ContactPointSystem code) {
      return code.getSystem();
      }
    }

    public enum ContactPointUse {
        /**
         * A communication contact point at a home; attempted contacts for business purposes might intrude privacy and chances are one will contact family or other household members instead of the person one wishes to call. Typically used with urgent cases, or if no other contacts are available.
         */
        HOME, 
        /**
         * An office contact point. First choice for business related contacts during business hours.
         */
        WORK, 
        /**
         * A temporary contact point. The period can provide more detailed information.
         */
        TEMP, 
        /**
         * This contact point is no longer in use (or was never correct, but retained for records).
         */
        OLD, 
        /**
         * A telecommunication device that moves and stays with its owner. May have characteristics of all other use codes, suitable for urgent matters, not the first choice for routine business.
         */
        MOBILE, 
        /**
         * added to help the parsers with the generic types
         */
        NULL;
        public static ContactPointUse fromCode(String codeString) throws FHIRException {
            if (codeString == null || "".equals(codeString))
                return null;
        if ("home".equals(codeString))
          return HOME;
        if ("work".equals(codeString))
          return WORK;
        if ("temp".equals(codeString))
          return TEMP;
        if ("old".equals(codeString))
          return OLD;
        if ("mobile".equals(codeString))
          return MOBILE;
        if (Configuration.isAcceptInvalidEnums())
          return null;
        else
          throw new FHIRException("Unknown ContactPointUse code '"+codeString+"'");
        }
        public String toCode() {
          switch (this) {
            case HOME: return "home";
            case WORK: return "work";
            case TEMP: return "temp";
            case OLD: return "old";
            case MOBILE: return "mobile";
            case NULL: return null;
            default: return "?";
          }
        }
        public String getSystem() {
          switch (this) {
            case HOME: return "http://hl7.org/fhir/contact-point-use";
            case WORK: return "http://hl7.org/fhir/contact-point-use";
            case TEMP: return "http://hl7.org/fhir/contact-point-use";
            case OLD: return "http://hl7.org/fhir/contact-point-use";
            case MOBILE: return "http://hl7.org/fhir/contact-point-use";
            case NULL: return null;
            default: return "?";
          }
        }
        public String getDefinition() {
          switch (this) {
            case HOME: return "A communication contact point at a home; attempted contacts for business purposes might intrude privacy and chances are one will contact family or other household members instead of the person one wishes to call. Typically used with urgent cases, or if no other contacts are available.";
            case WORK: return "An office contact point. First choice for business related contacts during business hours.";
            case TEMP: return "A temporary contact point. The period can provide more detailed information.";
            case OLD: return "This contact point is no longer in use (or was never correct, but retained for records).";
            case MOBILE: return "A telecommunication device that moves and stays with its owner. May have characteristics of all other use codes, suitable for urgent matters, not the first choice for routine business.";
            case NULL: return null;
            default: return "?";
          }
        }
        public String getDisplay() {
          switch (this) {
            case HOME: return "Home";
            case WORK: return "Work";
            case TEMP: return "Temp";
            case OLD: return "Old";
            case MOBILE: return "Mobile";
            case NULL: return null;
            default: return "?";
          }
        }
    }

  public static class ContactPointUseEnumFactory implements EnumFactory<ContactPointUse> {
    private final IModelContext modelContext;
    public ContactPointUseEnumFactory(IModelContext modelContext) {
      this.modelContext = modelContext;
    }
    public ContactPointUseEnumFactory() {
      this(null);
    }
    public ContactPointUse fromCode(String codeString) throws IllegalArgumentException {
      if (codeString == null || "".equals(codeString))
            if (codeString == null || "".equals(codeString))
                return null;
        if ("home".equals(codeString))
          return ContactPointUse.HOME;
        if ("work".equals(codeString))
          return ContactPointUse.WORK;
        if ("temp".equals(codeString))
          return ContactPointUse.TEMP;
        if ("old".equals(codeString))
          return ContactPointUse.OLD;
        if ("mobile".equals(codeString))
          return ContactPointUse.MOBILE;
        throw new IllegalArgumentException("Unknown ContactPointUse code '"+codeString+"'");
        }
        public Enumeration<ContactPointUse> fromType(PrimitiveType<?> code) throws FHIRException {
          if (code == null)
            return null;
          if (code.isEmpty())
            return new Enumeration<ContactPointUse>(modelContext, this, ContactPointUse.NULL, code);
          String codeString = ((PrimitiveType) code).asStringValue();
          if (codeString == null || "".equals(codeString))
            return new Enumeration<ContactPointUse>(modelContext, this, ContactPointUse.NULL, code);
        if ("home".equals(codeString))
          return new Enumeration<ContactPointUse>(modelContext, this, ContactPointUse.HOME, code);
        if ("work".equals(codeString))
          return new Enumeration<ContactPointUse>(modelContext, this, ContactPointUse.WORK, code);
        if ("temp".equals(codeString))
          return new Enumeration<ContactPointUse>(modelContext, this, ContactPointUse.TEMP, code);
        if ("old".equals(codeString))
          return new Enumeration<ContactPointUse>(modelContext, this, ContactPointUse.OLD, code);
        if ("mobile".equals(codeString))
          return new Enumeration<ContactPointUse>(modelContext, this, ContactPointUse.MOBILE, code);
        throw new FHIRException("Unknown ContactPointUse code '"+codeString+"'");
        }
    public String toCode(ContactPointUse code) {
      if (code == ContactPointUse.HOME)
        return "home";
      if (code == ContactPointUse.WORK)
        return "work";
      if (code == ContactPointUse.TEMP)
        return "temp";
      if (code == ContactPointUse.OLD)
        return "old";
      if (code == ContactPointUse.MOBILE)
        return "mobile";
      return "?";
      }
    public String toSystem(ContactPointUse code) {
      return code.getSystem();
      }
    }

    /**
     * Telecommunications form for contact point - what communications system is required to make use of the contact.
     */
    @Child(name = "system", type = {CodeType.class}, order=0, min=0, max=1, modifier=false, summary=true)
    @Description(shortDefinition="phone | fax | email | pager | url | sms | other")
    @ca.uhn.fhir.model.api.annotation.Binding(valueSet="http://hl7.org/fhir/ValueSet/contact-point-system")
    protected Enumeration<ContactPointSystem> system;

    /**
     * The actual contact point details, in a form that is meaningful to the designated communication system (i.e. phone number or email address).
     */
    @Child(name = "value", type = {StringType.class}, order=1, min=0, max=1, modifier=false, summary=true)
    @Description(shortDefinition="The actual contact point details")
    protected StringType value;

    /**
     * Identifies the purpose for the contact point.
     */
    @Child(name = "use", type = {CodeType.class}, order=2, min=0, max=1, modifier=true, summary=true)
    @Description(shortDefinition="home | work | temp | old | mobile - purpose of this contact point")
    @ca.uhn.fhir.model.api.annotation.Binding(valueSet="http://hl7.org/fhir/ValueSet/contact-point-use")
    protected Enumeration<ContactPointUse> use;

    /**
     * Specifies a preferred order in which to use a set of contacts. ContactPoints with lower rank values are more preferred than those with higher rank values.
     */
    @Child(name = "rank", type = {PositiveIntType.class}, order=3, min=0, max=1, modifier=false, summary=true)
    @Description(shortDefinition="Specify preferred order of use (1 = highest)")
    protected PositiveIntType rank;

    /**
     * Time period when the contact point was/is in use.
     */
    @Child(name = "period", type = {Period.class}, order=4, min=0, max=1, modifier=false, summary=true)
    @Description(shortDefinition="Time period when the contact point was/is in use")
    protected Period period;

    private static final long serialVersionUID = 1509610874L;

  /**
   * Constructor
   */
    public ContactPoint() {
      super();
    }

  /**
   * Constructor
   *
   * @param context the model context this object belongs to - all objects in a tree must share the same context (see Base.modelContext)
   */
    public ContactPoint(IModelContext modelContext) {
      super();
      this.modelContext = modelContext;
    }

    /**
     * @return {@link #system} (Telecommunications form for contact point - what communications system is required to make use of the contact.). This is the underlying object with id, value and extensions. The accessor "getSystem" gives direct access to the value
     */
    public Enumeration<ContactPointSystem> getSystemElement() { 
      if (this.system == null)
        if (Configuration.errorOnAutoCreate())
          throw new Error("Attempt to auto-create ContactPoint.system");
        else if (Configuration.doAutoCreate())
          this.system = new Enumeration<ContactPointSystem>(modelContext, new ContactPointSystemEnumFactory(modelContext)); // bb
      return this.system;
    }

    public boolean hasSystemElement() { 
      return this.system != null && !this.system.isEmpty();
    }

    public boolean hasSystem() { 
      return this.system != null && !this.system.isEmpty();
    }

    /**
     * @param value {@link #system} (Telecommunications form for contact point - what communications system is required to make use of the contact.). This is the underlying object with id, value and extensions. The accessor "getSystem" gives direct access to the value
     */
    public ContactPoint setSystemElement(Enumeration<ContactPointSystem> value) { 
      if (value != null) {
        value.setModelContext(this.modelContext);
      }
      this.system = value;
      return this;
    }

    /**
     * @return Telecommunications form for contact point - what communications system is required to make use of the contact.
     */
    public ContactPointSystem getSystem() { 
      return this.system == null ? null : this.system.getValue();
    }

    /**
     * @param value Telecommunications form for contact point - what communications system is required to make use of the contact.
     */
    public ContactPoint setSystem(ContactPointSystem value) { 
      if (value == null)
        this.system = null;
      else {
        if (this.system == null)
          this.system = new Enumeration<ContactPointSystem>(modelContext, new ContactPointSystemEnumFactory(modelContext));
        this.system.setValue(value);
      }
      return this;
    }

    /**
     * @return {@link #value} (The actual contact point details, in a form that is meaningful to the designated communication system (i.e. phone number or email address).). This is the underlying object with id, value and extensions. The accessor "getValue" gives direct access to the value
     */
    public StringType getValueElement() { 
      if (this.value == null)
        if (Configuration.errorOnAutoCreate())
          throw new Error("Attempt to auto-create ContactPoint.value");
        else if (Configuration.doAutoCreate())
          this.value = new StringType(modelContext); // bb
      return this.value;
    }

    public boolean hasValueElement() { 
      return this.value != null && !this.value.isEmpty();
    }

    public boolean hasValue() { 
      return this.value != null && !this.value.isEmpty();
    }

    /**
     * @param value {@link #value} (The actual contact point details, in a form that is meaningful to the designated communication system (i.e. phone number or email address).). This is the underlying object with id, value and extensions. The accessor "getValue" gives direct access to the value
     */
    public ContactPoint setValueElement(StringType value) { 
      if (value != null) {
        value.setModelContext(this.modelContext);
      }
      this.value = value;
      return this;
    }

    /**
     * @return The actual contact point details, in a form that is meaningful to the designated communication system (i.e. phone number or email address).
     */
    public String getValue() { 
      return this.value == null ? null : this.value.getValue();
    }

    /**
     * @param value The actual contact point details, in a form that is meaningful to the designated communication system (i.e. phone number or email address).
     */
    public ContactPoint setValue(String value) { 
      if (Utilities.noString(value))
        this.value = null;
      else {
        if (this.value == null)
          this.value = new StringType(modelContext);
        this.value.setValue(value);
      }
      return this;
    }

    /**
     * @return {@link #use} (Identifies the purpose for the contact point.). This is the underlying object with id, value and extensions. The accessor "getUse" gives direct access to the value
     */
    public Enumeration<ContactPointUse> getUseElement() { 
      if (this.use == null)
        if (Configuration.errorOnAutoCreate())
          throw new Error("Attempt to auto-create ContactPoint.use");
        else if (Configuration.doAutoCreate())
          this.use = new Enumeration<ContactPointUse>(modelContext, new ContactPointUseEnumFactory(modelContext)); // bb
      return this.use;
    }

    public boolean hasUseElement() { 
      return this.use != null && !this.use.isEmpty();
    }

    public boolean hasUse() { 
      return this.use != null && !this.use.isEmpty();
    }

    /**
     * @param value {@link #use} (Identifies the purpose for the contact point.). This is the underlying object with id, value and extensions. The accessor "getUse" gives direct access to the value
     */
    public ContactPoint setUseElement(Enumeration<ContactPointUse> value) { 
      if (value != null) {
        value.setModelContext(this.modelContext);
      }
      this.use = value;
      return this;
    }

    /**
     * @return Identifies the purpose for the contact point.
     */
    public ContactPointUse getUse() { 
      return this.use == null ? null : this.use.getValue();
    }

    /**
     * @param value Identifies the purpose for the contact point.
     */
    public ContactPoint setUse(ContactPointUse value) { 
      if (value == null)
        this.use = null;
      else {
        if (this.use == null)
          this.use = new Enumeration<ContactPointUse>(modelContext, new ContactPointUseEnumFactory(modelContext));
        this.use.setValue(value);
      }
      return this;
    }

    /**
     * @return {@link #rank} (Specifies a preferred order in which to use a set of contacts. ContactPoints with lower rank values are more preferred than those with higher rank values.). This is the underlying object with id, value and extensions. The accessor "getRank" gives direct access to the value
     */
    public PositiveIntType getRankElement() { 
      if (this.rank == null)
        if (Configuration.errorOnAutoCreate())
          throw new Error("Attempt to auto-create ContactPoint.rank");
        else if (Configuration.doAutoCreate())
          this.rank = new PositiveIntType(modelContext); // bb
      return this.rank;
    }

    public boolean hasRankElement() { 
      return this.rank != null && !this.rank.isEmpty();
    }

    public boolean hasRank() { 
      return this.rank != null && !this.rank.isEmpty();
    }

    /**
     * @param value {@link #rank} (Specifies a preferred order in which to use a set of contacts. ContactPoints with lower rank values are more preferred than those with higher rank values.). This is the underlying object with id, value and extensions. The accessor "getRank" gives direct access to the value
     */
    public ContactPoint setRankElement(PositiveIntType value) { 
      if (value != null) {
        value.setModelContext(this.modelContext);
      }
      this.rank = value;
      return this;
    }

    /**
     * @return Specifies a preferred order in which to use a set of contacts. ContactPoints with lower rank values are more preferred than those with higher rank values.
     */
    public int getRank() { 
      return this.rank == null || this.rank.isEmpty() ? 0 : this.rank.getValue();
    }

    /**
     * @param value Specifies a preferred order in which to use a set of contacts. ContactPoints with lower rank values are more preferred than those with higher rank values.
     */
    public ContactPoint setRank(int value) { 
        if (this.rank == null)
          this.rank = new PositiveIntType(modelContext);
        this.rank.setValue(value);
      return this;
    }

    /**
     * @return {@link #period} (Time period when the contact point was/is in use.)
     */
    public Period getPeriod() { 
      if (this.period == null)
        if (Configuration.errorOnAutoCreate())
          throw new Error("Attempt to auto-create ContactPoint.period");
        else if (Configuration.doAutoCreate())
          this.period = new Period(this.modelContext); // cc
      return this.period;
    }

    public boolean hasPeriod() { 
      return this.period != null && !this.period.isEmpty();
    }

    /**
     * @param value {@link #period} (Time period when the contact point was/is in use.)
     */
    public ContactPoint setPeriod(Period value) { 
      if (value != null) {
        value.setModelContext(this.modelContext);
      }
      this.period = value;
      return this;
    }

      protected void listChildren(List<Property> children) {
        super.listChildren(children);
        children.add(new Property("system", "code", "Telecommunications form for contact point - what communications system is required to make use of the contact.", 0, 1, system));
        children.add(new Property("value", "string", "The actual contact point details, in a form that is meaningful to the designated communication system (i.e. phone number or email address).", 0, 1, value));
        children.add(new Property("use", "code", "Identifies the purpose for the contact point.", 0, 1, use));
        children.add(new Property("rank", "positiveInt", "Specifies a preferred order in which to use a set of contacts. ContactPoints with lower rank values are more preferred than those with higher rank values.", 0, 1, rank));
        children.add(new Property("period", "Period", "Time period when the contact point was/is in use.", 0, 1, period));
      }

      @Override
      public Property getNamedProperty(String _name, boolean _checkValid) throws FHIRException {
        switch (_name) {
        case "system":  return new Property("system", "code", "Telecommunications form for contact point - what communications system is required to make use of the contact.", 0, 1, system);
        case "value":  return new Property("value", "string", "The actual contact point details, in a form that is meaningful to the designated communication system (i.e. phone number or email address).", 0, 1, value);
        case "use":  return new Property("use", "code", "Identifies the purpose for the contact point.", 0, 1, use);
        case "rank":  return new Property("rank", "positiveInt", "Specifies a preferred order in which to use a set of contacts. ContactPoints with lower rank values are more preferred than those with higher rank values.", 0, 1, rank);
        case "period":  return new Property("period", "Period", "Time period when the contact point was/is in use.", 0, 1, period);
        default: return super.getNamedProperty(_name, _checkValid);
        }

      }

      @Override
      public Base[] getNamedValue(String name, boolean checkValid) throws FHIRException {
        switch (name) {
        case "system": return this.system == null ? new Base[0] : new Base[] {this.system}; // Enumeration<ContactPointSystem>
        case "value": return this.value == null ? new Base[0] : new Base[] {this.value}; // StringType
        case "use": return this.use == null ? new Base[0] : new Base[] {this.use}; // Enumeration<ContactPointUse>
        case "rank": return this.rank == null ? new Base[0] : new Base[] {this.rank}; // PositiveIntType
        case "period": return this.period == null ? new Base[0] : new Base[] {this.period}; // Period
        default: return super.getNamedValue(name, checkValid);
        }

      }

      @Override
      public Base setProperty(String name, Base value) throws FHIRException {
        switch (name) {
        case "system":
          value = new ContactPointSystemEnumFactory(modelContext).fromType(TypeConvertor.castToCode(value));
          this.system = (Enumeration) value; // Enumeration<ContactPointSystem>
          if (this.system != null) {
            this.system.setModelContext(this.modelContext);
          }
          return value;
        case "value":
          this.value = TypeConvertor.castToString(value); // StringType
          if (this.value != null) {
            this.value.setModelContext(this.modelContext);
          }
          return value;
        case "use":
          value = new ContactPointUseEnumFactory(modelContext).fromType(TypeConvertor.castToCode(value));
          this.use = (Enumeration) value; // Enumeration<ContactPointUse>
          if (this.use != null) {
            this.use.setModelContext(this.modelContext);
          }
          return value;
        case "rank":
          this.rank = TypeConvertor.castToPositiveInt(value); // PositiveIntType
          if (this.rank != null) {
            this.rank.setModelContext(this.modelContext);
          }
          return value;
        case "period":
          this.period = TypeConvertor.castToPeriod(value); // Period
          if (this.period != null) {
            this.period.setModelContext(this.modelContext);
          }
          return value;
        default:
          return super.setProperty(name, value);
        }
      }

      @Override
      public void removeChild(String name, Base value) throws FHIRException {
        switch (name) {
        case "system":
          if (value == null || value == this.system) {
            this.system = null;
          }
          return;
        case "value":
          if (value == null || value == this.value) {
            this.value = null;
          }
          return;
        case "use":
          if (value == null || value == this.use) {
            this.use = null;
          }
          return;
        case "rank":
          if (value == null || value == this.rank) {
            this.rank = null;
          }
          return;
        case "period":
          if (value == null || value == this.period) {
            this.period = null;
          }
          return;
        default:
          super.removeChild(name, value);
        }
      }

      @Override
      public Base makeProperty(String name) throws FHIRException {
        switch (name) {
        case "system":  return getSystemElement();
        case "value":  return getValueElement();
        case "use":  return getUseElement();
        case "rank":  return getRankElement();
        case "period":  return getPeriod();
        default: return super.makeProperty(name);
        }

      }

      @Override
      public Base addChild(String name) throws FHIRException {
        if (name.equals("system")) {
          throw new FHIRException("Cannot call addChild on a singleton property ContactPoint.system");
        }
        else if (name.equals("value")) {
          throw new FHIRException("Cannot call addChild on a singleton property ContactPoint.value");
        }
        else if (name.equals("use")) {
          throw new FHIRException("Cannot call addChild on a singleton property ContactPoint.use");
        }
        else if (name.equals("rank")) {
          throw new FHIRException("Cannot call addChild on a singleton property ContactPoint.rank");
        }
        else if (name.equals("period")) {
          this.period = new Period(this.modelContext);
          return this.period;
        }
        else
          return super.addChild(name);
      }

  public String fhirType() {
    return "ContactPoint";

  }

      public ContactPoint copy(EnumSet<CopyObjectOptions> options) {
        ContactPoint dst = new ContactPoint(this.modelContext);
        copyValues(dst, options);
        return dst;
      }

      public void copyValues(ContactPoint dst, EnumSet<CopyObjectOptions> options) {
        super.copyValues(dst, options);
        dst.system = system == null ? null : system.copy(options);
        dst.value = value == null ? null : value.copy(options);
        dst.use = use == null ? null : use.copy(options);
        dst.rank = rank == null ? null : rank.copy(options);
        dst.period = period == null ? null : period.copy(options);
      }

      @Override
      public void setModelContext(IModelContext modelContext) {
        if (this.modelContext == modelContext) {
          return; // fast no-op; a subtree whose root has the context is assumed consistent - see Base.setModelContext
        }
        super.setModelContext(modelContext);
        if (this.system != null) {
          this.system.setModelContext(modelContext);
        }
        if (this.value != null) {
          this.value.setModelContext(modelContext);
        }
        if (this.use != null) {
          this.use.setModelContext(modelContext);
        }
        if (this.rank != null) {
          this.rank.setModelContext(modelContext);
        }
        if (this.period != null) {
          this.period.setModelContext(modelContext);
        }
      }

      @Override
      public boolean equalsDeep(Base other_) {
        if (!super.equalsDeep(other_))
          return false;
        if (!(other_ instanceof ContactPoint))
          return false;
        ContactPoint o = (ContactPoint) other_;
        return compareDeep(system, o.system, true) && compareDeep(value, o.value, true) && compareDeep(use, o.use, true)
           && compareDeep(rank, o.rank, true) && compareDeep(period, o.period, true);
      }

      @Override
      public boolean equalsShallow(Base other_) {
        if (!super.equalsShallow(other_))
          return false;
        if (!(other_ instanceof ContactPoint))
          return false;
        ContactPoint o = (ContactPoint) other_;
        return compareValues(system, o.system, true) && compareValues(value, o.value, true) && compareValues(use, o.use, true)
           && compareValues(rank, o.rank, true);
      }

      public boolean isEmpty() {
        return super.isEmpty() && ca.uhn.fhir.util.ElementUtil.isEmpty(system, value, use, rank
          , period);
      }


}

