// This file is generated code - do not edit it.
//
// Generated by the HL7 FHIR code generator (org.hl7.fhir.core: core code generator)
// from hl7.fhir.r6.core#6.0.0-ballot5 (version 6.0.0-ballot5)
// on Fri, Aug 14, 2026 19:22+1000.
//
// Any changes made here will be lost the next time the generator is run. To change
// this file, change the definitions it is generated from, or change the generator.
package org.hl7.fhir.model.core;

/*
  Copyright (c) 2011+, HL7, Inc.
  All rights reserved.
  
  Redistribution and use in source and binary forms, with or without modification,
  are permitted provided that the following conditions are met:
  
   * Redistributions of source code must retain the above copyright notice, this
     list of conditions and the following disclaimer
   * Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation
     and/or other materials provided with the distribution.
   * Neither the name of HL7 nor the names of its contributors may be used to 
     endorse or promote products derived from this software without specific 
     prior written permission.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.
  */

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.hl7.fhir.utilities.Utilities;
import org.hl7.fhir.model.core.Enumerations.*;
import org.hl7.fhir.instance.model.api.IBaseDatatypeElement;
import org.hl7.fhir.exceptions.FHIRException;
import org.hl7.fhir.instance.model.api.ICompositeType;
import ca.uhn.fhir.model.api.annotation.Child;
import ca.uhn.fhir.model.api.annotation.ChildOrder;
import ca.uhn.fhir.model.api.annotation.DatatypeDef;
import ca.uhn.fhir.model.api.annotation.Description;
import ca.uhn.fhir.model.api.annotation.Block;

/**
 * DosageCondition Type: DosageCondition expresses a time or time period as relative to the time of an event defined in data types other than dateTime.
 */
@DatatypeDef(name="DosageCondition")
@javax.annotation.processing.Generated(value = "org.hl7.fhir.core.generator.engine.JavaCoreGenerator", comments = "generated from hl7.fhir.r6.core#6.0.0-ballot5")
public class DosageCondition extends BackboneType implements ICompositeType {

    public enum ComparisonOperationVS {
        /**
         * the value for the parameter in the resource is equal to the provided value.
         */
        EQ, 
        /**
         * the value for the parameter in the resource is not equal to the provided value.
         */
        NE, 
        /**
         * The value for the parameter in the resource is in the list of codes in the value (comma-separated, and subject to code system logic; the code may be a value set).
         */
        IN, 
        /**
         * The value for the parameter in the resource is not in the list of codes in the value (comma-separated, and subject to code system logic; the code may be a value set).
         */
        NIN, 
        /**
         * the value for the parameter in the resource is greater than the provided value.
         */
        GT, 
        /**
         * the value for the parameter in the resource is less than the provided value.
         */
        LT, 
        /**
         * the value for the parameter in the resource is greater or equal to the provided value.
         */
        GE, 
        /**
         * the value for the parameter in the resource is less or equal to the provided value.
         */
        LE, 
        /**
         * the value for the parameter in the resource starts after the provided value.
         */
        SA, 
        /**
         * the value for the parameter in the resource ends before the provided value.
         */
        EB, 
        /**
         * the value for the parameter in the resource is approximately the same to the provided value.
         */
        AP, 
        /**
         * added to help the parsers with the generic types
         */
        NULL;
        public static ComparisonOperationVS fromCode(String codeString) throws FHIRException {
            if (codeString == null || "".equals(codeString))
                return null;
        if ("eq".equals(codeString))
          return EQ;
        if ("ne".equals(codeString))
          return NE;
        if ("in".equals(codeString))
          return IN;
        if ("nin".equals(codeString))
          return NIN;
        if ("gt".equals(codeString))
          return GT;
        if ("lt".equals(codeString))
          return LT;
        if ("ge".equals(codeString))
          return GE;
        if ("le".equals(codeString))
          return LE;
        if ("sa".equals(codeString))
          return SA;
        if ("eb".equals(codeString))
          return EB;
        if ("ap".equals(codeString))
          return AP;
        if (Configuration.isAcceptInvalidEnums())
          return null;
        else
          throw new FHIRException("Unknown ComparisonOperationVS code '"+codeString+"'");
        }
        public String toCode() {
          switch (this) {
            case EQ: return "eq";
            case NE: return "ne";
            case IN: return "in";
            case NIN: return "nin";
            case GT: return "gt";
            case LT: return "lt";
            case GE: return "ge";
            case LE: return "le";
            case SA: return "sa";
            case EB: return "eb";
            case AP: return "ap";
            case NULL: return null;
            default: return "?";
          }
        }
        public String getSystem() {
          switch (this) {
            case EQ: return "http://hl7.org/fhir/CodeSystem/comparison-operation";
            case NE: return "http://hl7.org/fhir/CodeSystem/comparison-operation";
            case IN: return "http://hl7.org/fhir/CodeSystem/comparison-operation";
            case NIN: return "http://hl7.org/fhir/CodeSystem/comparison-operation";
            case GT: return "http://hl7.org/fhir/CodeSystem/comparison-operation";
            case LT: return "http://hl7.org/fhir/CodeSystem/comparison-operation";
            case GE: return "http://hl7.org/fhir/CodeSystem/comparison-operation";
            case LE: return "http://hl7.org/fhir/CodeSystem/comparison-operation";
            case SA: return "http://hl7.org/fhir/CodeSystem/comparison-operation";
            case EB: return "http://hl7.org/fhir/CodeSystem/comparison-operation";
            case AP: return "http://hl7.org/fhir/CodeSystem/comparison-operation";
            case NULL: return null;
            default: return "?";
          }
        }
        public String getDefinition() {
          switch (this) {
            case EQ: return "the value for the parameter in the resource is equal to the provided value.";
            case NE: return "the value for the parameter in the resource is not equal to the provided value.";
            case IN: return "The value for the parameter in the resource is in the list of codes in the value (comma-separated, and subject to code system logic; the code may be a value set).";
            case NIN: return "The value for the parameter in the resource is not in the list of codes in the value (comma-separated, and subject to code system logic; the code may be a value set).";
            case GT: return "the value for the parameter in the resource is greater than the provided value.";
            case LT: return "the value for the parameter in the resource is less than the provided value.";
            case GE: return "the value for the parameter in the resource is greater or equal to the provided value.";
            case LE: return "the value for the parameter in the resource is less or equal to the provided value.";
            case SA: return "the value for the parameter in the resource starts after the provided value.";
            case EB: return "the value for the parameter in the resource ends before the provided value.";
            case AP: return "the value for the parameter in the resource is approximately the same to the provided value.";
            case NULL: return null;
            default: return "?";
          }
        }
        public String getDisplay() {
          switch (this) {
            case EQ: return "Equals";
            case NE: return "Not Equals";
            case IN: return "In";
            case NIN: return "Not In";
            case GT: return "Greater Than";
            case LT: return "Less Than";
            case GE: return "Greater or Equals";
            case LE: return "Less of Equal";
            case SA: return "Starts After";
            case EB: return "Ends Before";
            case AP: return "Approximately";
            case NULL: return null;
            default: return "?";
          }
        }
    }

  public static class ComparisonOperationVSEnumFactory implements EnumFactory<ComparisonOperationVS> {
    public ComparisonOperationVS fromCode(String codeString) throws IllegalArgumentException {
      if (codeString == null || "".equals(codeString))
            if (codeString == null || "".equals(codeString))
                return null;
        if ("eq".equals(codeString))
          return ComparisonOperationVS.EQ;
        if ("ne".equals(codeString))
          return ComparisonOperationVS.NE;
        if ("in".equals(codeString))
          return ComparisonOperationVS.IN;
        if ("nin".equals(codeString))
          return ComparisonOperationVS.NIN;
        if ("gt".equals(codeString))
          return ComparisonOperationVS.GT;
        if ("lt".equals(codeString))
          return ComparisonOperationVS.LT;
        if ("ge".equals(codeString))
          return ComparisonOperationVS.GE;
        if ("le".equals(codeString))
          return ComparisonOperationVS.LE;
        if ("sa".equals(codeString))
          return ComparisonOperationVS.SA;
        if ("eb".equals(codeString))
          return ComparisonOperationVS.EB;
        if ("ap".equals(codeString))
          return ComparisonOperationVS.AP;
        throw new IllegalArgumentException("Unknown ComparisonOperationVS code '"+codeString+"'");
        }
        public Enumeration<ComparisonOperationVS> fromType(PrimitiveType<?> code) throws FHIRException {
          if (code == null)
            return null;
          if (code.isEmpty())
            return new Enumeration<ComparisonOperationVS>(this, ComparisonOperationVS.NULL, code);
          String codeString = ((PrimitiveType) code).asStringValue();
          if (codeString == null || "".equals(codeString))
            return new Enumeration<ComparisonOperationVS>(this, ComparisonOperationVS.NULL, code);
        if ("eq".equals(codeString))
          return new Enumeration<ComparisonOperationVS>(this, ComparisonOperationVS.EQ, code);
        if ("ne".equals(codeString))
          return new Enumeration<ComparisonOperationVS>(this, ComparisonOperationVS.NE, code);
        if ("in".equals(codeString))
          return new Enumeration<ComparisonOperationVS>(this, ComparisonOperationVS.IN, code);
        if ("nin".equals(codeString))
          return new Enumeration<ComparisonOperationVS>(this, ComparisonOperationVS.NIN, code);
        if ("gt".equals(codeString))
          return new Enumeration<ComparisonOperationVS>(this, ComparisonOperationVS.GT, code);
        if ("lt".equals(codeString))
          return new Enumeration<ComparisonOperationVS>(this, ComparisonOperationVS.LT, code);
        if ("ge".equals(codeString))
          return new Enumeration<ComparisonOperationVS>(this, ComparisonOperationVS.GE, code);
        if ("le".equals(codeString))
          return new Enumeration<ComparisonOperationVS>(this, ComparisonOperationVS.LE, code);
        if ("sa".equals(codeString))
          return new Enumeration<ComparisonOperationVS>(this, ComparisonOperationVS.SA, code);
        if ("eb".equals(codeString))
          return new Enumeration<ComparisonOperationVS>(this, ComparisonOperationVS.EB, code);
        if ("ap".equals(codeString))
          return new Enumeration<ComparisonOperationVS>(this, ComparisonOperationVS.AP, code);
        throw new FHIRException("Unknown ComparisonOperationVS code '"+codeString+"'");
        }
    public String toCode(ComparisonOperationVS code) {
      if (code == ComparisonOperationVS.EQ)
        return "eq";
      if (code == ComparisonOperationVS.NE)
        return "ne";
      if (code == ComparisonOperationVS.IN)
        return "in";
      if (code == ComparisonOperationVS.NIN)
        return "nin";
      if (code == ComparisonOperationVS.GT)
        return "gt";
      if (code == ComparisonOperationVS.LT)
        return "lt";
      if (code == ComparisonOperationVS.GE)
        return "ge";
      if (code == ComparisonOperationVS.LE)
        return "le";
      if (code == ComparisonOperationVS.SA)
        return "sa";
      if (code == ComparisonOperationVS.EB)
        return "eb";
      if (code == ComparisonOperationVS.AP)
        return "ap";
      return "?";
      }
    public String toSystem(ComparisonOperationVS code) {
      return code.getSystem();
      }
    }

    /**
     * The specific event occurrence or resource context used as a base point (reference point) in time.  This establishes the context in which the 'path' is evaluated.
     */
    @Child(name = "code", type = {CodeableConcept.class}, order=0, min=1, max=1, modifier=false, summary=true)
    @Description(shortDefinition="The specific event occurrence or resource context used as a base point (reference point) in time")
    @ca.uhn.fhir.model.api.annotation.Binding(valueSet="http://hl7.org/fhir/ValueSet/dosage-condition-code")
    protected CodeableConcept code;

    /**
     * Additional details about the event - depends on the code.
     */
    @Child(name = "details", type = {CodeableConcept.class}, order=1, min=0, max=1, modifier=false, summary=true)
    @Description(shortDefinition="Additional details about the event - depends on the code")
    @ca.uhn.fhir.model.api.annotation.Binding(valueSet="http://hl7.org/fhir/ValueSet/dosage-condition-details")
    protected CodeableConcept details;

    /**
     * How the value is tested.
     */
    @Child(name = "operation", type = {CodeType.class}, order=2, min=0, max=1, modifier=false, summary=true)
    @Description(shortDefinition="eq | ne | in | nin | gt | lt | ge | le | sa | eb | ap")
    @ca.uhn.fhir.model.api.annotation.Binding(valueSet="http://hl7.org/fhir/ValueSet/comparison-operation")
    protected Enumeration<ComparisonOperationVS> operation;

    /**
     * The value for this critera.
     */
    @Child(name = "value", type = {Base64BinaryType.class, BooleanType.class, CanonicalType.class, CodeType.class, DateType.class, DateTimeType.class, DecimalType.class, IdType.class, InstantType.class, IntegerType.class, Integer64Type.class, MarkdownType.class, OidType.class, PositiveIntType.class, StringType.class, TimeType.class, UnsignedIntType.class, UriType.class, UrlType.class, UuidType.class, Address.class, Age.class, Annotation.class, Attachment.class, CodeableConcept.class, CodeableReference.class, Coding.class, ContactPoint.class, Count.class, Distance.class, Duration.class, HumanName.class, Identifier.class, Money.class, Period.class, Quantity.class, Range.class, Ratio.class, RatioRange.class, Reference.class, SampledData.class, Signature.class, Timing.class, ContactDetail.class, DataRequirement.class, Expression.class, ParameterDefinition.class, RelatedArtifact.class, TriggerDefinition.class, UsageContext.class, Availability.class, ExtendedContactDetail.class, VirtualServiceDetail.class, Dosage.class, Meta.class}, order=3, min=0, max=1, modifier=false, summary=true)
    @Description(shortDefinition="The value for this critera")
    protected DataType value;

    /**
     * Free-text (human-readable) description.
     */
    @Child(name = "text", type = {StringType.class}, order=4, min=0, max=1, modifier=false, summary=true)
    @Description(shortDefinition="Free-text description")
    protected StringType text;

    private static final long serialVersionUID = -536779469L;

  /**
   * Constructor
   */
    public DosageCondition() {
      super();
    }

  /**
   * Constructor
   */
    public DosageCondition(CodeableConcept code) {
      super();
      this.setCode(code);
    }

    /**
     * @return {@link #code} (The specific event occurrence or resource context used as a base point (reference point) in time.  This establishes the context in which the 'path' is evaluated.)
     */
    public CodeableConcept getCode() { 
      if (this.code == null)
        if (Configuration.errorOnAutoCreate())
          throw new Error("Attempt to auto-create DosageCondition.code");
        else if (Configuration.doAutoCreate())
          this.code = new CodeableConcept(); // cc
      return this.code;
    }

    public boolean hasCode() { 
      return this.code != null && !this.code.isEmpty();
    }

    /**
     * @param value {@link #code} (The specific event occurrence or resource context used as a base point (reference point) in time.  This establishes the context in which the 'path' is evaluated.)
     */
    public DosageCondition setCode(CodeableConcept value) { 
      this.code = value;
      return this;
    }

    /**
     * @return {@link #details} (Additional details about the event - depends on the code.)
     */
    public CodeableConcept getDetails() { 
      if (this.details == null)
        if (Configuration.errorOnAutoCreate())
          throw new Error("Attempt to auto-create DosageCondition.details");
        else if (Configuration.doAutoCreate())
          this.details = new CodeableConcept(); // cc
      return this.details;
    }

    public boolean hasDetails() { 
      return this.details != null && !this.details.isEmpty();
    }

    /**
     * @param value {@link #details} (Additional details about the event - depends on the code.)
     */
    public DosageCondition setDetails(CodeableConcept value) { 
      this.details = value;
      return this;
    }

    /**
     * @return {@link #operation} (How the value is tested.). This is the underlying object with id, value and extensions. The accessor "getOperation" gives direct access to the value
     */
    public Enumeration<ComparisonOperationVS> getOperationElement() { 
      if (this.operation == null)
        if (Configuration.errorOnAutoCreate())
          throw new Error("Attempt to auto-create DosageCondition.operation");
        else if (Configuration.doAutoCreate())
          this.operation = new Enumeration<ComparisonOperationVS>(new ComparisonOperationVSEnumFactory()); // bb
      return this.operation;
    }

    public boolean hasOperationElement() { 
      return this.operation != null && !this.operation.isEmpty();
    }

    public boolean hasOperation() { 
      return this.operation != null && !this.operation.isEmpty();
    }

    /**
     * @param value {@link #operation} (How the value is tested.). This is the underlying object with id, value and extensions. The accessor "getOperation" gives direct access to the value
     */
    public DosageCondition setOperationElement(Enumeration<ComparisonOperationVS> value) { 
      this.operation = value;
      return this;
    }

    /**
     * @return How the value is tested.
     */
    public ComparisonOperationVS getOperation() { 
      return this.operation == null ? null : this.operation.getValue();
    }

    /**
     * @param value How the value is tested.
     */
    public DosageCondition setOperation(ComparisonOperationVS value) { 
      if (value == null)
        this.operation = null;
      else {
        if (this.operation == null)
          this.operation = new Enumeration<ComparisonOperationVS>(new ComparisonOperationVSEnumFactory());
        this.operation.setValue(value);
      }
      return this;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public DataType getValue() { 
      return this.value;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Base64BinaryType getValueBase64BinaryType() throws FHIRException { 
      if (this.value == null)
        this.value = new Base64BinaryType();
      if (!(this.value instanceof Base64BinaryType))
        throw new FHIRException("Type mismatch: the type Base64BinaryType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Base64BinaryType) this.value;
    }

    public boolean hasValueBase64BinaryType() { 
      return this.value != null && this.value instanceof Base64BinaryType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public BooleanType getValueBooleanType() throws FHIRException { 
      if (this.value == null)
        this.value = new BooleanType();
      if (!(this.value instanceof BooleanType))
        throw new FHIRException("Type mismatch: the type BooleanType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (BooleanType) this.value;
    }

    public boolean hasValueBooleanType() { 
      return this.value != null && this.value instanceof BooleanType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public CanonicalType getValueCanonicalType() throws FHIRException { 
      if (this.value == null)
        this.value = new CanonicalType();
      if (!(this.value instanceof CanonicalType))
        throw new FHIRException("Type mismatch: the type CanonicalType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (CanonicalType) this.value;
    }

    public boolean hasValueCanonicalType() { 
      return this.value != null && this.value instanceof CanonicalType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public CodeType getValueCodeType() throws FHIRException { 
      if (this.value == null)
        this.value = new CodeType();
      if (!(this.value instanceof CodeType))
        throw new FHIRException("Type mismatch: the type CodeType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (CodeType) this.value;
    }

    public boolean hasValueCodeType() { 
      return this.value != null && this.value instanceof CodeType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public DateType getValueDateType() throws FHIRException { 
      if (this.value == null)
        this.value = new DateType();
      if (!(this.value instanceof DateType))
        throw new FHIRException("Type mismatch: the type DateType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (DateType) this.value;
    }

    public boolean hasValueDateType() { 
      return this.value != null && this.value instanceof DateType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public DateTimeType getValueDateTimeType() throws FHIRException { 
      if (this.value == null)
        this.value = new DateTimeType();
      if (!(this.value instanceof DateTimeType))
        throw new FHIRException("Type mismatch: the type DateTimeType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (DateTimeType) this.value;
    }

    public boolean hasValueDateTimeType() { 
      return this.value != null && this.value instanceof DateTimeType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public DecimalType getValueDecimalType() throws FHIRException { 
      if (this.value == null)
        this.value = new DecimalType();
      if (!(this.value instanceof DecimalType))
        throw new FHIRException("Type mismatch: the type DecimalType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (DecimalType) this.value;
    }

    public boolean hasValueDecimalType() { 
      return this.value != null && this.value instanceof DecimalType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public IdType getValueIdType() throws FHIRException { 
      if (this.value == null)
        this.value = new IdType();
      if (!(this.value instanceof IdType))
        throw new FHIRException("Type mismatch: the type IdType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (IdType) this.value;
    }

    public boolean hasValueIdType() { 
      return this.value != null && this.value instanceof IdType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public InstantType getValueInstantType() throws FHIRException { 
      if (this.value == null)
        this.value = new InstantType();
      if (!(this.value instanceof InstantType))
        throw new FHIRException("Type mismatch: the type InstantType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (InstantType) this.value;
    }

    public boolean hasValueInstantType() { 
      return this.value != null && this.value instanceof InstantType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public IntegerType getValueIntegerType() throws FHIRException { 
      if (this.value == null)
        this.value = new IntegerType();
      if (!(this.value instanceof IntegerType))
        throw new FHIRException("Type mismatch: the type IntegerType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (IntegerType) this.value;
    }

    public boolean hasValueIntegerType() { 
      return this.value != null && this.value instanceof IntegerType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Integer64Type getValueInteger64Type() throws FHIRException { 
      if (this.value == null)
        this.value = new Integer64Type();
      if (!(this.value instanceof Integer64Type))
        throw new FHIRException("Type mismatch: the type Integer64Type was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Integer64Type) this.value;
    }

    public boolean hasValueInteger64Type() { 
      return this.value != null && this.value instanceof Integer64Type;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public MarkdownType getValueMarkdownType() throws FHIRException { 
      if (this.value == null)
        this.value = new MarkdownType();
      if (!(this.value instanceof MarkdownType))
        throw new FHIRException("Type mismatch: the type MarkdownType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (MarkdownType) this.value;
    }

    public boolean hasValueMarkdownType() { 
      return this.value != null && this.value instanceof MarkdownType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public OidType getValueOidType() throws FHIRException { 
      if (this.value == null)
        this.value = new OidType();
      if (!(this.value instanceof OidType))
        throw new FHIRException("Type mismatch: the type OidType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (OidType) this.value;
    }

    public boolean hasValueOidType() { 
      return this.value != null && this.value instanceof OidType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public PositiveIntType getValuePositiveIntType() throws FHIRException { 
      if (this.value == null)
        this.value = new PositiveIntType();
      if (!(this.value instanceof PositiveIntType))
        throw new FHIRException("Type mismatch: the type PositiveIntType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (PositiveIntType) this.value;
    }

    public boolean hasValuePositiveIntType() { 
      return this.value != null && this.value instanceof PositiveIntType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public StringType getValueStringType() throws FHIRException { 
      if (this.value == null)
        this.value = new StringType();
      if (!(this.value instanceof StringType))
        throw new FHIRException("Type mismatch: the type StringType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (StringType) this.value;
    }

    public boolean hasValueStringType() { 
      return this.value != null && this.value instanceof StringType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public TimeType getValueTimeType() throws FHIRException { 
      if (this.value == null)
        this.value = new TimeType();
      if (!(this.value instanceof TimeType))
        throw new FHIRException("Type mismatch: the type TimeType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (TimeType) this.value;
    }

    public boolean hasValueTimeType() { 
      return this.value != null && this.value instanceof TimeType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public UnsignedIntType getValueUnsignedIntType() throws FHIRException { 
      if (this.value == null)
        this.value = new UnsignedIntType();
      if (!(this.value instanceof UnsignedIntType))
        throw new FHIRException("Type mismatch: the type UnsignedIntType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (UnsignedIntType) this.value;
    }

    public boolean hasValueUnsignedIntType() { 
      return this.value != null && this.value instanceof UnsignedIntType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public UriType getValueUriType() throws FHIRException { 
      if (this.value == null)
        this.value = new UriType();
      if (!(this.value instanceof UriType))
        throw new FHIRException("Type mismatch: the type UriType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (UriType) this.value;
    }

    public boolean hasValueUriType() { 
      return this.value != null && this.value instanceof UriType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public UrlType getValueUrlType() throws FHIRException { 
      if (this.value == null)
        this.value = new UrlType();
      if (!(this.value instanceof UrlType))
        throw new FHIRException("Type mismatch: the type UrlType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (UrlType) this.value;
    }

    public boolean hasValueUrlType() { 
      return this.value != null && this.value instanceof UrlType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public UuidType getValueUuidType() throws FHIRException { 
      if (this.value == null)
        this.value = new UuidType();
      if (!(this.value instanceof UuidType))
        throw new FHIRException("Type mismatch: the type UuidType was expected, but "+this.value.getClass().getName()+" was encountered");
      return (UuidType) this.value;
    }

    public boolean hasValueUuidType() { 
      return this.value != null && this.value instanceof UuidType;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Address getValueAddress() throws FHIRException { 
      if (this.value == null)
        this.value = new Address();
      if (!(this.value instanceof Address))
        throw new FHIRException("Type mismatch: the type Address was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Address) this.value;
    }

    public boolean hasValueAddress() { 
      return this.value != null && this.value instanceof Address;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Age getValueAge() throws FHIRException { 
      if (this.value == null)
        this.value = new Age();
      if (!(this.value instanceof Age))
        throw new FHIRException("Type mismatch: the type Age was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Age) this.value;
    }

    public boolean hasValueAge() { 
      return this.value != null && this.value instanceof Age;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Annotation getValueAnnotation() throws FHIRException { 
      if (this.value == null)
        this.value = new Annotation();
      if (!(this.value instanceof Annotation))
        throw new FHIRException("Type mismatch: the type Annotation was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Annotation) this.value;
    }

    public boolean hasValueAnnotation() { 
      return this.value != null && this.value instanceof Annotation;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Attachment getValueAttachment() throws FHIRException { 
      if (this.value == null)
        this.value = new Attachment();
      if (!(this.value instanceof Attachment))
        throw new FHIRException("Type mismatch: the type Attachment was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Attachment) this.value;
    }

    public boolean hasValueAttachment() { 
      return this.value != null && this.value instanceof Attachment;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public CodeableConcept getValueCodeableConcept() throws FHIRException { 
      if (this.value == null)
        this.value = new CodeableConcept();
      if (!(this.value instanceof CodeableConcept))
        throw new FHIRException("Type mismatch: the type CodeableConcept was expected, but "+this.value.getClass().getName()+" was encountered");
      return (CodeableConcept) this.value;
    }

    public boolean hasValueCodeableConcept() { 
      return this.value != null && this.value instanceof CodeableConcept;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public CodeableReference getValueCodeableReference() throws FHIRException { 
      if (this.value == null)
        this.value = new CodeableReference();
      if (!(this.value instanceof CodeableReference))
        throw new FHIRException("Type mismatch: the type CodeableReference was expected, but "+this.value.getClass().getName()+" was encountered");
      return (CodeableReference) this.value;
    }

    public boolean hasValueCodeableReference() { 
      return this.value != null && this.value instanceof CodeableReference;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Coding getValueCoding() throws FHIRException { 
      if (this.value == null)
        this.value = new Coding();
      if (!(this.value instanceof Coding))
        throw new FHIRException("Type mismatch: the type Coding was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Coding) this.value;
    }

    public boolean hasValueCoding() { 
      return this.value != null && this.value instanceof Coding;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public ContactPoint getValueContactPoint() throws FHIRException { 
      if (this.value == null)
        this.value = new ContactPoint();
      if (!(this.value instanceof ContactPoint))
        throw new FHIRException("Type mismatch: the type ContactPoint was expected, but "+this.value.getClass().getName()+" was encountered");
      return (ContactPoint) this.value;
    }

    public boolean hasValueContactPoint() { 
      return this.value != null && this.value instanceof ContactPoint;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Count getValueCount() throws FHIRException { 
      if (this.value == null)
        this.value = new Count();
      if (!(this.value instanceof Count))
        throw new FHIRException("Type mismatch: the type Count was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Count) this.value;
    }

    public boolean hasValueCount() { 
      return this.value != null && this.value instanceof Count;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Distance getValueDistance() throws FHIRException { 
      if (this.value == null)
        this.value = new Distance();
      if (!(this.value instanceof Distance))
        throw new FHIRException("Type mismatch: the type Distance was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Distance) this.value;
    }

    public boolean hasValueDistance() { 
      return this.value != null && this.value instanceof Distance;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Duration getValueDuration() throws FHIRException { 
      if (this.value == null)
        this.value = new Duration();
      if (!(this.value instanceof Duration))
        throw new FHIRException("Type mismatch: the type Duration was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Duration) this.value;
    }

    public boolean hasValueDuration() { 
      return this.value != null && this.value instanceof Duration;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public HumanName getValueHumanName() throws FHIRException { 
      if (this.value == null)
        this.value = new HumanName();
      if (!(this.value instanceof HumanName))
        throw new FHIRException("Type mismatch: the type HumanName was expected, but "+this.value.getClass().getName()+" was encountered");
      return (HumanName) this.value;
    }

    public boolean hasValueHumanName() { 
      return this.value != null && this.value instanceof HumanName;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Identifier getValueIdentifier() throws FHIRException { 
      if (this.value == null)
        this.value = new Identifier();
      if (!(this.value instanceof Identifier))
        throw new FHIRException("Type mismatch: the type Identifier was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Identifier) this.value;
    }

    public boolean hasValueIdentifier() { 
      return this.value != null && this.value instanceof Identifier;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Money getValueMoney() throws FHIRException { 
      if (this.value == null)
        this.value = new Money();
      if (!(this.value instanceof Money))
        throw new FHIRException("Type mismatch: the type Money was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Money) this.value;
    }

    public boolean hasValueMoney() { 
      return this.value != null && this.value instanceof Money;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Period getValuePeriod() throws FHIRException { 
      if (this.value == null)
        this.value = new Period();
      if (!(this.value instanceof Period))
        throw new FHIRException("Type mismatch: the type Period was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Period) this.value;
    }

    public boolean hasValuePeriod() { 
      return this.value != null && this.value instanceof Period;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Quantity getValueQuantity() throws FHIRException { 
      if (this.value == null)
        this.value = new Quantity();
      if (!(this.value instanceof Quantity))
        throw new FHIRException("Type mismatch: the type Quantity was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Quantity) this.value;
    }

    public boolean hasValueQuantity() { 
      return this.value != null && this.value instanceof Quantity;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Range getValueRange() throws FHIRException { 
      if (this.value == null)
        this.value = new Range();
      if (!(this.value instanceof Range))
        throw new FHIRException("Type mismatch: the type Range was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Range) this.value;
    }

    public boolean hasValueRange() { 
      return this.value != null && this.value instanceof Range;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Ratio getValueRatio() throws FHIRException { 
      if (this.value == null)
        this.value = new Ratio();
      if (!(this.value instanceof Ratio))
        throw new FHIRException("Type mismatch: the type Ratio was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Ratio) this.value;
    }

    public boolean hasValueRatio() { 
      return this.value != null && this.value instanceof Ratio;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public RatioRange getValueRatioRange() throws FHIRException { 
      if (this.value == null)
        this.value = new RatioRange();
      if (!(this.value instanceof RatioRange))
        throw new FHIRException("Type mismatch: the type RatioRange was expected, but "+this.value.getClass().getName()+" was encountered");
      return (RatioRange) this.value;
    }

    public boolean hasValueRatioRange() { 
      return this.value != null && this.value instanceof RatioRange;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Reference getValueReference() throws FHIRException { 
      if (this.value == null)
        this.value = new Reference();
      if (!(this.value instanceof Reference))
        throw new FHIRException("Type mismatch: the type Reference was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Reference) this.value;
    }

    public boolean hasValueReference() { 
      return this.value != null && this.value instanceof Reference;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public SampledData getValueSampledData() throws FHIRException { 
      if (this.value == null)
        this.value = new SampledData();
      if (!(this.value instanceof SampledData))
        throw new FHIRException("Type mismatch: the type SampledData was expected, but "+this.value.getClass().getName()+" was encountered");
      return (SampledData) this.value;
    }

    public boolean hasValueSampledData() { 
      return this.value != null && this.value instanceof SampledData;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Signature getValueSignature() throws FHIRException { 
      if (this.value == null)
        this.value = new Signature();
      if (!(this.value instanceof Signature))
        throw new FHIRException("Type mismatch: the type Signature was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Signature) this.value;
    }

    public boolean hasValueSignature() { 
      return this.value != null && this.value instanceof Signature;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Timing getValueTiming() throws FHIRException { 
      if (this.value == null)
        this.value = new Timing();
      if (!(this.value instanceof Timing))
        throw new FHIRException("Type mismatch: the type Timing was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Timing) this.value;
    }

    public boolean hasValueTiming() { 
      return this.value != null && this.value instanceof Timing;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public ContactDetail getValueContactDetail() throws FHIRException { 
      if (this.value == null)
        this.value = new ContactDetail();
      if (!(this.value instanceof ContactDetail))
        throw new FHIRException("Type mismatch: the type ContactDetail was expected, but "+this.value.getClass().getName()+" was encountered");
      return (ContactDetail) this.value;
    }

    public boolean hasValueContactDetail() { 
      return this.value != null && this.value instanceof ContactDetail;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public DataRequirement getValueDataRequirement() throws FHIRException { 
      if (this.value == null)
        this.value = new DataRequirement();
      if (!(this.value instanceof DataRequirement))
        throw new FHIRException("Type mismatch: the type DataRequirement was expected, but "+this.value.getClass().getName()+" was encountered");
      return (DataRequirement) this.value;
    }

    public boolean hasValueDataRequirement() { 
      return this.value != null && this.value instanceof DataRequirement;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Expression getValueExpression() throws FHIRException { 
      if (this.value == null)
        this.value = new Expression();
      if (!(this.value instanceof Expression))
        throw new FHIRException("Type mismatch: the type Expression was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Expression) this.value;
    }

    public boolean hasValueExpression() { 
      return this.value != null && this.value instanceof Expression;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public ParameterDefinition getValueParameterDefinition() throws FHIRException { 
      if (this.value == null)
        this.value = new ParameterDefinition();
      if (!(this.value instanceof ParameterDefinition))
        throw new FHIRException("Type mismatch: the type ParameterDefinition was expected, but "+this.value.getClass().getName()+" was encountered");
      return (ParameterDefinition) this.value;
    }

    public boolean hasValueParameterDefinition() { 
      return this.value != null && this.value instanceof ParameterDefinition;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public RelatedArtifact getValueRelatedArtifact() throws FHIRException { 
      if (this.value == null)
        this.value = new RelatedArtifact();
      if (!(this.value instanceof RelatedArtifact))
        throw new FHIRException("Type mismatch: the type RelatedArtifact was expected, but "+this.value.getClass().getName()+" was encountered");
      return (RelatedArtifact) this.value;
    }

    public boolean hasValueRelatedArtifact() { 
      return this.value != null && this.value instanceof RelatedArtifact;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public TriggerDefinition getValueTriggerDefinition() throws FHIRException { 
      if (this.value == null)
        this.value = new TriggerDefinition();
      if (!(this.value instanceof TriggerDefinition))
        throw new FHIRException("Type mismatch: the type TriggerDefinition was expected, but "+this.value.getClass().getName()+" was encountered");
      return (TriggerDefinition) this.value;
    }

    public boolean hasValueTriggerDefinition() { 
      return this.value != null && this.value instanceof TriggerDefinition;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public UsageContext getValueUsageContext() throws FHIRException { 
      if (this.value == null)
        this.value = new UsageContext();
      if (!(this.value instanceof UsageContext))
        throw new FHIRException("Type mismatch: the type UsageContext was expected, but "+this.value.getClass().getName()+" was encountered");
      return (UsageContext) this.value;
    }

    public boolean hasValueUsageContext() { 
      return this.value != null && this.value instanceof UsageContext;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Availability getValueAvailability() throws FHIRException { 
      if (this.value == null)
        this.value = new Availability();
      if (!(this.value instanceof Availability))
        throw new FHIRException("Type mismatch: the type Availability was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Availability) this.value;
    }

    public boolean hasValueAvailability() { 
      return this.value != null && this.value instanceof Availability;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public ExtendedContactDetail getValueExtendedContactDetail() throws FHIRException { 
      if (this.value == null)
        this.value = new ExtendedContactDetail();
      if (!(this.value instanceof ExtendedContactDetail))
        throw new FHIRException("Type mismatch: the type ExtendedContactDetail was expected, but "+this.value.getClass().getName()+" was encountered");
      return (ExtendedContactDetail) this.value;
    }

    public boolean hasValueExtendedContactDetail() { 
      return this.value != null && this.value instanceof ExtendedContactDetail;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public VirtualServiceDetail getValueVirtualServiceDetail() throws FHIRException { 
      if (this.value == null)
        this.value = new VirtualServiceDetail();
      if (!(this.value instanceof VirtualServiceDetail))
        throw new FHIRException("Type mismatch: the type VirtualServiceDetail was expected, but "+this.value.getClass().getName()+" was encountered");
      return (VirtualServiceDetail) this.value;
    }

    public boolean hasValueVirtualServiceDetail() { 
      return this.value != null && this.value instanceof VirtualServiceDetail;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Dosage getValueDosage() throws FHIRException { 
      if (this.value == null)
        this.value = new Dosage();
      if (!(this.value instanceof Dosage))
        throw new FHIRException("Type mismatch: the type Dosage was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Dosage) this.value;
    }

    public boolean hasValueDosage() { 
      return this.value != null && this.value instanceof Dosage;
    }

    /**
     * @return {@link #value} (The value for this critera.)
     */
    public Meta getValueMeta() throws FHIRException { 
      if (this.value == null)
        this.value = new Meta();
      if (!(this.value instanceof Meta))
        throw new FHIRException("Type mismatch: the type Meta was expected, but "+this.value.getClass().getName()+" was encountered");
      return (Meta) this.value;
    }

    public boolean hasValueMeta() { 
      return this.value != null && this.value instanceof Meta;
    }

    public boolean hasValue() { 
      return this.value != null && !this.value.isEmpty();
    }

    /**
     * @param value {@link #value} (The value for this critera.)
     */
    public DosageCondition setValue(DataType value) { 
      if (value != null && !(value instanceof Base64BinaryType || value instanceof BooleanType || value instanceof CanonicalType || value instanceof CodeType || value instanceof DateType || value instanceof DateTimeType || value instanceof DecimalType || value instanceof IdType || value instanceof InstantType || value instanceof IntegerType || value instanceof Integer64Type || value instanceof MarkdownType || value instanceof OidType || value instanceof PositiveIntType || value instanceof StringType || value instanceof TimeType || value instanceof UnsignedIntType || value instanceof UriType || value instanceof UrlType || value instanceof UuidType || value instanceof Address || value instanceof Age || value instanceof Annotation || value instanceof Attachment || value instanceof CodeableConcept || value instanceof CodeableReference || value instanceof Coding || value instanceof ContactPoint || value instanceof Count || value instanceof Distance || value instanceof Duration || value instanceof HumanName || value instanceof Identifier || value instanceof Money || value instanceof Period || value instanceof Quantity || value instanceof Range || value instanceof Ratio || value instanceof RatioRange || value instanceof Reference || value instanceof SampledData || value instanceof Signature || value instanceof Timing || value instanceof ContactDetail || value instanceof DataRequirement || value instanceof Expression || value instanceof ParameterDefinition || value instanceof RelatedArtifact || value instanceof TriggerDefinition || value instanceof UsageContext || value instanceof Availability || value instanceof ExtendedContactDetail || value instanceof VirtualServiceDetail || value instanceof Dosage || value instanceof Meta))
        throw new FHIRException("Not the right type for DosageCondition.value[x]: "+value.fhirType());
      this.value = value;
      return this;
    }

    /**
     * @return {@link #text} (Free-text (human-readable) description.). This is the underlying object with id, value and extensions. The accessor "getText" gives direct access to the value
     */
    public StringType getTextElement() { 
      if (this.text == null)
        if (Configuration.errorOnAutoCreate())
          throw new Error("Attempt to auto-create DosageCondition.text");
        else if (Configuration.doAutoCreate())
          this.text = new StringType(); // bb
      return this.text;
    }

    public boolean hasTextElement() { 
      return this.text != null && !this.text.isEmpty();
    }

    public boolean hasText() { 
      return this.text != null && !this.text.isEmpty();
    }

    /**
     * @param value {@link #text} (Free-text (human-readable) description.). This is the underlying object with id, value and extensions. The accessor "getText" gives direct access to the value
     */
    public DosageCondition setTextElement(StringType value) { 
      this.text = value;
      return this;
    }

    /**
     * @return Free-text (human-readable) description.
     */
    public String getText() { 
      return this.text == null ? null : this.text.getValue();
    }

    /**
     * @param value Free-text (human-readable) description.
     */
    public DosageCondition setText(String value) { 
      if (Utilities.noString(value))
        this.text = null;
      else {
        if (this.text == null)
          this.text = new StringType();
        this.text.setValue(value);
      }
      return this;
    }

      protected void listChildren(List<Property> children) {
        super.listChildren(children);
        children.add(new Property("code", "CodeableConcept", "The specific event occurrence or resource context used as a base point (reference point) in time.  This establishes the context in which the 'path' is evaluated.", 0, 1, code));
        children.add(new Property("details", "CodeableConcept", "Additional details about the event - depends on the code.", 0, 1, details));
        children.add(new Property("operation", "code", "How the value is tested.", 0, 1, operation));
        children.add(new Property("value[x]", "base64Binary|boolean|canonical|code|date|dateTime|decimal|id|instant|integer|integer64|markdown|oid|positiveInt|string|time|unsignedInt|uri|url|uuid|Address|Age|Annotation|Attachment|CodeableConcept|CodeableReference|Coding|ContactPoint|Count|Distance|Duration|HumanName|Identifier|Money|Period|Quantity|Range|Ratio|RatioRange|Reference|SampledData|Signature|Timing|ContactDetail|DataRequirement|Expression|ParameterDefinition|RelatedArtifact|TriggerDefinition|UsageContext|Availability|ExtendedContactDetail|VirtualServiceDetail|Dosage|Meta", "The value for this critera.", 0, 1, value));
        children.add(new Property("text", "string", "Free-text (human-readable) description.", 0, 1, text));
      }

      @Override
      public Property getNamedProperty(int _hash, String _name, boolean _checkValid) throws FHIRException {
        switch (_hash) {
        case 3059181: /*code*/  return new Property("code", "CodeableConcept", "The specific event occurrence or resource context used as a base point (reference point) in time.  This establishes the context in which the 'path' is evaluated.", 0, 1, code);
        case 1557721666: /*details*/  return new Property("details", "CodeableConcept", "Additional details about the event - depends on the code.", 0, 1, details);
        case 1662702951: /*operation*/  return new Property("operation", "code", "How the value is tested.", 0, 1, operation);
        case -1410166417: /*value[x]*/  return new Property("value[x]", "base64Binary|boolean|canonical|code|date|dateTime|decimal|id|instant|integer|integer64|markdown|oid|positiveInt|string|time|unsignedInt|uri|url|uuid|Address|Age|Annotation|Attachment|CodeableConcept|CodeableReference|Coding|ContactPoint|Count|Distance|Duration|HumanName|Identifier|Money|Period|Quantity|Range|Ratio|RatioRange|Reference|SampledData|Signature|Timing|ContactDetail|DataRequirement|Expression|ParameterDefinition|RelatedArtifact|TriggerDefinition|UsageContext|Availability|ExtendedContactDetail|VirtualServiceDetail|Dosage|Meta", "The value for this critera.", 0, 1, value);
        case 111972721: /*value*/  return new Property("value[x]", "base64Binary|boolean|canonical|code|date|dateTime|decimal|id|instant|integer|integer64|markdown|oid|positiveInt|string|time|unsignedInt|uri|url|uuid|Address|Age|Annotation|Attachment|CodeableConcept|CodeableReference|Coding|ContactPoint|Count|Distance|Duration|HumanName|Identifier|Money|Period|Quantity|Range|Ratio|RatioRange|Reference|SampledData|Signature|Timing|ContactDetail|DataRequirement|Expression|ParameterDefinition|RelatedArtifact|TriggerDefinition|UsageContext|Availability|ExtendedContactDetail|VirtualServiceDetail|Dosage|Meta", "The value for this critera.", 0, 1, value);
        case -1535024575: /*valueBase64Binary*/  return new Property("value[x]", "base64Binary", "The value for this critera.", 0, 1, value);
        case 733421943: /*valueBoolean*/  return new Property("value[x]", "boolean", "The value for this critera.", 0, 1, value);
        case -786218365: /*valueCanonical*/  return new Property("value[x]", "canonical", "The value for this critera.", 0, 1, value);
        case -766209282: /*valueCode*/  return new Property("value[x]", "code", "The value for this critera.", 0, 1, value);
        case -766192449: /*valueDate*/  return new Property("value[x]", "date", "The value for this critera.", 0, 1, value);
        case 1047929900: /*valueDateTime*/  return new Property("value[x]", "dateTime", "The value for this critera.", 0, 1, value);
        case -2083993440: /*valueDecimal*/  return new Property("value[x]", "decimal", "The value for this critera.", 0, 1, value);
        case 231604844: /*valueId*/  return new Property("value[x]", "id", "The value for this critera.", 0, 1, value);
        case -1668687056: /*valueInstant*/  return new Property("value[x]", "instant", "The value for this critera.", 0, 1, value);
        case -1668204915: /*valueInteger*/  return new Property("value[x]", "integer", "The value for this critera.", 0, 1, value);
        case -1122120181: /*valueInteger64*/  return new Property("value[x]", "integer64", "The value for this critera.", 0, 1, value);
        case -497880704: /*valueMarkdown*/  return new Property("value[x]", "markdown", "The value for this critera.", 0, 1, value);
        case -1410178407: /*valueOid*/  return new Property("value[x]", "oid", "The value for this critera.", 0, 1, value);
        case -1249932027: /*valuePositiveInt*/  return new Property("value[x]", "positiveInt", "The value for this critera.", 0, 1, value);
        case -1424603934: /*valueString*/  return new Property("value[x]", "string", "The value for this critera.", 0, 1, value);
        case -765708322: /*valueTime*/  return new Property("value[x]", "time", "The value for this critera.", 0, 1, value);
        case 26529417: /*valueUnsignedInt*/  return new Property("value[x]", "unsignedInt", "The value for this critera.", 0, 1, value);
        case -1410172357: /*valueUri*/  return new Property("value[x]", "uri", "The value for this critera.", 0, 1, value);
        case -1410172354: /*valueUrl*/  return new Property("value[x]", "url", "The value for this critera.", 0, 1, value);
        case -765667124: /*valueUuid*/  return new Property("value[x]", "uuid", "The value for this critera.", 0, 1, value);
        case -478981821: /*valueAddress*/  return new Property("value[x]", "Address", "The value for this critera.", 0, 1, value);
        case -1410191922: /*valueAge*/  return new Property("value[x]", "Age", "The value for this critera.", 0, 1, value);
        case -67108992: /*valueAnnotation*/  return new Property("value[x]", "Annotation", "The value for this critera.", 0, 1, value);
        case -475566732: /*valueAttachment*/  return new Property("value[x]", "Attachment", "The value for this critera.", 0, 1, value);
        case 924902896: /*valueCodeableConcept*/  return new Property("value[x]", "CodeableConcept", "The value for this critera.", 0, 1, value);
        case -257955629: /*valueCodeableReference*/  return new Property("value[x]", "CodeableReference", "The value for this critera.", 0, 1, value);
        case -1887705029: /*valueCoding*/  return new Property("value[x]", "Coding", "The value for this critera.", 0, 1, value);
        case 944904545: /*valueContactPoint*/  return new Property("value[x]", "ContactPoint", "The value for this critera.", 0, 1, value);
        case 2017332766: /*valueCount*/  return new Property("value[x]", "Count", "The value for this critera.", 0, 1, value);
        case -456359802: /*valueDistance*/  return new Property("value[x]", "Distance", "The value for this critera.", 0, 1, value);
        case 1558135333: /*valueDuration*/  return new Property("value[x]", "Duration", "The value for this critera.", 0, 1, value);
        case -2026205465: /*valueHumanName*/  return new Property("value[x]", "HumanName", "The value for this critera.", 0, 1, value);
        case -130498310: /*valueIdentifier*/  return new Property("value[x]", "Identifier", "The value for this critera.", 0, 1, value);
        case 2026560975: /*valueMoney*/  return new Property("value[x]", "Money", "The value for this critera.", 0, 1, value);
        case -1524344174: /*valuePeriod*/  return new Property("value[x]", "Period", "The value for this critera.", 0, 1, value);
        case -2029823716: /*valueQuantity*/  return new Property("value[x]", "Quantity", "The value for this critera.", 0, 1, value);
        case 2030761548: /*valueRange*/  return new Property("value[x]", "Range", "The value for this critera.", 0, 1, value);
        case 2030767386: /*valueRatio*/  return new Property("value[x]", "Ratio", "The value for this critera.", 0, 1, value);
        case -706454461: /*valueRatioRange*/  return new Property("value[x]", "RatioRange", "The value for this critera.", 0, 1, value);
        case 1755241690: /*valueReference*/  return new Property("value[x]", "Reference", "The value for this critera.", 0, 1, value);
        case -962229101: /*valueSampledData*/  return new Property("value[x]", "SampledData", "The value for this critera.", 0, 1, value);
        case -540985785: /*valueSignature*/  return new Property("value[x]", "Signature", "The value for this critera.", 0, 1, value);
        case -1406282469: /*valueTiming*/  return new Property("value[x]", "Timing", "The value for this critera.", 0, 1, value);
        case -1125200224: /*valueContactDetail*/  return new Property("value[x]", "ContactDetail", "The value for this critera.", 0, 1, value);
        case 1710554248: /*valueDataRequirement*/  return new Property("value[x]", "DataRequirement", "The value for this critera.", 0, 1, value);
        case -307517719: /*valueExpression*/  return new Property("value[x]", "Expression", "The value for this critera.", 0, 1, value);
        case 1387478187: /*valueParameterDefinition*/  return new Property("value[x]", "ParameterDefinition", "The value for this critera.", 0, 1, value);
        case 1748214124: /*valueRelatedArtifact*/  return new Property("value[x]", "RelatedArtifact", "The value for this critera.", 0, 1, value);
        case 976830394: /*valueTriggerDefinition*/  return new Property("value[x]", "TriggerDefinition", "The value for this critera.", 0, 1, value);
        case 588000479: /*valueUsageContext*/  return new Property("value[x]", "UsageContext", "The value for this critera.", 0, 1, value);
        case 1678530924: /*valueAvailability*/  return new Property("value[x]", "Availability", "The value for this critera.", 0, 1, value);
        case -1567222041: /*valueExtendedContactDetail*/  return new Property("value[x]", "ExtendedContactDetail", "The value for this critera.", 0, 1, value);
        case 1943661868: /*valueVirtualServiceDetail*/  return new Property("value[x]", "VirtualServiceDetail", "The value for this critera.", 0, 1, value);
        case -1858636920: /*valueDosage*/  return new Property("value[x]", "Dosage", "The value for this critera.", 0, 1, value);
        case -765920490: /*valueMeta*/  return new Property("value[x]", "Meta", "The value for this critera.", 0, 1, value);
        case 3556653: /*text*/  return new Property("text", "string", "Free-text (human-readable) description.", 0, 1, text);
        default: return super.getNamedProperty(_hash, _name, _checkValid);
        }

      }

      @Override
      public Base[] getProperty(int hash, String name, boolean checkValid) throws FHIRException {
        switch (hash) {
        case 3059181: /*code*/ return this.code == null ? new Base[0] : new Base[] {this.code}; // CodeableConcept
        case 1557721666: /*details*/ return this.details == null ? new Base[0] : new Base[] {this.details}; // CodeableConcept
        case 1662702951: /*operation*/ return this.operation == null ? new Base[0] : new Base[] {this.operation}; // Enumeration<ComparisonOperationVS>
        case 111972721: /*value*/ return this.value == null ? new Base[0] : new Base[] {this.value}; // DataType
        case 3556653: /*text*/ return this.text == null ? new Base[0] : new Base[] {this.text}; // StringType
        default: return super.getProperty(hash, name, checkValid);
        }

      }

      @Override
      public Base setProperty(int hash, String name, Base value) throws FHIRException {
        switch (hash) {
        case 3059181: // code
          this.code = TypeConvertor.castToCodeableConcept(value); // CodeableConcept
          return value;
        case 1557721666: // details
          this.details = TypeConvertor.castToCodeableConcept(value); // CodeableConcept
          return value;
        case 1662702951: // operation
          value = new ComparisonOperationVSEnumFactory().fromType(TypeConvertor.castToCode(value));
          this.operation = (Enumeration) value; // Enumeration<ComparisonOperationVS>
          return value;
        case 111972721: // value
          this.value = TypeConvertor.castToType(value); // DataType
          return value;
        case 3556653: // text
          this.text = TypeConvertor.castToString(value); // StringType
          return value;
        default: return super.setProperty(hash, name, value);
        }

      }

      @Override
      public Base setProperty(String name, Base value) throws FHIRException {
        if (name.equals("code")) {
          this.code = TypeConvertor.castToCodeableConcept(value); // CodeableConcept
        } else if (name.equals("details")) {
          this.details = TypeConvertor.castToCodeableConcept(value); // CodeableConcept
        } else if (name.equals("operation")) {
          value = new ComparisonOperationVSEnumFactory().fromType(TypeConvertor.castToCode(value));
          this.operation = (Enumeration) value; // Enumeration<ComparisonOperationVS>
        } else if (name.equals("value[x]")) {
          this.value = TypeConvertor.castToType(value); // DataType
        } else if (name.equals("text")) {
          this.text = TypeConvertor.castToString(value); // StringType
        } else
          return super.setProperty(name, value);
        return value;
      }

      @Override
      public Base makeProperty(int hash, String name) throws FHIRException {
        switch (hash) {
        case 3059181:  return getCode();
        case 1557721666:  return getDetails();
        case 1662702951:  return getOperationElement();
        case -1410166417:  return getValue();
        case 111972721:  return getValue();
        case 3556653:  return getTextElement();
        default: return super.makeProperty(hash, name);
        }

      }

      @Override
      public String[] getTypesForProperty(int hash, String name) throws FHIRException {
        switch (hash) {
        case 3059181: /*code*/ return new String[] {"CodeableConcept"};
        case 1557721666: /*details*/ return new String[] {"CodeableConcept"};
        case 1662702951: /*operation*/ return new String[] {"code"};
        case 111972721: /*value*/ return new String[] {"base64Binary", "boolean", "canonical", "code", "date", "dateTime", "decimal", "id", "instant", "integer", "integer64", "markdown", "oid", "positiveInt", "string", "time", "unsignedInt", "uri", "url", "uuid", "Address", "Age", "Annotation", "Attachment", "CodeableConcept", "CodeableReference", "Coding", "ContactPoint", "Count", "Distance", "Duration", "HumanName", "Identifier", "Money", "Period", "Quantity", "Range", "Ratio", "RatioRange", "Reference", "SampledData", "Signature", "Timing", "ContactDetail", "DataRequirement", "Expression", "ParameterDefinition", "RelatedArtifact", "TriggerDefinition", "UsageContext", "Availability", "ExtendedContactDetail", "VirtualServiceDetail", "Dosage", "Meta"};
        case 3556653: /*text*/ return new String[] {"string"};
        default: return super.getTypesForProperty(hash, name);
        }

      }

      @Override
      public Base addChild(String name) throws FHIRException {
        if (name.equals("code")) {
          this.code = new CodeableConcept();
          return this.code;
        }
        else if (name.equals("details")) {
          this.details = new CodeableConcept();
          return this.details;
        }
        else if (name.equals("operation")) {
          throw new FHIRException("Cannot call addChild on a singleton property DosageCondition.operation");
        }
        else if (name.equals("valueBase64Binary")) {
          this.value = new Base64BinaryType();
          return this.value;
        }
        else if (name.equals("valueBoolean")) {
          this.value = new BooleanType();
          return this.value;
        }
        else if (name.equals("valueCanonical")) {
          this.value = new CanonicalType();
          return this.value;
        }
        else if (name.equals("valueCode")) {
          this.value = new CodeType();
          return this.value;
        }
        else if (name.equals("valueDate")) {
          this.value = new DateType();
          return this.value;
        }
        else if (name.equals("valueDateTime")) {
          this.value = new DateTimeType();
          return this.value;
        }
        else if (name.equals("valueDecimal")) {
          this.value = new DecimalType();
          return this.value;
        }
        else if (name.equals("valueId")) {
          this.value = new IdType();
          return this.value;
        }
        else if (name.equals("valueInstant")) {
          this.value = new InstantType();
          return this.value;
        }
        else if (name.equals("valueInteger")) {
          this.value = new IntegerType();
          return this.value;
        }
        else if (name.equals("valueInteger64")) {
          this.value = new Integer64Type();
          return this.value;
        }
        else if (name.equals("valueMarkdown")) {
          this.value = new MarkdownType();
          return this.value;
        }
        else if (name.equals("valueOid")) {
          this.value = new OidType();
          return this.value;
        }
        else if (name.equals("valuePositiveInt")) {
          this.value = new PositiveIntType();
          return this.value;
        }
        else if (name.equals("valueString")) {
          this.value = new StringType();
          return this.value;
        }
        else if (name.equals("valueTime")) {
          this.value = new TimeType();
          return this.value;
        }
        else if (name.equals("valueUnsignedInt")) {
          this.value = new UnsignedIntType();
          return this.value;
        }
        else if (name.equals("valueUri")) {
          this.value = new UriType();
          return this.value;
        }
        else if (name.equals("valueUrl")) {
          this.value = new UrlType();
          return this.value;
        }
        else if (name.equals("valueUuid")) {
          this.value = new UuidType();
          return this.value;
        }
        else if (name.equals("valueAddress")) {
          this.value = new Address();
          return this.value;
        }
        else if (name.equals("valueAge")) {
          this.value = new Age();
          return this.value;
        }
        else if (name.equals("valueAnnotation")) {
          this.value = new Annotation();
          return this.value;
        }
        else if (name.equals("valueAttachment")) {
          this.value = new Attachment();
          return this.value;
        }
        else if (name.equals("valueCodeableConcept")) {
          this.value = new CodeableConcept();
          return this.value;
        }
        else if (name.equals("valueCodeableReference")) {
          this.value = new CodeableReference();
          return this.value;
        }
        else if (name.equals("valueCoding")) {
          this.value = new Coding();
          return this.value;
        }
        else if (name.equals("valueContactPoint")) {
          this.value = new ContactPoint();
          return this.value;
        }
        else if (name.equals("valueCount")) {
          this.value = new Count();
          return this.value;
        }
        else if (name.equals("valueDistance")) {
          this.value = new Distance();
          return this.value;
        }
        else if (name.equals("valueDuration")) {
          this.value = new Duration();
          return this.value;
        }
        else if (name.equals("valueHumanName")) {
          this.value = new HumanName();
          return this.value;
        }
        else if (name.equals("valueIdentifier")) {
          this.value = new Identifier();
          return this.value;
        }
        else if (name.equals("valueMoney")) {
          this.value = new Money();
          return this.value;
        }
        else if (name.equals("valuePeriod")) {
          this.value = new Period();
          return this.value;
        }
        else if (name.equals("valueQuantity")) {
          this.value = new Quantity();
          return this.value;
        }
        else if (name.equals("valueRange")) {
          this.value = new Range();
          return this.value;
        }
        else if (name.equals("valueRatio")) {
          this.value = new Ratio();
          return this.value;
        }
        else if (name.equals("valueRatioRange")) {
          this.value = new RatioRange();
          return this.value;
        }
        else if (name.equals("valueReference")) {
          this.value = new Reference();
          return this.value;
        }
        else if (name.equals("valueSampledData")) {
          this.value = new SampledData();
          return this.value;
        }
        else if (name.equals("valueSignature")) {
          this.value = new Signature();
          return this.value;
        }
        else if (name.equals("valueTiming")) {
          this.value = new Timing();
          return this.value;
        }
        else if (name.equals("valueContactDetail")) {
          this.value = new ContactDetail();
          return this.value;
        }
        else if (name.equals("valueDataRequirement")) {
          this.value = new DataRequirement();
          return this.value;
        }
        else if (name.equals("valueExpression")) {
          this.value = new Expression();
          return this.value;
        }
        else if (name.equals("valueParameterDefinition")) {
          this.value = new ParameterDefinition();
          return this.value;
        }
        else if (name.equals("valueRelatedArtifact")) {
          this.value = new RelatedArtifact();
          return this.value;
        }
        else if (name.equals("valueTriggerDefinition")) {
          this.value = new TriggerDefinition();
          return this.value;
        }
        else if (name.equals("valueUsageContext")) {
          this.value = new UsageContext();
          return this.value;
        }
        else if (name.equals("valueAvailability")) {
          this.value = new Availability();
          return this.value;
        }
        else if (name.equals("valueExtendedContactDetail")) {
          this.value = new ExtendedContactDetail();
          return this.value;
        }
        else if (name.equals("valueVirtualServiceDetail")) {
          this.value = new VirtualServiceDetail();
          return this.value;
        }
        else if (name.equals("valueDosage")) {
          this.value = new Dosage();
          return this.value;
        }
        else if (name.equals("valueMeta")) {
          this.value = new Meta();
          return this.value;
        }
        else if (name.equals("text")) {
          throw new FHIRException("Cannot call addChild on a singleton property DosageCondition.text");
        }
        else
          return super.addChild(name);
      }

  public String fhirType() {
    return "DosageCondition";

  }

      public DosageCondition copy() {
        DosageCondition dst = new DosageCondition();
        copyValues(dst);
        return dst;
      }

      public void copyValues(DosageCondition dst) {
        super.copyValues(dst);
        dst.code = code == null ? null : code.copy();
        dst.details = details == null ? null : details.copy();
        dst.operation = operation == null ? null : operation.copy();
        dst.value = value == null ? null : value.copy();
        dst.text = text == null ? null : text.copy();
      }

      protected DosageCondition typedCopy() {
        return copy();
      }

      @Override
      public boolean equalsDeep(Base other_) {
        if (!super.equalsDeep(other_))
          return false;
        if (!(other_ instanceof DosageCondition))
          return false;
        DosageCondition o = (DosageCondition) other_;
        return compareDeep(code, o.code, true) && compareDeep(details, o.details, true) && compareDeep(operation, o.operation, true)
           && compareDeep(value, o.value, true) && compareDeep(text, o.text, true);
      }

      @Override
      public boolean equalsShallow(Base other_) {
        if (!super.equalsShallow(other_))
          return false;
        if (!(other_ instanceof DosageCondition))
          return false;
        DosageCondition o = (DosageCondition) other_;
        return compareValues(operation, o.operation, true) && compareValues(text, o.text, true);
      }

      public boolean isEmpty() {
        return super.isEmpty() && ca.uhn.fhir.util.ElementUtil.isEmpty(code, details, operation
          , value, text);
      }


}

