// This file is generated code - do not edit it.
//
// Generated by the HL7 FHIR code generator (org.hl7.fhir.core: core code generator)
// from hl7.fhir.r6.core#6.0.0-ballot5 (version 6.0.0-ballot5)
// on Fri, Aug 14, 2026 19:22+1000.
//
// Any changes made here will be lost the next time the generator is run. To change
// this file, change the definitions it is generated from, or change the generator.
package org.hl7.fhir.model.core;

/*
  Copyright (c) 2011+, HL7, Inc.
  All rights reserved.
  
  Redistribution and use in source and binary forms, with or without modification,
  are permitted provided that the following conditions are met:
  
   * Redistributions of source code must retain the above copyright notice, this
     list of conditions and the following disclaimer
   * Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation
     and/or other materials provided with the distribution.
   * Neither the name of HL7 nor the names of its contributors may be used to 
     endorse or promote products derived from this software without specific 
     prior written permission.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.
  */

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.hl7.fhir.utilities.Utilities;
import org.hl7.fhir.model.core.Enumerations.*;
import org.hl7.fhir.instance.model.api.IBaseDatatypeElement;
import org.hl7.fhir.exceptions.FHIRException;
import org.hl7.fhir.instance.model.api.ICompositeType;
import ca.uhn.fhir.model.api.annotation.Child;
import ca.uhn.fhir.model.api.annotation.ChildOrder;
import ca.uhn.fhir.model.api.annotation.DatatypeDef;
import ca.uhn.fhir.model.api.annotation.Description;
import ca.uhn.fhir.model.api.annotation.Block;

/**
 * RelativeTime Type: RelativeTime expresses a time or time period as relative to the time of an event defined in data types other than dateTime.
 */
@DatatypeDef(name="RelativeTime")
@javax.annotation.processing.Generated(value = "org.hl7.fhir.core.generator.engine.JavaCoreGenerator", comments = "generated from hl7.fhir.r6.core#6.0.0-ballot5")
public class RelativeTime extends BackboneType implements ICompositeType {

    /**
     * The specific event occurrence or resource context used as a base point (reference point) in time.  This establishes the context in which the 'path' is evaluated.
     */
    @Child(name = "contextReference", type = {Reference.class}, order=0, min=0, max=1, modifier=false, summary=true)
    @Description(shortDefinition="The specific event occurrence or resource context used as a base point (reference point) in time")
    protected Reference contextReference;

    /**
     * The type of event used as a base point.  Instances of this definition will establish the context for evaluating the path to determine the base time for the offset.
     */
    @Child(name = "contextDefinition", type = {CanonicalType.class}, order=1, min=0, max=1, modifier=false, summary=true)
    @Description(shortDefinition="The type of event used as a base point")
    protected CanonicalType contextDefinition;

    /**
     * Path to the element defining the basis for the relative time. Any valid FHIRPath expression.
     */
    @Child(name = "contextPath", type = {StringType.class}, order=2, min=0, max=1, modifier=false, summary=true)
    @Description(shortDefinition="Path to the element defining the basis for the relative time")
    protected StringType contextPath;

    /**
     * Coded representation of the event used as a base point (reference point) in time.
     */
    @Child(name = "contextCode", type = {CodeableConcept.class}, order=3, min=0, max=1, modifier=false, summary=true)
    @Description(shortDefinition="Coded representation of the event used as a base point (reference point) in time")
    @ca.uhn.fhir.model.api.annotation.Binding(valueSet="http://hl7.org/fhir/ValueSet/relativetime-codes")
    protected CodeableConcept contextCode;

    /**
     * An offset or offset range before (negative values) or after (positive values) the event. Range is limited to time-valued quantities (Durations).
     */
    @Child(name = "offset", type = {Duration.class, Range.class}, order=4, min=0, max=1, modifier=false, summary=true)
    @Description(shortDefinition="An offset or offset range before (negative values) or after (positive values) the event")
    protected DataType offset;

    /**
     * Free-text (human-readable) description.
     */
    @Child(name = "text", type = {StringType.class}, order=5, min=0, max=1, modifier=false, summary=true)
    @Description(shortDefinition="Free-text description")
    protected StringType text;

    private static final long serialVersionUID = -69334872L;

  /**
   * Constructor
   */
    public RelativeTime() {
      super();
    }

    /**
     * @return {@link #contextReference} (The specific event occurrence or resource context used as a base point (reference point) in time.  This establishes the context in which the 'path' is evaluated.)
     */
    public Reference getContextReference() { 
      if (this.contextReference == null)
        if (Configuration.errorOnAutoCreate())
          throw new Error("Attempt to auto-create RelativeTime.contextReference");
        else if (Configuration.doAutoCreate())
          this.contextReference = new Reference(); // cc
      return this.contextReference;
    }

    public boolean hasContextReference() { 
      return this.contextReference != null && !this.contextReference.isEmpty();
    }

    /**
     * @param value {@link #contextReference} (The specific event occurrence or resource context used as a base point (reference point) in time.  This establishes the context in which the 'path' is evaluated.)
     */
    public RelativeTime setContextReference(Reference value) { 
      this.contextReference = value;
      return this;
    }

    /**
     * @return {@link #contextDefinition} (The type of event used as a base point.  Instances of this definition will establish the context for evaluating the path to determine the base time for the offset.). This is the underlying object with id, value and extensions. The accessor "getContextDefinition" gives direct access to the value
     */
    public CanonicalType getContextDefinitionElement() { 
      if (this.contextDefinition == null)
        if (Configuration.errorOnAutoCreate())
          throw new Error("Attempt to auto-create RelativeTime.contextDefinition");
        else if (Configuration.doAutoCreate())
          this.contextDefinition = new CanonicalType(); // bb
      return this.contextDefinition;
    }

    public boolean hasContextDefinitionElement() { 
      return this.contextDefinition != null && !this.contextDefinition.isEmpty();
    }

    public boolean hasContextDefinition() { 
      return this.contextDefinition != null && !this.contextDefinition.isEmpty();
    }

    /**
     * @param value {@link #contextDefinition} (The type of event used as a base point.  Instances of this definition will establish the context for evaluating the path to determine the base time for the offset.). This is the underlying object with id, value and extensions. The accessor "getContextDefinition" gives direct access to the value
     */
    public RelativeTime setContextDefinitionElement(CanonicalType value) { 
      this.contextDefinition = value;
      return this;
    }

    /**
     * @return The type of event used as a base point.  Instances of this definition will establish the context for evaluating the path to determine the base time for the offset.
     */
    public String getContextDefinition() { 
      return this.contextDefinition == null ? null : this.contextDefinition.getValue();
    }

    /**
     * @param value The type of event used as a base point.  Instances of this definition will establish the context for evaluating the path to determine the base time for the offset.
     */
    public RelativeTime setContextDefinition(String value) { 
      if (Utilities.noString(value))
        this.contextDefinition = null;
      else {
        if (this.contextDefinition == null)
          this.contextDefinition = new CanonicalType();
        this.contextDefinition.setValue(value);
      }
      return this;
    }

    /**
     * @return {@link #contextPath} (Path to the element defining the basis for the relative time. Any valid FHIRPath expression.). This is the underlying object with id, value and extensions. The accessor "getContextPath" gives direct access to the value
     */
    public StringType getContextPathElement() { 
      if (this.contextPath == null)
        if (Configuration.errorOnAutoCreate())
          throw new Error("Attempt to auto-create RelativeTime.contextPath");
        else if (Configuration.doAutoCreate())
          this.contextPath = new StringType(); // bb
      return this.contextPath;
    }

    public boolean hasContextPathElement() { 
      return this.contextPath != null && !this.contextPath.isEmpty();
    }

    public boolean hasContextPath() { 
      return this.contextPath != null && !this.contextPath.isEmpty();
    }

    /**
     * @param value {@link #contextPath} (Path to the element defining the basis for the relative time. Any valid FHIRPath expression.). This is the underlying object with id, value and extensions. The accessor "getContextPath" gives direct access to the value
     */
    public RelativeTime setContextPathElement(StringType value) { 
      this.contextPath = value;
      return this;
    }

    /**
     * @return Path to the element defining the basis for the relative time. Any valid FHIRPath expression.
     */
    public String getContextPath() { 
      return this.contextPath == null ? null : this.contextPath.getValue();
    }

    /**
     * @param value Path to the element defining the basis for the relative time. Any valid FHIRPath expression.
     */
    public RelativeTime setContextPath(String value) { 
      if (Utilities.noString(value))
        this.contextPath = null;
      else {
        if (this.contextPath == null)
          this.contextPath = new StringType();
        this.contextPath.setValue(value);
      }
      return this;
    }

    /**
     * @return {@link #contextCode} (Coded representation of the event used as a base point (reference point) in time.)
     */
    public CodeableConcept getContextCode() { 
      if (this.contextCode == null)
        if (Configuration.errorOnAutoCreate())
          throw new Error("Attempt to auto-create RelativeTime.contextCode");
        else if (Configuration.doAutoCreate())
          this.contextCode = new CodeableConcept(); // cc
      return this.contextCode;
    }

    public boolean hasContextCode() { 
      return this.contextCode != null && !this.contextCode.isEmpty();
    }

    /**
     * @param value {@link #contextCode} (Coded representation of the event used as a base point (reference point) in time.)
     */
    public RelativeTime setContextCode(CodeableConcept value) { 
      this.contextCode = value;
      return this;
    }

    /**
     * @return {@link #offset} (An offset or offset range before (negative values) or after (positive values) the event. Range is limited to time-valued quantities (Durations).)
     */
    public DataType getOffset() { 
      return this.offset;
    }

    /**
     * @return {@link #offset} (An offset or offset range before (negative values) or after (positive values) the event. Range is limited to time-valued quantities (Durations).)
     */
    public Duration getOffsetDuration() throws FHIRException { 
      if (this.offset == null)
        this.offset = new Duration();
      if (!(this.offset instanceof Duration))
        throw new FHIRException("Type mismatch: the type Duration was expected, but "+this.offset.getClass().getName()+" was encountered");
      return (Duration) this.offset;
    }

    public boolean hasOffsetDuration() { 
      return this.offset != null && this.offset instanceof Duration;
    }

    /**
     * @return {@link #offset} (An offset or offset range before (negative values) or after (positive values) the event. Range is limited to time-valued quantities (Durations).)
     */
    public Range getOffsetRange() throws FHIRException { 
      if (this.offset == null)
        this.offset = new Range();
      if (!(this.offset instanceof Range))
        throw new FHIRException("Type mismatch: the type Range was expected, but "+this.offset.getClass().getName()+" was encountered");
      return (Range) this.offset;
    }

    public boolean hasOffsetRange() { 
      return this.offset != null && this.offset instanceof Range;
    }

    public boolean hasOffset() { 
      return this.offset != null && !this.offset.isEmpty();
    }

    /**
     * @param value {@link #offset} (An offset or offset range before (negative values) or after (positive values) the event. Range is limited to time-valued quantities (Durations).)
     */
    public RelativeTime setOffset(DataType value) { 
      if (value != null && !(value instanceof Duration || value instanceof Range))
        throw new FHIRException("Not the right type for RelativeTime.offset[x]: "+value.fhirType());
      this.offset = value;
      return this;
    }

    /**
     * @return {@link #text} (Free-text (human-readable) description.). This is the underlying object with id, value and extensions. The accessor "getText" gives direct access to the value
     */
    public StringType getTextElement() { 
      if (this.text == null)
        if (Configuration.errorOnAutoCreate())
          throw new Error("Attempt to auto-create RelativeTime.text");
        else if (Configuration.doAutoCreate())
          this.text = new StringType(); // bb
      return this.text;
    }

    public boolean hasTextElement() { 
      return this.text != null && !this.text.isEmpty();
    }

    public boolean hasText() { 
      return this.text != null && !this.text.isEmpty();
    }

    /**
     * @param value {@link #text} (Free-text (human-readable) description.). This is the underlying object with id, value and extensions. The accessor "getText" gives direct access to the value
     */
    public RelativeTime setTextElement(StringType value) { 
      this.text = value;
      return this;
    }

    /**
     * @return Free-text (human-readable) description.
     */
    public String getText() { 
      return this.text == null ? null : this.text.getValue();
    }

    /**
     * @param value Free-text (human-readable) description.
     */
    public RelativeTime setText(String value) { 
      if (Utilities.noString(value))
        this.text = null;
      else {
        if (this.text == null)
          this.text = new StringType();
        this.text.setValue(value);
      }
      return this;
    }

      protected void listChildren(List<Property> children) {
        super.listChildren(children);
        children.add(new Property("contextReference", "Reference(Any)", "The specific event occurrence or resource context used as a base point (reference point) in time.  This establishes the context in which the 'path' is evaluated.", 0, 1, contextReference));
        children.add(new Property("contextDefinition", "canonical(ActivityDefinition|EventDefinition|PlanDefinition|ObservationDefinition)", "The type of event used as a base point.  Instances of this definition will establish the context for evaluating the path to determine the base time for the offset.", 0, 1, contextDefinition));
        children.add(new Property("contextPath", "string", "Path to the element defining the basis for the relative time. Any valid FHIRPath expression.", 0, 1, contextPath));
        children.add(new Property("contextCode", "CodeableConcept", "Coded representation of the event used as a base point (reference point) in time.", 0, 1, contextCode));
        children.add(new Property("offset[x]", "Duration|Range", "An offset or offset range before (negative values) or after (positive values) the event. Range is limited to time-valued quantities (Durations).", 0, 1, offset));
        children.add(new Property("text", "string", "Free-text (human-readable) description.", 0, 1, text));
      }

      @Override
      public Property getNamedProperty(int _hash, String _name, boolean _checkValid) throws FHIRException {
        switch (_hash) {
        case 404102748: /*contextReference*/  return new Property("contextReference", "Reference(Any)", "The specific event occurrence or resource context used as a base point (reference point) in time.  This establishes the context in which the 'path' is evaluated.", 0, 1, contextReference);
        case 1537882210: /*contextDefinition*/  return new Property("contextDefinition", "canonical(ActivityDefinition|EventDefinition|PlanDefinition|ObservationDefinition)", "The type of event used as a base point.  Instances of this definition will establish the context for evaluating the path to determine the base time for the offset.", 0, 1, contextDefinition);
        case -102982028: /*contextPath*/  return new Property("contextPath", "string", "Path to the element defining the basis for the relative time. Any valid FHIRPath expression.", 0, 1, contextPath);
        case -103356356: /*contextCode*/  return new Property("contextCode", "CodeableConcept", "Coded representation of the event used as a base point (reference point) in time.", 0, 1, contextCode);
        case -1960684787: /*offset[x]*/  return new Property("offset[x]", "Duration|Range", "An offset or offset range before (negative values) or after (positive values) the event. Range is limited to time-valued quantities (Durations).", 0, 1, offset);
        case -1019779949: /*offset*/  return new Property("offset[x]", "Duration|Range", "An offset or offset range before (negative values) or after (positive values) the event. Range is limited to time-valued quantities (Durations).", 0, 1, offset);
        case 134075207: /*offsetDuration*/  return new Property("offset[x]", "Duration", "An offset or offset range before (negative values) or after (positive values) the event. Range is limited to time-valued quantities (Durations).", 0, 1, offset);
        case 1263585386: /*offsetRange*/  return new Property("offset[x]", "Range", "An offset or offset range before (negative values) or after (positive values) the event. Range is limited to time-valued quantities (Durations).", 0, 1, offset);
        case 3556653: /*text*/  return new Property("text", "string", "Free-text (human-readable) description.", 0, 1, text);
        default: return super.getNamedProperty(_hash, _name, _checkValid);
        }

      }

      @Override
      public Base[] getProperty(int hash, String name, boolean checkValid) throws FHIRException {
        switch (hash) {
        case 404102748: /*contextReference*/ return this.contextReference == null ? new Base[0] : new Base[] {this.contextReference}; // Reference
        case 1537882210: /*contextDefinition*/ return this.contextDefinition == null ? new Base[0] : new Base[] {this.contextDefinition}; // CanonicalType
        case -102982028: /*contextPath*/ return this.contextPath == null ? new Base[0] : new Base[] {this.contextPath}; // StringType
        case -103356356: /*contextCode*/ return this.contextCode == null ? new Base[0] : new Base[] {this.contextCode}; // CodeableConcept
        case -1019779949: /*offset*/ return this.offset == null ? new Base[0] : new Base[] {this.offset}; // DataType
        case 3556653: /*text*/ return this.text == null ? new Base[0] : new Base[] {this.text}; // StringType
        default: return super.getProperty(hash, name, checkValid);
        }

      }

      @Override
      public Base setProperty(int hash, String name, Base value) throws FHIRException {
        switch (hash) {
        case 404102748: // contextReference
          this.contextReference = TypeConvertor.castToReference(value); // Reference
          return value;
        case 1537882210: // contextDefinition
          this.contextDefinition = TypeConvertor.castToCanonical(value); // CanonicalType
          return value;
        case -102982028: // contextPath
          this.contextPath = TypeConvertor.castToString(value); // StringType
          return value;
        case -103356356: // contextCode
          this.contextCode = TypeConvertor.castToCodeableConcept(value); // CodeableConcept
          return value;
        case -1019779949: // offset
          this.offset = TypeConvertor.castToType(value); // DataType
          return value;
        case 3556653: // text
          this.text = TypeConvertor.castToString(value); // StringType
          return value;
        default: return super.setProperty(hash, name, value);
        }

      }

      @Override
      public Base setProperty(String name, Base value) throws FHIRException {
        if (name.equals("contextReference")) {
          this.contextReference = TypeConvertor.castToReference(value); // Reference
        } else if (name.equals("contextDefinition")) {
          this.contextDefinition = TypeConvertor.castToCanonical(value); // CanonicalType
        } else if (name.equals("contextPath")) {
          this.contextPath = TypeConvertor.castToString(value); // StringType
        } else if (name.equals("contextCode")) {
          this.contextCode = TypeConvertor.castToCodeableConcept(value); // CodeableConcept
        } else if (name.equals("offset[x]")) {
          this.offset = TypeConvertor.castToType(value); // DataType
        } else if (name.equals("text")) {
          this.text = TypeConvertor.castToString(value); // StringType
        } else
          return super.setProperty(name, value);
        return value;
      }

      @Override
      public Base makeProperty(int hash, String name) throws FHIRException {
        switch (hash) {
        case 404102748:  return getContextReference();
        case 1537882210:  return getContextDefinitionElement();
        case -102982028:  return getContextPathElement();
        case -103356356:  return getContextCode();
        case -1960684787:  return getOffset();
        case -1019779949:  return getOffset();
        case 3556653:  return getTextElement();
        default: return super.makeProperty(hash, name);
        }

      }

      @Override
      public String[] getTypesForProperty(int hash, String name) throws FHIRException {
        switch (hash) {
        case 404102748: /*contextReference*/ return new String[] {"Reference"};
        case 1537882210: /*contextDefinition*/ return new String[] {"canonical"};
        case -102982028: /*contextPath*/ return new String[] {"string"};
        case -103356356: /*contextCode*/ return new String[] {"CodeableConcept"};
        case -1019779949: /*offset*/ return new String[] {"Duration", "Range"};
        case 3556653: /*text*/ return new String[] {"string"};
        default: return super.getTypesForProperty(hash, name);
        }

      }

      @Override
      public Base addChild(String name) throws FHIRException {
        if (name.equals("contextReference")) {
          this.contextReference = new Reference();
          return this.contextReference;
        }
        else if (name.equals("contextDefinition")) {
          throw new FHIRException("Cannot call addChild on a singleton property RelativeTime.contextDefinition");
        }
        else if (name.equals("contextPath")) {
          throw new FHIRException("Cannot call addChild on a singleton property RelativeTime.contextPath");
        }
        else if (name.equals("contextCode")) {
          this.contextCode = new CodeableConcept();
          return this.contextCode;
        }
        else if (name.equals("offsetDuration")) {
          this.offset = new Duration();
          return this.offset;
        }
        else if (name.equals("offsetRange")) {
          this.offset = new Range();
          return this.offset;
        }
        else if (name.equals("text")) {
          throw new FHIRException("Cannot call addChild on a singleton property RelativeTime.text");
        }
        else
          return super.addChild(name);
      }

  public String fhirType() {
    return "RelativeTime";

  }

      public RelativeTime copy() {
        RelativeTime dst = new RelativeTime();
        copyValues(dst);
        return dst;
      }

      public void copyValues(RelativeTime dst) {
        super.copyValues(dst);
        dst.contextReference = contextReference == null ? null : contextReference.copy();
        dst.contextDefinition = contextDefinition == null ? null : contextDefinition.copy();
        dst.contextPath = contextPath == null ? null : contextPath.copy();
        dst.contextCode = contextCode == null ? null : contextCode.copy();
        dst.offset = offset == null ? null : offset.copy();
        dst.text = text == null ? null : text.copy();
      }

      protected RelativeTime typedCopy() {
        return copy();
      }

      @Override
      public boolean equalsDeep(Base other_) {
        if (!super.equalsDeep(other_))
          return false;
        if (!(other_ instanceof RelativeTime))
          return false;
        RelativeTime o = (RelativeTime) other_;
        return compareDeep(contextReference, o.contextReference, true) && compareDeep(contextDefinition, o.contextDefinition, true)
           && compareDeep(contextPath, o.contextPath, true) && compareDeep(contextCode, o.contextCode, true)
           && compareDeep(offset, o.offset, true) && compareDeep(text, o.text, true);
      }

      @Override
      public boolean equalsShallow(Base other_) {
        if (!super.equalsShallow(other_))
          return false;
        if (!(other_ instanceof RelativeTime))
          return false;
        RelativeTime o = (RelativeTime) other_;
        return compareValues(contextDefinition, o.contextDefinition, true) && compareValues(contextPath, o.contextPath, true)
           && compareValues(text, o.text, true);
      }

      public boolean isEmpty() {
        return super.isEmpty() && ca.uhn.fhir.util.ElementUtil.isEmpty(contextReference, contextDefinition
          , contextPath, contextCode, offset, text);
      }


}

