# Overrides for dependencies whose declared (or undeclared) license does not
# exactly match an entry in the LICENSE_CHECK profile's <includedLicenses>,
# and which are not resolved by the plugin's OR semantics for dual/triple
# licensed dependencies (a dependency licensed under several licenses passes
# as soon as one of them is on the allowlist, so those need no entry here).
#
# Format: groupId--artifactId--version=License Name
#
# Every entry below must have a comment explaining why it's here, per the
# project's license-review policy. See src/license/README.md.
#
# No license declared in the dependency's own pom. Is Apache License 2.0:
# https://github.com/NCIP/lexevs/blob/master/lgSharedLibraries/apache/commons/jakarta-regexp-1.4.license.txt
jakarta-regexp--jakarta-regexp--1.4=Apache License 2.0

# No license declared in the dependency's own pom. Is BSD:
# https://mvnrepository.com/artifact/org.antlr/ST4/4.1
org.antlr--ST4--4.1=New BSD License
