// This file is generated code - do not edit it.
//
// Generated by the HL7 FHIR code generator (org.hl7.fhir.core: ig-codegen)
// from hl7.fhir.uv.tools#1.1.2 (version 5.0.0)
// on Mon, Aug 17, 2026 16:12+1000.
//
// Any changes made here will be lost the next time the generator is run. To change
// this file, change the definitions it is generated from, or change the generator.

package org.hl7.fhir.model.tools;

/*
  Copyright (c) 2011+, HL7, Inc.
  All rights reserved.
  
  Redistribution and use in source and binary forms, with or without modification, \
  are permitted provided that the following conditions are met:
  
   * Redistributions of source code must retain the above copyright notice, this \
     list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above copyright notice, \
     this list of conditions and the following disclaimer in the documentation \
     and/or other materials provided with the distribution.
   * Neither the name of HL7 nor the names of its contributors may be used to 
     endorse or promote products derived from this software without specific 
     prior written permission.
  
  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\" AND \
  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED \
  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. \
  IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, \
  INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT \
  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR \
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, \
  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) \
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE \
  POSSIBILITY OF SUCH DAMAGE.
  */

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.hl7.fhir.model.tools.Enumerations.*;
import org.hl7.fhir.exceptions.FHIRException;
import java.util.EnumSet;
import org.hl7.fhir.model.*;
import org.hl7.fhir.model.core.*;
import org.hl7.fhir.model.Base.CopyObjectOptions;
import org.hl7.fhir.instance.model.api.ICompositeType;
import ca.uhn.fhir.model.api.annotation.Child;
import ca.uhn.fhir.model.api.annotation.ChildOrder;
import ca.uhn.fhir.model.api.annotation.DatatypeDef;
import ca.uhn.fhir.model.api.annotation.Description;
import ca.uhn.fhir.model.api.annotation.Block;

/**
 * This is a concrete subtype of Base that has extensions (though the format in JSON is different)
 */
@DatatypeDef(name="CDSHooksExtensions")
@javax.annotation.processing.Generated(value = "org.hl7.fhir.validation.codegen.LogicalModelCodeGenerator", comments = "generated from hl7.fhir.uv.tools#1.1.2")
public class CDSHooksExtensions extends LogicalBase implements ICompositeType {

    /**
     * An extension where the name is defined by the extension definition, and the extension definition is of any type (including primitives, though the 'id' element cannot be represented for primitives)
     */
    @Child(name = "extension", type = {Base.class}, order=0, min=0, max=Child.MAX_UNLIMITED, modifier=false, summary=false)
    @Description(shortDefinition="An extension of any type")
    protected List<NamedElementExtension> extensionList;

    private static final long serialVersionUID = 163508525L;

  /**
   * Constructor
   */
    public CDSHooksExtensions() {
      super();
    }

  /**
   * Constructor
   *
   * @param context the model context this object belongs to - all objects in a tree must share the same context (see Base.modelContext)
   */
    public CDSHooksExtensions(IModelContext modelContext) {
      super();
      this.modelContext = modelContext;
    }

    /**
     * @return {@link #extension} (An extension where the name is defined by the extension definition, and the extension definition is of any type (including primitives, though the 'id' element cannot be represented for primitives))
     */
    public List<NamedElementExtension> getExtensionList() { 
      if (this.extensionList == null)
        this.extensionList = new ArrayList<NamedElementExtension>();
      return this.extensionList;
    }

    /**
     * @return Returns a reference to <code>this</code> for easy method chaining
     */
    public CDSHooksExtensions setExtensionList(List<NamedElementExtension> theExtension) { 
      this.extensionList = theExtension;
      return this;
    }

    public boolean hasExtension() { 
      if (this.extensionList == null)
        return false;
      for (NamedElementExtension item : this.extensionList)
        if (!item.isEmpty())
          return true;
      return false;
    }

    public CDSHooksExtensions addExtension(NamedElementExtension t) { //3b
      if (t == null)
        return this;
      if (this.extensionList == null)
        this.extensionList = new ArrayList<NamedElementExtension>();
      this.extensionList.add(t);
      return this;
    }

      protected void listChildren(List<Property> children) {
        super.listChildren(children);
        children.add(new Property("extension", "Base", "An extension where the name is defined by the extension definition, and the extension definition is of any type (including primitives, though the 'id' element cannot be represented for primitives)", 0, java.lang.Integer.MAX_VALUE, extensionList));
      }

      @Override
      public Property getNamedProperty(String _name, boolean _checkValid) throws FHIRException {
        switch (_name) {
        case "extension":  return new Property("extension", "Base", "An extension where the name is defined by the extension definition, and the extension definition is of any type (including primitives, though the 'id' element cannot be represented for primitives)", 0, java.lang.Integer.MAX_VALUE, extensionList);
        default: return super.getNamedProperty(_name, _checkValid);
        }

      }

      @Override
      public Base[] getNamedValue(String name, boolean checkValid) throws FHIRException {
        switch (name) {
        case "extension": return this.extensionList == null ? new Base[0] : this.extensionList.toArray(new Base[this.extensionList.size()]); // NamedElementExtension
        default: return super.getNamedValue(name, checkValid);
        }

      }

      @Override
      public Base setProperty(String name, Base value) throws FHIRException {
        if (name.equals("extension")) {
          this.getExtensionList().add((NamedElementExtension) value); // NamedElementExtension
        } else
          return super.setProperty(name, value);
        return value;
      }

      @Override
      public void removeChild(String name, Base value) throws FHIRException {
        switch (name) {
        case "extension":
          this.getExtensionList().remove(value);
          return;
        default:
          super.removeChild(name, value);
        }
      }

      @Override
      public Base makeProperty(String name) throws FHIRException {
        switch (name) {
        case "extension":
          throw new Error("Unable to make an instance of the abstract property 'extension'");
        default: return super.makeProperty(name);
        }

      }

      @Override
      public Base addChild(String name) throws FHIRException {
        if (name.equals("extension")) {
          throw new FHIRException("Cannot call addChild on an abstract type CDSHooksExtensions.extension");
        }
        else
          return super.addChild(name);
      }

  public String fhirType() {
    return "CDSHooksExtensions";

  }

      public CDSHooksExtensions copy(EnumSet<CopyObjectOptions> options) {
        CDSHooksExtensions dst = new CDSHooksExtensions(this.modelContext);
        copyValues(dst, options);
        return dst;
      }

      public void copyValues(CDSHooksExtensions dst, EnumSet<CopyObjectOptions> options) {
        super.copyValues(dst, options);
        if (extensionList != null) {
          dst.extensionList = new ArrayList<NamedElementExtension>();
          for (NamedElementExtension i : extensionList)
            dst.extensionList.add(i.copy(options));
        };
      }

      @Override
      public boolean equalsDeep(Base other_) {
        if (!super.equalsDeep(other_))
          return false;
        if (!(other_ instanceof CDSHooksExtensions))
          return false;
        CDSHooksExtensions o = (CDSHooksExtensions) other_;
        return compareDeep(extensionList, o.extensionList, true);
      }

      @Override
      public boolean equalsShallow(Base other_) {
        if (!super.equalsShallow(other_))
          return false;
        if (!(other_ instanceof CDSHooksExtensions))
          return false;
        CDSHooksExtensions o = (CDSHooksExtensions) other_;
        return true;
      }

      public boolean isEmpty() {
        return super.isEmpty() && ca.uhn.fhir.util.ElementUtil.isEmpty(extensionList);
      }


}

