package org.hl7.fhir.test.profiles.codegen;


import org.hl7.fhir.model.*;
import org.hl7.fhir.model.core.*;
import org.hl7.fhir.services.profilemodel.PEInstance;
import org.hl7.fhir.services.profilemodel.gen.PEGeneratedBase;


// Generated by the HAPI Java Profile Generator, 5/11/24, 6:00 pm

/**
 * Extension for the date where a condition lost focus in a specific clinical 
 * context
 *
 */
public class NotFollowedAnymore extends PEGeneratedBase {

  public static final String CANONICAL_URL = "http://hl7.dk/fhir/core/StructureDefinition/NotFollowedAnymore|3.2.0";


  /**
   * Parameter-less constructor.
   *
   */
  public NotFollowedAnymore() {
  }

  /**
   * Used when loading other models 
   *
   */
  public static NotFollowedAnymore fromSource(PEInstance source) {
    NotFollowedAnymore theThing = new NotFollowedAnymore();
    theThing.workerContext = source.getContext();
    theThing.load(source);
    return theThing;
  }

  public void load(PEInstance src) {
    clear();

  }

  public void save(PEInstance tgt, boolean nulls) {

  }



  public void clear() {

  }

}
