package org.hl7.fhir.convertors.conv50_N.resources50_N;

import org.hl7.fhir.convertors.context.ConversionContext50_N;
import org.hl7.fhir.exceptions.FHIRException;

// generated by the converter generator: R5 <-> R6 (6.0.0-ballot5)
// the R5 side is asserted from the R6 definitions - compile errors mark real version differences

public class Ingredient50_N {

  public static org.hl7.fhir.model.core.Ingredient convertIngredient(org.hl7.fhir.r5.model.Ingredient src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.Ingredient tgt = new org.hl7.fhir.model.core.Ingredient();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyDomainResource(src, tgt);
    if (src.hasIdentifier())
      tgt.getIdentifierList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Identifier50_N.convertIdentifier(src.getIdentifier()));
    if (src.hasStatus())
      tgt.setStatusElement(org.hl7.fhir.convertors.conv50_N.resources50_N.Enumerations50_N.convertPublicationStatus(src.getStatusElement()));
    for (org.hl7.fhir.r5.model.Reference t : src.getFor())
      tgt.getForList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    if (src.hasRole())
      tgt.setRole(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getRole()));
    for (org.hl7.fhir.r5.model.CodeableConcept t : src.getFunction())
      tgt.getFunctionList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    if (src.hasGroup())
      tgt.setGroup(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getGroup()));
    if (src.hasAllergenicIndicator())
      tgt.setAllergenicIndicatorElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Boolean50_N.convertBoolean(src.getAllergenicIndicatorElement()));
    if (src.hasComment())
      tgt.setCommentElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getCommentElement()));
    for (org.hl7.fhir.r5.model.Ingredient.IngredientManufacturerComponent t : src.getManufacturer())
      tgt.getManufacturerList().add(convertIngredientManufacturerComponent(t));
    if (src.hasSubstance())
      tgt.setSubstance(convertIngredientSubstanceComponent(src.getSubstance()));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.Ingredient convertIngredient(org.hl7.fhir.model.core.Ingredient src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.Ingredient tgt = new org.hl7.fhir.r5.model.Ingredient();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyDomainResource(src, tgt);
    for (org.hl7.fhir.model.core.Identifier t : src.getIdentifierList())
      tgt.setIdentifier(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Identifier50_N.convertIdentifier(t));
    if (src.hasStatus())
      tgt.setStatusElement(org.hl7.fhir.convertors.conv50_N.resources50_N.Enumerations50_N.convertPublicationStatus(src.getStatusElement()));
    for (org.hl7.fhir.model.core.Reference t : src.getForList())
      tgt.getFor().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    if (src.hasRole())
      tgt.setRole(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getRole()));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getFunctionList())
      tgt.getFunction().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    if (src.hasGroup())
      tgt.setGroup(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getGroup()));
    if (src.hasAllergenicIndicator())
      tgt.setAllergenicIndicatorElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Boolean50_N.convertBoolean(src.getAllergenicIndicatorElement()));
    if (src.hasComment())
      tgt.setCommentElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getCommentElement()));
    for (org.hl7.fhir.model.core.Ingredient.IngredientManufacturerComponent t : src.getManufacturerList())
      tgt.getManufacturer().add(convertIngredientManufacturerComponent(t));
    if (src.hasSubstance())
      tgt.setSubstance(convertIngredientSubstanceComponent(src.getSubstance()));
    return tgt;
  }

  public static org.hl7.fhir.model.core.Ingredient.IngredientManufacturerComponent convertIngredientManufacturerComponent(org.hl7.fhir.r5.model.Ingredient.IngredientManufacturerComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.Ingredient.IngredientManufacturerComponent tgt = new org.hl7.fhir.model.core.Ingredient.IngredientManufacturerComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasRole())
      tgt.setRoleElement(convertIngredientManufacturerRole(src.getRoleElement()));
    if (src.hasManufacturer())
      tgt.setManufacturer(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getManufacturer()));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.Ingredient.IngredientManufacturerComponent convertIngredientManufacturerComponent(org.hl7.fhir.model.core.Ingredient.IngredientManufacturerComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.Ingredient.IngredientManufacturerComponent tgt = new org.hl7.fhir.r5.model.Ingredient.IngredientManufacturerComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasRole())
      tgt.setRoleElement(convertIngredientManufacturerRole(src.getRoleElement()));
    if (src.hasManufacturer())
      tgt.setManufacturer(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getManufacturer()));
    return tgt;
  }

  public static org.hl7.fhir.model.core.Ingredient.IngredientSubstanceComponent convertIngredientSubstanceComponent(org.hl7.fhir.r5.model.Ingredient.IngredientSubstanceComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.Ingredient.IngredientSubstanceComponent tgt = new org.hl7.fhir.model.core.Ingredient.IngredientSubstanceComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasCode())
      tgt.setCode(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(src.getCode()));
    for (org.hl7.fhir.r5.model.Ingredient.IngredientSubstanceStrengthComponent t : src.getStrength())
      tgt.getStrengthList().add(convertIngredientSubstanceStrengthComponent(t));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.Ingredient.IngredientSubstanceComponent convertIngredientSubstanceComponent(org.hl7.fhir.model.core.Ingredient.IngredientSubstanceComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.Ingredient.IngredientSubstanceComponent tgt = new org.hl7.fhir.r5.model.Ingredient.IngredientSubstanceComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasCode())
      tgt.setCode(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(src.getCode()));
    for (org.hl7.fhir.model.core.Ingredient.IngredientSubstanceStrengthComponent t : src.getStrengthList())
      tgt.getStrength().add(convertIngredientSubstanceStrengthComponent(t));
    return tgt;
  }

  public static org.hl7.fhir.model.core.Ingredient.IngredientSubstanceStrengthComponent convertIngredientSubstanceStrengthComponent(org.hl7.fhir.r5.model.Ingredient.IngredientSubstanceStrengthComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.Ingredient.IngredientSubstanceStrengthComponent tgt = new org.hl7.fhir.model.core.Ingredient.IngredientSubstanceStrengthComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasPresentation())
      tgt.setPresentation(ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().convertType(src.getPresentation()));
    if (src.hasTextPresentation())
      tgt.setTextPresentationElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getTextPresentationElement()));
    if (src.hasConcentration())
      tgt.setConcentration(ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().convertType(src.getConcentration()));
    if (src.hasTextConcentration())
      tgt.setTextConcentrationElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getTextConcentrationElement()));
    if (src.hasBasis())
      tgt.setBasis(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getBasis()));
    if (src.hasMeasurementPoint())
      tgt.setMeasurementPointElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getMeasurementPointElement()));
    for (org.hl7.fhir.r5.model.CodeableConcept t : src.getCountry())
      tgt.getCountryList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    for (org.hl7.fhir.r5.model.Ingredient.IngredientSubstanceStrengthReferenceStrengthComponent t : src.getReferenceStrength())
      tgt.getReferenceStrengthList().add(convertIngredientSubstanceStrengthReferenceStrengthComponent(t));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.Ingredient.IngredientSubstanceStrengthComponent convertIngredientSubstanceStrengthComponent(org.hl7.fhir.model.core.Ingredient.IngredientSubstanceStrengthComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.Ingredient.IngredientSubstanceStrengthComponent tgt = new org.hl7.fhir.r5.model.Ingredient.IngredientSubstanceStrengthComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasPresentation())
      tgt.setPresentation(ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().convertType(src.getPresentation()));
    if (src.hasTextPresentation())
      tgt.setTextPresentationElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getTextPresentationElement()));
    if (src.hasConcentration())
      tgt.setConcentration(ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().convertType(src.getConcentration()));
    if (src.hasTextConcentration())
      tgt.setTextConcentrationElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getTextConcentrationElement()));
    if (src.hasBasis())
      tgt.setBasis(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getBasis()));
    if (src.hasMeasurementPoint())
      tgt.setMeasurementPointElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getMeasurementPointElement()));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getCountryList())
      tgt.getCountry().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    for (org.hl7.fhir.model.core.Ingredient.IngredientSubstanceStrengthReferenceStrengthComponent t : src.getReferenceStrengthList())
      tgt.getReferenceStrength().add(convertIngredientSubstanceStrengthReferenceStrengthComponent(t));
    return tgt;
  }

  public static org.hl7.fhir.model.core.Ingredient.IngredientSubstanceStrengthReferenceStrengthComponent convertIngredientSubstanceStrengthReferenceStrengthComponent(org.hl7.fhir.r5.model.Ingredient.IngredientSubstanceStrengthReferenceStrengthComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.Ingredient.IngredientSubstanceStrengthReferenceStrengthComponent tgt = new org.hl7.fhir.model.core.Ingredient.IngredientSubstanceStrengthReferenceStrengthComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasSubstance())
      tgt.setSubstance(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(src.getSubstance()));
    if (src.hasStrength())
      tgt.setStrength(ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().convertType(src.getStrength()));
    if (src.hasMeasurementPoint())
      tgt.setMeasurementPointElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getMeasurementPointElement()));
    for (org.hl7.fhir.r5.model.CodeableConcept t : src.getCountry())
      tgt.getCountryList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.Ingredient.IngredientSubstanceStrengthReferenceStrengthComponent convertIngredientSubstanceStrengthReferenceStrengthComponent(org.hl7.fhir.model.core.Ingredient.IngredientSubstanceStrengthReferenceStrengthComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.Ingredient.IngredientSubstanceStrengthReferenceStrengthComponent tgt = new org.hl7.fhir.r5.model.Ingredient.IngredientSubstanceStrengthReferenceStrengthComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasSubstance())
      tgt.setSubstance(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(src.getSubstance()));
    if (src.hasStrength())
      tgt.setStrength(ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().convertType(src.getStrength()));
    if (src.hasMeasurementPoint())
      tgt.setMeasurementPointElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getMeasurementPointElement()));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getCountryList())
      tgt.getCountry().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    return tgt;
  }

  static public org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.Ingredient.IngredientManufacturerRole> convertIngredientManufacturerRole(org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.Ingredient.IngredientManufacturerRole> src) throws FHIRException {
    if (src == null || src.isEmpty())
      return null;
    org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.Ingredient.IngredientManufacturerRole> tgt = new org.hl7.fhir.model.core.Enumeration<>(new org.hl7.fhir.model.core.Ingredient.IngredientManufacturerRoleEnumFactory());
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyElement(src, tgt);
    if (src.getValue() == null) {
      tgt.setValue(null);
    } else {
      switch (src.getValue()) {
        case ALLOWED:
          tgt.setValue(org.hl7.fhir.model.core.Ingredient.IngredientManufacturerRole.ALLOWED);
          break;
        case POSSIBLE:
          tgt.setValue(org.hl7.fhir.model.core.Ingredient.IngredientManufacturerRole.POSSIBLE);
          break;
        case ACTUAL:
          tgt.setValue(org.hl7.fhir.model.core.Ingredient.IngredientManufacturerRole.ACTUAL);
          break;
        default:
          tgt.setValue(org.hl7.fhir.model.core.Ingredient.IngredientManufacturerRole.NULL);
          break;
      }
    }
    return tgt;
  }

  static public org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.Ingredient.IngredientManufacturerRole> convertIngredientManufacturerRole(org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.Ingredient.IngredientManufacturerRole> src) throws FHIRException {
    if (src == null || src.isEmpty())
      return null;
    org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.Ingredient.IngredientManufacturerRole> tgt = new org.hl7.fhir.r5.model.Enumeration<>(new org.hl7.fhir.r5.model.Ingredient.IngredientManufacturerRoleEnumFactory());
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyElement(src, tgt);
    if (src.getValue() == null) {
      tgt.setValue(null);
    } else {
      switch (src.getValue()) {
        case ALLOWED:
          tgt.setValue(org.hl7.fhir.r5.model.Ingredient.IngredientManufacturerRole.ALLOWED);
          break;
        case POSSIBLE:
          tgt.setValue(org.hl7.fhir.r5.model.Ingredient.IngredientManufacturerRole.POSSIBLE);
          break;
        case ACTUAL:
          tgt.setValue(org.hl7.fhir.r5.model.Ingredient.IngredientManufacturerRole.ACTUAL);
          break;
        default:
          tgt.setValue(org.hl7.fhir.r5.model.Ingredient.IngredientManufacturerRole.NULL);
          break;
      }
    }
    return tgt;
  }

}
