package org.hl7.fhir.convertors.conv50_N.resources50_N;

import org.hl7.fhir.convertors.context.ConversionContext50_N;
import org.hl7.fhir.exceptions.FHIRException;
import org.hl7.fhir.r5.model.Availability;

// generated by the converter generator: R5 <-> R6 (6.0.0-ballot5)
// the R5 side is asserted from the R6 definitions - compile errors mark real version differences

public class Location50_N {

  // Location.code is new in R6 - carried in R5 as a cross-version extension
  public static final String CODE_EXTENSION_URL = "http://hl7.org/fhir/6.0/StructureDefinition/extension-Location.code";

  public static org.hl7.fhir.model.core.Location convertLocation(org.hl7.fhir.r5.model.Location src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.Location tgt = new org.hl7.fhir.model.core.Location();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyDomainResource(src, tgt, CODE_EXTENSION_URL);
    for (org.hl7.fhir.r5.model.Identifier t : src.getIdentifier())
      tgt.getIdentifierList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Identifier50_N.convertIdentifier(t));
    if (src.hasStatus())
      tgt.setStatusElement(convertLocationStatus(src.getStatusElement()));
    if (src.hasOperationalStatus())
      tgt.setOperationalStatus(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Coding50_N.convertCoding(src.getOperationalStatus()));
    for (org.hl7.fhir.r5.model.Extension t : src.getExtensionsByUrl(CODE_EXTENSION_URL))
      tgt.getCodeList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept((org.hl7.fhir.r5.model.CodeableConcept) t.getValue()));
    if (src.hasName())
      tgt.setNameElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getNameElement()));
    for (org.hl7.fhir.r5.model.StringType t : src.getAlias())
      tgt.getAliasList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(t));
    if (src.hasDescription())
      tgt.setDescriptionElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getDescriptionElement()));
    if (src.hasMode())
      tgt.setModeElement(convertLocationMode(src.getModeElement()));
    for (org.hl7.fhir.r5.model.CodeableConcept t : src.getType())
      tgt.getTypeList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    for (org.hl7.fhir.r5.model.ExtendedContactDetail t : src.getContact())
      tgt.getContactList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.ExtendedContactDetail50_N.convertExtendedContactDetail(t));
    if (src.hasAddress())
      tgt.setAddress(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Address50_N.convertAddress(src.getAddress()));
    if (src.hasForm())
      tgt.setForm(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getForm()));
    if (src.hasPosition())
      tgt.setPosition(convertLocationPositionComponent(src.getPosition()));
    if (src.hasManagingOrganization())
      tgt.setManagingOrganization(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getManagingOrganization()));
    if (src.hasPartOf())
      tgt.setPartOf(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getPartOf()));
    for (org.hl7.fhir.r5.model.CodeableConcept t : src.getCharacteristic())
      tgt.getCharacteristicList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    for (Availability t : src.getHoursOfOperation())
      tgt.setHoursOfOperation(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.Availability50_N.convertAvailability(t));
    for (org.hl7.fhir.r5.model.VirtualServiceDetail t : src.getVirtualService())
      tgt.getVirtualServiceList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.VirtualServiceDetail50_N.convertVirtualServiceDetail(t));
    for (org.hl7.fhir.r5.model.Reference t : src.getEndpoint())
      tgt.getEndpointList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.Location convertLocation(org.hl7.fhir.model.core.Location src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.Location tgt = new org.hl7.fhir.r5.model.Location();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyDomainResource(src, tgt);
    for (org.hl7.fhir.model.core.Identifier t : src.getIdentifierList())
      tgt.getIdentifier().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Identifier50_N.convertIdentifier(t));
    if (src.hasStatus())
      tgt.setStatusElement(convertLocationStatus(src.getStatusElement()));
    if (src.hasOperationalStatus())
      tgt.setOperationalStatus(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Coding50_N.convertCoding(src.getOperationalStatus()));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getCodeList())
      tgt.addExtension(CODE_EXTENSION_URL, org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    if (src.hasName())
      tgt.setNameElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getNameElement()));
    for (org.hl7.fhir.model.core.StringType t : src.getAliasList())
      tgt.getAlias().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(t));
    if (src.hasDescription())
      tgt.setDescriptionElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getDescriptionElement()));
    if (src.hasMode())
      tgt.setModeElement(convertLocationMode(src.getModeElement()));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getTypeList())
      tgt.getType().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    for (org.hl7.fhir.model.core.ExtendedContactDetail t : src.getContactList())
      tgt.getContact().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.ExtendedContactDetail50_N.convertExtendedContactDetail(t));
    if (src.hasAddress())
      tgt.setAddress(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Address50_N.convertAddress(src.getAddress()));
    if (src.hasForm())
      tgt.setForm(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getForm()));
    if (src.hasPosition())
      tgt.setPosition(convertLocationPositionComponent(src.getPosition()));
    if (src.hasManagingOrganization())
      tgt.setManagingOrganization(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getManagingOrganization()));
    if (src.hasPartOf())
      tgt.setPartOf(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getPartOf()));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getCharacteristicList())
      tgt.getCharacteristic().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    if (src.hasHoursOfOperation())
      tgt.getHoursOfOperation().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.Availability50_N.convertAvailability(src.getHoursOfOperation()));
    for (org.hl7.fhir.model.core.VirtualServiceDetail t : src.getVirtualServiceList())
      tgt.getVirtualService().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.VirtualServiceDetail50_N.convertVirtualServiceDetail(t));
    for (org.hl7.fhir.model.core.Reference t : src.getEndpointList())
      tgt.getEndpoint().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    return tgt;
  }

  public static org.hl7.fhir.model.core.Location.LocationPositionComponent convertLocationPositionComponent(org.hl7.fhir.r5.model.Location.LocationPositionComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.Location.LocationPositionComponent tgt = new org.hl7.fhir.model.core.Location.LocationPositionComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasLongitude())
      tgt.setLongitudeElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Decimal50_N.convertDecimal(src.getLongitudeElement()));
    if (src.hasLatitude())
      tgt.setLatitudeElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Decimal50_N.convertDecimal(src.getLatitudeElement()));
    if (src.hasAltitude())
      tgt.setAltitudeElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Decimal50_N.convertDecimal(src.getAltitudeElement()));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.Location.LocationPositionComponent convertLocationPositionComponent(org.hl7.fhir.model.core.Location.LocationPositionComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.Location.LocationPositionComponent tgt = new org.hl7.fhir.r5.model.Location.LocationPositionComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasLongitude())
      tgt.setLongitudeElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Decimal50_N.convertDecimal(src.getLongitudeElement()));
    if (src.hasLatitude())
      tgt.setLatitudeElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Decimal50_N.convertDecimal(src.getLatitudeElement()));
    if (src.hasAltitude())
      tgt.setAltitudeElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Decimal50_N.convertDecimal(src.getAltitudeElement()));
    return tgt;
  }

  static public org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.Location.LocationMode> convertLocationMode(org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.Location.LocationMode> src) throws FHIRException {
    if (src == null || src.isEmpty())
      return null;
    org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.Location.LocationMode> tgt = new org.hl7.fhir.model.core.Enumeration<>(new org.hl7.fhir.model.core.Location.LocationModeEnumFactory());
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyElement(src, tgt);
    if (src.getValue() == null) {
      tgt.setValue(null);
    } else {
      switch (src.getValue()) {
        case INSTANCE:
          tgt.setValue(org.hl7.fhir.model.core.Location.LocationMode.INSTANCE);
          break;
        case KIND:
          tgt.setValue(org.hl7.fhir.model.core.Location.LocationMode.KIND);
          break;
        default:
          tgt.setValue(org.hl7.fhir.model.core.Location.LocationMode.NULL);
          break;
      }
    }
    return tgt;
  }

  static public org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.Location.LocationMode> convertLocationMode(org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.Location.LocationMode> src) throws FHIRException {
    if (src == null || src.isEmpty())
      return null;
    org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.Location.LocationMode> tgt = new org.hl7.fhir.r5.model.Enumeration<>(new org.hl7.fhir.r5.model.Location.LocationModeEnumFactory());
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyElement(src, tgt);
    if (src.getValue() == null) {
      tgt.setValue(null);
    } else {
      switch (src.getValue()) {
        case INSTANCE:
          tgt.setValue(org.hl7.fhir.r5.model.Location.LocationMode.INSTANCE);
          break;
        case KIND:
          tgt.setValue(org.hl7.fhir.r5.model.Location.LocationMode.KIND);
          break;
        default:
          tgt.setValue(org.hl7.fhir.r5.model.Location.LocationMode.NULL);
          break;
      }
    }
    return tgt;
  }

  static public org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.Location.LocationStatus> convertLocationStatus(org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.Location.LocationStatus> src) throws FHIRException {
    if (src == null || src.isEmpty())
      return null;
    org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.Location.LocationStatus> tgt = new org.hl7.fhir.model.core.Enumeration<>(new org.hl7.fhir.model.core.Location.LocationStatusEnumFactory());
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyElement(src, tgt);
    if (src.getValue() == null) {
      tgt.setValue(null);
    } else {
      switch (src.getValue()) {
        case ACTIVE:
          tgt.setValue(org.hl7.fhir.model.core.Location.LocationStatus.ACTIVE);
          break;
        case SUSPENDED:
          tgt.setValue(org.hl7.fhir.model.core.Location.LocationStatus.SUSPENDED);
          break;
        case INACTIVE:
          tgt.setValue(org.hl7.fhir.model.core.Location.LocationStatus.INACTIVE);
          break;
        default:
          tgt.setValue(org.hl7.fhir.model.core.Location.LocationStatus.NULL);
          break;
      }
    }
    return tgt;
  }

  static public org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.Location.LocationStatus> convertLocationStatus(org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.Location.LocationStatus> src) throws FHIRException {
    if (src == null || src.isEmpty())
      return null;
    org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.Location.LocationStatus> tgt = new org.hl7.fhir.r5.model.Enumeration<>(new org.hl7.fhir.r5.model.Location.LocationStatusEnumFactory());
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyElement(src, tgt);
    if (src.getValue() == null) {
      tgt.setValue(null);
    } else {
      switch (src.getValue()) {
        case ACTIVE:
          tgt.setValue(org.hl7.fhir.r5.model.Location.LocationStatus.ACTIVE);
          break;
        case SUSPENDED:
          tgt.setValue(org.hl7.fhir.r5.model.Location.LocationStatus.SUSPENDED);
          break;
        case INACTIVE:
          tgt.setValue(org.hl7.fhir.r5.model.Location.LocationStatus.INACTIVE);
          break;
        default:
          tgt.setValue(org.hl7.fhir.r5.model.Location.LocationStatus.NULL);
          break;
      }
    }
    return tgt;
  }

}
