package org.hl7.fhir.convertors.conv50_N.resources50_N;

import org.hl7.fhir.convertors.context.ConversionContext50_N;
import org.hl7.fhir.exceptions.FHIRException;

// generated by the converter generator: R5 <-> R6 (6.0.0-ballot5)
// the R5 side is asserted from the R6 definitions - compile errors mark real version differences

public class MedicinalProductDefinition50_N {

  public static org.hl7.fhir.model.core.MedicinalProductDefinition convertMedicinalProductDefinition(org.hl7.fhir.r5.model.MedicinalProductDefinition src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.MedicinalProductDefinition tgt = new org.hl7.fhir.model.core.MedicinalProductDefinition();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyDomainResource(src, tgt);
    for (org.hl7.fhir.r5.model.Identifier t : src.getIdentifier())
      tgt.getIdentifierList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Identifier50_N.convertIdentifier(t));
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    if (src.hasDomain())
      tgt.setDomain(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getDomain()));
    if (src.hasVersion())
      tgt.setVersionElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getVersionElement()));
    if (src.hasStatus())
      tgt.setStatus(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getStatus()));
    if (src.hasStatusDate())
      tgt.setStatusDateElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.DateTime50_N.convertDateTime(src.getStatusDateElement()));
    if (src.hasDescription())
      tgt.setDescriptionElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getDescriptionElement()));
    if (src.hasCombinedPharmaceuticalDoseForm())
      tgt.setCombinedPharmaceuticalDoseForm(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getCombinedPharmaceuticalDoseForm()));
    for (org.hl7.fhir.r5.model.CodeableConcept t : src.getRoute())
      tgt.getRouteList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    if (src.hasIndication())
      tgt.setIndicationElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getIndicationElement()));
    if (src.hasLegalStatusOfSupply())
      tgt.setLegalStatusOfSupply(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getLegalStatusOfSupply()));
    if (src.hasAdditionalMonitoringIndicator())
      tgt.setAdditionalMonitoringIndicator(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getAdditionalMonitoringIndicator()));
    for (org.hl7.fhir.r5.model.CodeableConcept t : src.getSpecialMeasures())
      tgt.getSpecialMeasuresList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    if (src.hasPediatricUseIndicator())
      tgt.setPediatricUseIndicator(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getPediatricUseIndicator()));
    for (org.hl7.fhir.r5.model.CodeableConcept t : src.getClassification())
      tgt.getClassificationList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    for (org.hl7.fhir.r5.model.MarketingStatus t : src.getMarketingStatus())
      tgt.getMarketingStatusList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.MarketingStatus50_N.convertMarketingStatus(t));
    for (org.hl7.fhir.r5.model.CodeableConcept t : src.getPackagedMedicinalProduct())
      tgt.getPackagedMedicinalProductList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    for (org.hl7.fhir.r5.model.Reference t : src.getComprisedOf())
      tgt.getComprisedOfList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    for (org.hl7.fhir.r5.model.CodeableConcept t : src.getIngredient())
      tgt.getIngredientList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    for (org.hl7.fhir.r5.model.CodeableReference t : src.getImpurity())
      tgt.getImpurityList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(t));
    for (org.hl7.fhir.r5.model.Reference t : src.getAttachedDocument())
      tgt.getAttachedDocumentList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    for (org.hl7.fhir.r5.model.Reference t : src.getMasterFile())
      tgt.getMasterFileList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    for (org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionContactComponent t : src.getContact())
      tgt.getContactList().add(convertMedicinalProductDefinitionContactComponent(t));
    for (org.hl7.fhir.r5.model.Reference t : src.getClinicalTrial())
      tgt.getClinicalTrialList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    for (org.hl7.fhir.r5.model.Coding t : src.getCode())
      tgt.getCodeList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Coding50_N.convertCoding(t));
    for (org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionNameComponent t : src.getName())
      tgt.getNameList().add(convertMedicinalProductDefinitionNameComponent(t));
    for (org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionCrossReferenceComponent t : src.getCrossReference())
      tgt.getCrossReferenceList().add(convertMedicinalProductDefinitionCrossReferenceComponent(t));
    for (org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionOperationComponent t : src.getOperation())
      tgt.getOperationList().add(convertMedicinalProductDefinitionOperationComponent(t));
    for (org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionCharacteristicComponent t : src.getCharacteristic())
      tgt.getCharacteristicList().add(convertMedicinalProductDefinitionCharacteristicComponent(t));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.MedicinalProductDefinition convertMedicinalProductDefinition(org.hl7.fhir.model.core.MedicinalProductDefinition src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.MedicinalProductDefinition tgt = new org.hl7.fhir.r5.model.MedicinalProductDefinition();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyDomainResource(src, tgt);
    for (org.hl7.fhir.model.core.Identifier t : src.getIdentifierList())
      tgt.getIdentifier().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Identifier50_N.convertIdentifier(t));
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    if (src.hasDomain())
      tgt.setDomain(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getDomain()));
    if (src.hasVersion())
      tgt.setVersionElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getVersionElement()));
    if (src.hasStatus())
      tgt.setStatus(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getStatus()));
    if (src.hasStatusDate())
      tgt.setStatusDateElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.DateTime50_N.convertDateTime(src.getStatusDateElement()));
    if (src.hasDescription())
      tgt.setDescriptionElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getDescriptionElement()));
    if (src.hasCombinedPharmaceuticalDoseForm())
      tgt.setCombinedPharmaceuticalDoseForm(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getCombinedPharmaceuticalDoseForm()));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getRouteList())
      tgt.getRoute().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    if (src.hasIndication())
      tgt.setIndicationElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getIndicationElement()));
    if (src.hasLegalStatusOfSupply())
      tgt.setLegalStatusOfSupply(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getLegalStatusOfSupply()));
    if (src.hasAdditionalMonitoringIndicator())
      tgt.setAdditionalMonitoringIndicator(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getAdditionalMonitoringIndicator()));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getSpecialMeasuresList())
      tgt.getSpecialMeasures().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    if (src.hasPediatricUseIndicator())
      tgt.setPediatricUseIndicator(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getPediatricUseIndicator()));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getClassificationList())
      tgt.getClassification().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    for (org.hl7.fhir.model.core.MarketingStatus t : src.getMarketingStatusList())
      tgt.getMarketingStatus().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.MarketingStatus50_N.convertMarketingStatus(t));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getPackagedMedicinalProductList())
      tgt.getPackagedMedicinalProduct().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    for (org.hl7.fhir.model.core.Reference t : src.getComprisedOfList())
      tgt.getComprisedOf().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getIngredientList())
      tgt.getIngredient().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    for (org.hl7.fhir.model.core.CodeableReference t : src.getImpurityList())
      tgt.getImpurity().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(t));
    for (org.hl7.fhir.model.core.Reference t : src.getAttachedDocumentList())
      tgt.getAttachedDocument().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    for (org.hl7.fhir.model.core.Reference t : src.getMasterFileList())
      tgt.getMasterFile().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    for (org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionContactComponent t : src.getContactList())
      tgt.getContact().add(convertMedicinalProductDefinitionContactComponent(t));
    for (org.hl7.fhir.model.core.Reference t : src.getClinicalTrialList())
      tgt.getClinicalTrial().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    for (org.hl7.fhir.model.core.Coding t : src.getCodeList())
      tgt.getCode().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Coding50_N.convertCoding(t));
    for (org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionNameComponent t : src.getNameList())
      tgt.getName().add(convertMedicinalProductDefinitionNameComponent(t));
    for (org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionCrossReferenceComponent t : src.getCrossReferenceList())
      tgt.getCrossReference().add(convertMedicinalProductDefinitionCrossReferenceComponent(t));
    for (org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionOperationComponent t : src.getOperationList())
      tgt.getOperation().add(convertMedicinalProductDefinitionOperationComponent(t));
    for (org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionCharacteristicComponent t : src.getCharacteristicList())
      tgt.getCharacteristic().add(convertMedicinalProductDefinitionCharacteristicComponent(t));
    return tgt;
  }

  public static org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionContactComponent convertMedicinalProductDefinitionContactComponent(org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionContactComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionContactComponent tgt = new org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionContactComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    if (src.hasContact())
      tgt.setContact(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getContact()));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionContactComponent convertMedicinalProductDefinitionContactComponent(org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionContactComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionContactComponent tgt = new org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionContactComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    if (src.hasContact())
      tgt.setContact(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getContact()));
    return tgt;
  }

  public static org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionNameComponent convertMedicinalProductDefinitionNameComponent(org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionNameComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionNameComponent tgt = new org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionNameComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasProductName())
      tgt.setProductNameElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getProductNameElement()));
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    for (org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionNamePartComponent t : src.getPart())
      tgt.getPartList().add(convertMedicinalProductDefinitionNamePartComponent(t));
    for (org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionNameUsageComponent t : src.getUsage())
      tgt.getUsageList().add(convertMedicinalProductDefinitionNameUsageComponent(t));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionNameComponent convertMedicinalProductDefinitionNameComponent(org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionNameComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionNameComponent tgt = new org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionNameComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasProductName())
      tgt.setProductNameElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getProductNameElement()));
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    for (org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionNamePartComponent t : src.getPartList())
      tgt.getPart().add(convertMedicinalProductDefinitionNamePartComponent(t));
    for (org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionNameUsageComponent t : src.getUsageList())
      tgt.getUsage().add(convertMedicinalProductDefinitionNameUsageComponent(t));
    return tgt;
  }

  public static org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionNamePartComponent convertMedicinalProductDefinitionNamePartComponent(org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionNamePartComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionNamePartComponent tgt = new org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionNamePartComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasPart())
      tgt.setPartElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getPartElement()));
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionNamePartComponent convertMedicinalProductDefinitionNamePartComponent(org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionNamePartComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionNamePartComponent tgt = new org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionNamePartComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasPart())
      tgt.setPartElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getPartElement()));
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    return tgt;
  }

  public static org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionNameUsageComponent convertMedicinalProductDefinitionNameUsageComponent(org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionNameUsageComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionNameUsageComponent tgt = new org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionNameUsageComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasCountry())
      tgt.setCountry(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getCountry()));
    if (src.hasJurisdiction())
      tgt.setJurisdiction(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getJurisdiction()));
    if (src.hasLanguage())
      tgt.setLanguage(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getLanguage()));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionNameUsageComponent convertMedicinalProductDefinitionNameUsageComponent(org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionNameUsageComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionNameUsageComponent tgt = new org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionNameUsageComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasCountry())
      tgt.setCountry(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getCountry()));
    if (src.hasJurisdiction())
      tgt.setJurisdiction(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getJurisdiction()));
    if (src.hasLanguage())
      tgt.setLanguage(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getLanguage()));
    return tgt;
  }

  public static org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionCrossReferenceComponent convertMedicinalProductDefinitionCrossReferenceComponent(org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionCrossReferenceComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionCrossReferenceComponent tgt = new org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionCrossReferenceComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasProduct())
      tgt.setProduct(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(src.getProduct()));
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionCrossReferenceComponent convertMedicinalProductDefinitionCrossReferenceComponent(org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionCrossReferenceComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionCrossReferenceComponent tgt = new org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionCrossReferenceComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasProduct())
      tgt.setProduct(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(src.getProduct()));
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    return tgt;
  }

  public static org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionOperationComponent convertMedicinalProductDefinitionOperationComponent(org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionOperationComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionOperationComponent tgt = new org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionOperationComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(src.getType()));
    if (src.hasEffectiveDate())
      tgt.setEffectiveDate(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Period50_N.convertPeriod(src.getEffectiveDate()));
    for (org.hl7.fhir.r5.model.Reference t : src.getOrganization())
      tgt.getOrganizationList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    if (src.hasConfidentialityIndicator())
      tgt.setConfidentialityIndicator(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getConfidentialityIndicator()));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionOperationComponent convertMedicinalProductDefinitionOperationComponent(org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionOperationComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionOperationComponent tgt = new org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionOperationComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(src.getType()));
    if (src.hasEffectiveDate())
      tgt.setEffectiveDate(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Period50_N.convertPeriod(src.getEffectiveDate()));
    for (org.hl7.fhir.model.core.Reference t : src.getOrganizationList())
      tgt.getOrganization().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    if (src.hasConfidentialityIndicator())
      tgt.setConfidentialityIndicator(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getConfidentialityIndicator()));
    return tgt;
  }

  public static org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionCharacteristicComponent convertMedicinalProductDefinitionCharacteristicComponent(org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionCharacteristicComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionCharacteristicComponent tgt = new org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionCharacteristicComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    if (src.hasValue())
      tgt.setValue(ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().convertType(src.getValue()));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionCharacteristicComponent convertMedicinalProductDefinitionCharacteristicComponent(org.hl7.fhir.model.core.MedicinalProductDefinition.MedicinalProductDefinitionCharacteristicComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionCharacteristicComponent tgt = new org.hl7.fhir.r5.model.MedicinalProductDefinition.MedicinalProductDefinitionCharacteristicComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    if (src.hasValue())
      tgt.setValue(ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().convertType(src.getValue()));
    return tgt;
  }

}
