package org.hl7.fhir.convertors.conv50_N.resources50_N;

import org.hl7.fhir.convertors.context.ConversionContext50_N;
import org.hl7.fhir.exceptions.FHIRException;

// generated by the converter generator: R5 <-> R6 (6.0.0-ballot5)
// the R5 side is asserted from the R6 definitions - compile errors mark real version differences

public class NamingSystem50_N {

  public static org.hl7.fhir.model.core.NamingSystem convertNamingSystem(org.hl7.fhir.r5.model.NamingSystem src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.NamingSystem tgt = new org.hl7.fhir.model.core.NamingSystem();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyDomainResource(src, tgt);
    if (src.hasUrl())
      tgt.setUrlElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Uri50_N.convertUri(src.getUrlElement()));
    for (org.hl7.fhir.r5.model.Identifier t : src.getIdentifier())
      tgt.getIdentifierList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Identifier50_N.convertIdentifier(t));
    if (src.hasVersion())
      tgt.setVersionElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getVersionElement()));
    if (src.hasVersionAlgorithm())
      tgt.setVersionAlgorithm(ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().convertType(src.getVersionAlgorithm()));
    if (src.hasName())
      tgt.setNameElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getNameElement()));
    if (src.hasTitle())
      tgt.setTitleElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getTitleElement()));
    if (src.hasStatus())
      tgt.setStatusElement(org.hl7.fhir.convertors.conv50_N.resources50_N.Enumerations50_N.convertPublicationStatus(src.getStatusElement()));
    if (src.hasKind())
      tgt.setKindElement(convertNamingSystemType(src.getKindElement()));
    if (src.hasExperimental())
      tgt.setExperimentalElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Boolean50_N.convertBoolean(src.getExperimentalElement()));
    if (src.hasDate())
      tgt.setDateElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.DateTime50_N.convertDateTime(src.getDateElement()));
    if (src.hasPublisher())
      tgt.setPublisherElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getPublisherElement()));
    for (org.hl7.fhir.r5.model.ContactDetail t : src.getContact())
      tgt.getContactList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.ContactDetail50_N.convertContactDetail(t));
    if (src.hasResponsible())
      tgt.setResponsibleElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getResponsibleElement()));
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    if (src.hasDescription())
      tgt.setDescriptionElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getDescriptionElement()));
    for (org.hl7.fhir.r5.model.UsageContext t : src.getUseContext())
      tgt.getUseContextList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.UsageContext50_N.convertUsageContext(t));
    for (org.hl7.fhir.r5.model.CodeableConcept t : src.getJurisdiction())
      tgt.getJurisdictionList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    if (src.hasPurpose())
      tgt.setPurposeElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getPurposeElement()));
    if (src.hasCopyright())
      tgt.setCopyrightElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getCopyrightElement()));
    if (src.hasCopyrightLabel())
      tgt.setCopyrightLabelElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getCopyrightLabelElement()));
    if (src.hasApprovalDate())
      tgt.setApprovalDateElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Date50_N.convertDate(src.getApprovalDateElement()));
    if (src.hasLastReviewDate())
      tgt.setLastReviewDateElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Date50_N.convertDate(src.getLastReviewDateElement()));
    if (src.hasEffectivePeriod())
      tgt.setEffectivePeriod(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Period50_N.convertPeriod(src.getEffectivePeriod()));
    for (org.hl7.fhir.r5.model.CodeableConcept t : src.getTopic())
      tgt.getTopicList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    for (org.hl7.fhir.r5.model.ContactDetail t : src.getAuthor())
      tgt.getAuthorList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.ContactDetail50_N.convertContactDetail(t));
    for (org.hl7.fhir.r5.model.ContactDetail t : src.getEditor())
      tgt.getEditorList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.ContactDetail50_N.convertContactDetail(t));
    for (org.hl7.fhir.r5.model.ContactDetail t : src.getReviewer())
      tgt.getReviewerList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.ContactDetail50_N.convertContactDetail(t));
    for (org.hl7.fhir.r5.model.ContactDetail t : src.getEndorser())
      tgt.getEndorserList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.ContactDetail50_N.convertContactDetail(t));
    for (org.hl7.fhir.r5.model.RelatedArtifact t : src.getRelatedArtifact())
      tgt.getRelatedArtifactList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.RelatedArtifact50_N.convertRelatedArtifact(t));
    if (src.hasUsage())
      tgt.setUsageElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertStringToMarkDown(src.getUsageElement()));
    for (org.hl7.fhir.r5.model.NamingSystem.NamingSystemUniqueIdComponent t : src.getUniqueId())
      tgt.getUniqueIdList().add(convertNamingSystemUniqueIdComponent(t));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.NamingSystem convertNamingSystem(org.hl7.fhir.model.core.NamingSystem src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.NamingSystem tgt = new org.hl7.fhir.r5.model.NamingSystem();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyDomainResource(src, tgt);
    if (src.hasUrl())
      tgt.setUrlElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Uri50_N.convertUri(src.getUrlElement()));
    for (org.hl7.fhir.model.core.Identifier t : src.getIdentifierList())
      tgt.getIdentifier().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Identifier50_N.convertIdentifier(t));
    if (src.hasVersion())
      tgt.setVersionElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getVersionElement()));
    if (src.hasVersionAlgorithm())
      tgt.setVersionAlgorithm(ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().convertType(src.getVersionAlgorithm()));
    if (src.hasName())
      tgt.setNameElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getNameElement()));
    if (src.hasTitle())
      tgt.setTitleElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getTitleElement()));
    if (src.hasStatus())
      tgt.setStatusElement(org.hl7.fhir.convertors.conv50_N.resources50_N.Enumerations50_N.convertPublicationStatus(src.getStatusElement()));
    if (src.hasKind())
      tgt.setKindElement(convertNamingSystemType(src.getKindElement()));
    if (src.hasExperimental())
      tgt.setExperimentalElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Boolean50_N.convertBoolean(src.getExperimentalElement()));
    if (src.hasDate())
      tgt.setDateElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.DateTime50_N.convertDateTime(src.getDateElement()));
    if (src.hasPublisher())
      tgt.setPublisherElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getPublisherElement()));
    for (org.hl7.fhir.model.core.ContactDetail t : src.getContactList())
      tgt.getContact().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.ContactDetail50_N.convertContactDetail(t));
    if (src.hasResponsible())
      tgt.setResponsibleElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getResponsibleElement()));
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    if (src.hasDescription())
      tgt.setDescriptionElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getDescriptionElement()));
    for (org.hl7.fhir.model.core.UsageContext t : src.getUseContextList())
      tgt.getUseContext().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.UsageContext50_N.convertUsageContext(t));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getJurisdictionList())
      tgt.getJurisdiction().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    if (src.hasPurpose())
      tgt.setPurposeElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getPurposeElement()));
    if (src.hasCopyright())
      tgt.setCopyrightElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getCopyrightElement()));
    if (src.hasCopyrightLabel())
      tgt.setCopyrightLabelElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getCopyrightLabelElement()));
    if (src.hasApprovalDate())
      tgt.setApprovalDateElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Date50_N.convertDate(src.getApprovalDateElement()));
    if (src.hasLastReviewDate())
      tgt.setLastReviewDateElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Date50_N.convertDate(src.getLastReviewDateElement()));
    if (src.hasEffectivePeriod())
      tgt.setEffectivePeriod(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Period50_N.convertPeriod(src.getEffectivePeriod()));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getTopicList())
      tgt.getTopic().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    for (org.hl7.fhir.model.core.ContactDetail t : src.getAuthorList())
      tgt.getAuthor().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.ContactDetail50_N.convertContactDetail(t));
    for (org.hl7.fhir.model.core.ContactDetail t : src.getEditorList())
      tgt.getEditor().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.ContactDetail50_N.convertContactDetail(t));
    for (org.hl7.fhir.model.core.ContactDetail t : src.getReviewerList())
      tgt.getReviewer().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.ContactDetail50_N.convertContactDetail(t));
    for (org.hl7.fhir.model.core.ContactDetail t : src.getEndorserList())
      tgt.getEndorser().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.ContactDetail50_N.convertContactDetail(t));
    for (org.hl7.fhir.model.core.RelatedArtifact t : src.getRelatedArtifactList())
      tgt.getRelatedArtifact().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.metadata50_N.RelatedArtifact50_N.convertRelatedArtifact(t));
    if (src.hasUsage())
      tgt.setUsageElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getUsageElement()));
    for (org.hl7.fhir.model.core.NamingSystem.NamingSystemUniqueIdComponent t : src.getUniqueIdList())
      tgt.getUniqueId().add(convertNamingSystemUniqueIdComponent(t));
    return tgt;
  }

  public static org.hl7.fhir.model.core.NamingSystem.NamingSystemUniqueIdComponent convertNamingSystemUniqueIdComponent(org.hl7.fhir.r5.model.NamingSystem.NamingSystemUniqueIdComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.NamingSystem.NamingSystemUniqueIdComponent tgt = new org.hl7.fhir.model.core.NamingSystem.NamingSystemUniqueIdComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasType())
      tgt.setTypeElement(convertNamingSystemIdentifierType(src.getTypeElement()));
    if (src.hasValue())
      tgt.setValueElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getValueElement()));
    if (src.hasPreferred())
      tgt.setPreferredElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Boolean50_N.convertBoolean(src.getPreferredElement()));
    if (src.hasComment())
      tgt.setCommentElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getCommentElement()));
    if (src.hasPeriod())
      tgt.setPeriod(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Period50_N.convertPeriod(src.getPeriod()));
    if (src.hasAuthoritative())
      tgt.setAuthoritativeElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Boolean50_N.convertBoolean(src.getAuthoritativeElement()));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.NamingSystem.NamingSystemUniqueIdComponent convertNamingSystemUniqueIdComponent(org.hl7.fhir.model.core.NamingSystem.NamingSystemUniqueIdComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.NamingSystem.NamingSystemUniqueIdComponent tgt = new org.hl7.fhir.r5.model.NamingSystem.NamingSystemUniqueIdComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasType())
      tgt.setTypeElement(convertNamingSystemIdentifierType(src.getTypeElement()));
    if (src.hasValue())
      tgt.setValueElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getValueElement()));
    if (src.hasPreferred())
      tgt.setPreferredElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Boolean50_N.convertBoolean(src.getPreferredElement()));
    if (src.hasComment())
      tgt.setCommentElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.String50_N.convertString(src.getCommentElement()));
    if (src.hasPeriod())
      tgt.setPeriod(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Period50_N.convertPeriod(src.getPeriod()));
    if (src.hasAuthoritative())
      tgt.setAuthoritativeElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Boolean50_N.convertBoolean(src.getAuthoritativeElement()));
    return tgt;
  }

  static public org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.NamingSystem.NamingSystemIdentifierType> convertNamingSystemIdentifierType(org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.NamingSystem.NamingSystemIdentifierType> src) throws FHIRException {
    if (src == null || src.isEmpty())
      return null;
    org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.NamingSystem.NamingSystemIdentifierType> tgt = new org.hl7.fhir.model.core.Enumeration<>(new org.hl7.fhir.model.core.NamingSystem.NamingSystemIdentifierTypeEnumFactory());
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyElement(src, tgt);
    if (src.getValue() == null) {
      tgt.setValue(null);
    } else {
      switch (src.getValue()) {
        case OID:
          tgt.setValue(org.hl7.fhir.model.core.NamingSystem.NamingSystemIdentifierType.OID);
          break;
        case UUID:
          tgt.setValue(org.hl7.fhir.model.core.NamingSystem.NamingSystemIdentifierType.UUID);
          break;
        case URI:
          tgt.setValue(org.hl7.fhir.model.core.NamingSystem.NamingSystemIdentifierType.URI);
          break;
        case IRISTEM:
          tgt.setValue(org.hl7.fhir.model.core.NamingSystem.NamingSystemIdentifierType.IRISTEM);
          break;
        case V2CSMNEMONIC:
          tgt.setValue(org.hl7.fhir.model.core.NamingSystem.NamingSystemIdentifierType.V2CSMNEMONIC);
          break;
        case OTHER:
          tgt.setValue(org.hl7.fhir.model.core.NamingSystem.NamingSystemIdentifierType.OTHER);
          break;
        default:
          tgt.setValue(org.hl7.fhir.model.core.NamingSystem.NamingSystemIdentifierType.NULL);
          break;
      }
    }
    return tgt;
  }

  static public org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.NamingSystem.NamingSystemIdentifierType> convertNamingSystemIdentifierType(org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.NamingSystem.NamingSystemIdentifierType> src) throws FHIRException {
    if (src == null || src.isEmpty())
      return null;
    org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.NamingSystem.NamingSystemIdentifierType> tgt = new org.hl7.fhir.r5.model.Enumeration<>(new org.hl7.fhir.r5.model.NamingSystem.NamingSystemIdentifierTypeEnumFactory());
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyElement(src, tgt);
    if (src.getValue() == null) {
      tgt.setValue(null);
    } else {
      switch (src.getValue()) {
        case OID:
          tgt.setValue(org.hl7.fhir.r5.model.NamingSystem.NamingSystemIdentifierType.OID);
          break;
        case UUID:
          tgt.setValue(org.hl7.fhir.r5.model.NamingSystem.NamingSystemIdentifierType.UUID);
          break;
        case URI:
          tgt.setValue(org.hl7.fhir.r5.model.NamingSystem.NamingSystemIdentifierType.URI);
          break;
        case IRISTEM:
          tgt.setValue(org.hl7.fhir.r5.model.NamingSystem.NamingSystemIdentifierType.IRISTEM);
          break;
        case V2CSMNEMONIC:
          tgt.setValue(org.hl7.fhir.r5.model.NamingSystem.NamingSystemIdentifierType.V2CSMNEMONIC);
          break;
        case OTHER:
          tgt.setValue(org.hl7.fhir.r5.model.NamingSystem.NamingSystemIdentifierType.OTHER);
          break;
        default:
          tgt.setValue(org.hl7.fhir.r5.model.NamingSystem.NamingSystemIdentifierType.NULL);
          break;
      }
    }
    return tgt;
  }

  static public org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.NamingSystem.NamingSystemType> convertNamingSystemType(org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.NamingSystem.NamingSystemType> src) throws FHIRException {
    if (src == null || src.isEmpty())
      return null;
    org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.NamingSystem.NamingSystemType> tgt = new org.hl7.fhir.model.core.Enumeration<>(new org.hl7.fhir.model.core.NamingSystem.NamingSystemTypeEnumFactory());
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyElement(src, tgt);
    if (src.getValue() == null) {
      tgt.setValue(null);
    } else {
      switch (src.getValue()) {
        case CODESYSTEM:
          tgt.setValue(org.hl7.fhir.model.core.NamingSystem.NamingSystemType.CODESYSTEM);
          break;
        case IDENTIFIER:
          tgt.setValue(org.hl7.fhir.model.core.NamingSystem.NamingSystemType.IDENTIFIER);
          break;
        case ROOT:
          tgt.setValue(org.hl7.fhir.model.core.NamingSystem.NamingSystemType.ROOT);
          break;
        default:
          tgt.setValue(org.hl7.fhir.model.core.NamingSystem.NamingSystemType.NULL);
          break;
      }
    }
    return tgt;
  }

  static public org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.NamingSystem.NamingSystemType> convertNamingSystemType(org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.NamingSystem.NamingSystemType> src) throws FHIRException {
    if (src == null || src.isEmpty())
      return null;
    org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.NamingSystem.NamingSystemType> tgt = new org.hl7.fhir.r5.model.Enumeration<>(new org.hl7.fhir.r5.model.NamingSystem.NamingSystemTypeEnumFactory());
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyElement(src, tgt);
    if (src.getValue() == null) {
      tgt.setValue(null);
    } else {
      switch (src.getValue()) {
        case CODESYSTEM:
          tgt.setValue(org.hl7.fhir.r5.model.NamingSystem.NamingSystemType.CODESYSTEM);
          break;
        case IDENTIFIER:
          tgt.setValue(org.hl7.fhir.r5.model.NamingSystem.NamingSystemType.IDENTIFIER);
          break;
        case ROOT:
          tgt.setValue(org.hl7.fhir.r5.model.NamingSystem.NamingSystemType.ROOT);
          break;
        default:
          tgt.setValue(org.hl7.fhir.r5.model.NamingSystem.NamingSystemType.NULL);
          break;
      }
    }
    return tgt;
  }

}
