package org.hl7.fhir.convertors.conv50_N.resources50_N;

import org.hl7.fhir.convertors.context.ConversionContext50_N;
import org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.SimpleQuantity50_N;
import org.hl7.fhir.exceptions.FHIRException;
import org.hl7.fhir.r5.model.NutritionIntake;

// generated by the converter generator: R5 <-> R6 (6.0.0-ballot5)
// the R5 side is asserted from the R6 definitions - compile errors mark real version differences

public class NutritionIntake50_N {

  // the instantiates elements were removed in R6 - carried in R6 as cross-version extensions
  public static final String INSTANTIATES_CANONICAL_EXTENSION_URL = "http://hl7.org/fhir/5.0/StructureDefinition/extension-NutritionIntake.instantiatesCanonical";
  public static final String INSTANTIATES_URI_EXTENSION_URL = "http://hl7.org/fhir/5.0/StructureDefinition/extension-NutritionIntake.instantiatesUri";
  // nutritionItem.consumedItem.totalIntake is new in R6 - carried on the R5 consumedItem as a complex cross-version extension
  public static final String TOTAL_INTAKE_EXTENSION_URL = "http://hl7.org/fhir/6.0/StructureDefinition/extension-NutritionIntake.nutritionItem.consumedItem.totalIntake";

  public static org.hl7.fhir.model.core.NutritionIntake convertNutritionIntake(org.hl7.fhir.r5.model.NutritionIntake src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.NutritionIntake tgt = new org.hl7.fhir.model.core.NutritionIntake();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyDomainResource(src, tgt);
    for (org.hl7.fhir.r5.model.CanonicalType t : src.getInstantiatesCanonical())
      tgt.addExtension(INSTANTIATES_CANONICAL_EXTENSION_URL, org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Canonical50_N.convertCanonical(t));
    for (org.hl7.fhir.r5.model.UriType t : src.getInstantiatesUri())
      tgt.addExtension(INSTANTIATES_URI_EXTENSION_URL, org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Uri50_N.convertUri(t));
    for (org.hl7.fhir.r5.model.Identifier t : src.getIdentifier())
      tgt.getIdentifierList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Identifier50_N.convertIdentifier(t));
    for (org.hl7.fhir.r5.model.Reference t : src.getBasedOn())
      tgt.getBasedOnList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    for (org.hl7.fhir.r5.model.Reference t : src.getPartOf())
      tgt.getPartOfList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    if (src.hasStatus())
      tgt.setStatusElement(org.hl7.fhir.convertors.conv50_N.resources50_N.Enumerations50_N.convertEventStatus(src.getStatusElement()));
    for (org.hl7.fhir.r5.model.CodeableConcept t : src.getStatusReason())
      tgt.getStatusReasonList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    if (src.hasCode())
      tgt.setCode(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getCode()));
    if (src.hasSubject())
      tgt.setSubject(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getSubject()));
    if (src.hasEncounter())
      tgt.setEncounter(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getEncounter()));
    if (src.hasOccurrence())
      tgt.setOccurrence(ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().convertType(src.getOccurrence()));
    if (src.hasRecorded())
      tgt.setRecordedElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.DateTime50_N.convertDateTime(src.getRecordedElement()));
    if (src.hasReported())
      tgt.setReported(ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().convertType(src.getReported()));
    for (NutritionIntake.NutritionIntakeConsumedItemComponent t : src.getConsumedItem())
      tgt.getNutritionItemList().add(convertNutritionIntakeNutritionItemComponent(t));
    for (org.hl7.fhir.r5.model.NutritionIntake.NutritionIntakePerformerComponent t : src.getPerformer())
      tgt.getPerformerList().add(convertNutritionIntakePerformerComponent(t));
    if (src.hasLocation())
      tgt.setLocation(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getLocation()));
    for (org.hl7.fhir.r5.model.Reference t : src.getDerivedFrom())
      tgt.getDerivedFromList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    for (org.hl7.fhir.r5.model.CodeableReference t : src.getReason())
      tgt.getReasonList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(t));
    for (org.hl7.fhir.r5.model.Annotation t : src.getNote())
      tgt.getNoteList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Annotation50_N.convertAnnotation(t));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.NutritionIntake convertNutritionIntake(org.hl7.fhir.model.core.NutritionIntake src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.NutritionIntake tgt = new org.hl7.fhir.r5.model.NutritionIntake();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyDomainResource(src, tgt, INSTANTIATES_CANONICAL_EXTENSION_URL, INSTANTIATES_URI_EXTENSION_URL);
    for (org.hl7.fhir.model.core.Extension t : src.getExtensionsByUrl(INSTANTIATES_CANONICAL_EXTENSION_URL))
      tgt.getInstantiatesCanonical().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Canonical50_N.convertCanonical((org.hl7.fhir.model.core.CanonicalType) t.getValue()));
    for (org.hl7.fhir.model.core.Extension t : src.getExtensionsByUrl(INSTANTIATES_URI_EXTENSION_URL))
      tgt.getInstantiatesUri().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Uri50_N.convertUri((org.hl7.fhir.model.core.UriType) t.getValue()));
    for (org.hl7.fhir.model.core.Identifier t : src.getIdentifierList())
      tgt.getIdentifier().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Identifier50_N.convertIdentifier(t));
    for (org.hl7.fhir.model.core.Reference t : src.getBasedOnList())
      tgt.getBasedOn().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    for (org.hl7.fhir.model.core.Reference t : src.getPartOfList())
      tgt.getPartOf().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    if (src.hasStatus())
      tgt.setStatusElement(org.hl7.fhir.convertors.conv50_N.resources50_N.Enumerations50_N.convertEventStatus(src.getStatusElement()));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getStatusReasonList())
      tgt.getStatusReason().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    if (src.hasCode())
      tgt.setCode(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getCode()));
    if (src.hasSubject())
      tgt.setSubject(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getSubject()));
    if (src.hasEncounter())
      tgt.setEncounter(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getEncounter()));
    if (src.hasOccurrence())
      tgt.setOccurrence(ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().convertType(src.getOccurrence()));
    if (src.hasRecorded())
      tgt.setRecordedElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.DateTime50_N.convertDateTime(src.getRecordedElement()));
    if (src.hasReported())
      tgt.setReported(ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().convertType(src.getReported()));
    for (org.hl7.fhir.model.core.NutritionIntake.NutritionIntakeNutritionItemComponent t : src.getNutritionItemList())
      tgt.getConsumedItem().add(convertNutritionIntakeNutritionItemComponent(t));
    for (org.hl7.fhir.model.core.NutritionIntake.NutritionIntakePerformerComponent t : src.getPerformerList())
      tgt.getPerformer().add(convertNutritionIntakePerformerComponent(t));
    if (src.hasLocation())
      tgt.setLocation(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getLocation()));
    for (org.hl7.fhir.model.core.Reference t : src.getDerivedFromList())
      tgt.getDerivedFrom().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    for (org.hl7.fhir.model.core.CodeableReference t : src.getReasonList())
      tgt.getReason().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(t));
    for (org.hl7.fhir.model.core.Annotation t : src.getNoteList())
      tgt.getNote().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Annotation50_N.convertAnnotation(t));
    return tgt;
  }

  public static org.hl7.fhir.model.core.NutritionIntake.NutritionIntakeNutritionItemComponent convertNutritionIntakeNutritionItemComponent(org.hl7.fhir.r5.model.NutritionIntake.NutritionIntakeConsumedItemComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.NutritionIntake.NutritionIntakeNutritionItemComponent tgt = new org.hl7.fhir.model.core.NutritionIntake.NutritionIntakeNutritionItemComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt, TOTAL_INTAKE_EXTENSION_URL);
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    if (src.hasNutritionProduct())
      tgt.setNutritionProduct(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(src.getNutritionProduct()));
    if (src.getNotConsumed()) {
      org.hl7.fhir.model.core.NutritionIntake.NutritionIntakeNutritionItemNotConsumedItemComponent tgtT = tgt.addNotConsumedItem();
      if (src.hasNotConsumedReason())
        tgtT.setReason(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getNotConsumedReason()));
      if (src.hasSchedule())
        tgtT.setSchedule(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Timing50_N.convertTiming(src.getSchedule()));
      if (src.hasAmount())
        tgtT.setAmount(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Quantity50_N.convertQuantity(src.getAmount()));
    } else {
      org.hl7.fhir.model.core.NutritionIntake.NutritionIntakeNutritionItemConsumedItemComponent tgtT = tgt.addConsumedItem();
      if (src.hasSchedule())
        tgtT.setSchedule(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Timing50_N.convertTiming(src.getSchedule()));
      if (src.hasAmount())
        tgtT.setAmount(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Quantity50_N.convertQuantity(src.getAmount()));
      if (src.hasRate())
        tgtT.setRate(ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().convertType(src.getRate()));
      for (org.hl7.fhir.r5.model.Extension t : src.getExtensionsByUrl(TOTAL_INTAKE_EXTENSION_URL)) {
        org.hl7.fhir.model.core.NutritionIntake.NutritionIntakeNutritionItemConsumedItemTotalIntakeComponent ti = tgtT.addTotalIntake();
        if (t.hasExtension("nutrient"))
          ti.setNutrient(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference((org.hl7.fhir.r5.model.CodeableReference) t.getExtensionByUrl("nutrient").getValue()));
        if (t.hasExtension("amount"))
          ti.setAmount(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Quantity50_N.convertQuantity((org.hl7.fhir.r5.model.Quantity) t.getExtensionByUrl("amount").getValue()));
        if (t.hasExtension("energy"))
          ti.setEnergy(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Quantity50_N.convertQuantity((org.hl7.fhir.r5.model.Quantity) t.getExtensionByUrl("energy").getValue()));
      }
    }
    return tgt;
  }

  public static org.hl7.fhir.r5.model.NutritionIntake.NutritionIntakeConsumedItemComponent convertNutritionIntakeNutritionItemComponent(org.hl7.fhir.model.core.NutritionIntake.NutritionIntakeNutritionItemComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.NutritionIntake.NutritionIntakeConsumedItemComponent tgt = new org.hl7.fhir.r5.model.NutritionIntake.NutritionIntakeConsumedItemComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasType())
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    if (src.hasNutritionProduct())
      tgt.setNutritionProduct(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(src.getNutritionProduct()));
    if (src.hasConsumedItem()) {
      if (src.getConsumedItemFirstRep().hasSchedule())
        tgt.setSchedule(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Timing50_N.convertTiming(src.getConsumedItemFirstRep().getSchedule()));
      if (src.getConsumedItemFirstRep().hasAmount())
        tgt.setAmount(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Quantity50_N.convertQuantity(src.getConsumedItemFirstRep().getAmount()));
      if (src.getConsumedItemFirstRep().hasRateQuantity())
        tgt.setRate(SimpleQuantity50_N.convertSimpleQuantity(src.getConsumedItemFirstRep().getRateQuantity()));
      for (org.hl7.fhir.model.core.NutritionIntake.NutritionIntakeNutritionItemConsumedItemTotalIntakeComponent t : src.getConsumedItemFirstRep().getTotalIntakeList()) {
        org.hl7.fhir.r5.model.Extension ext = new org.hl7.fhir.r5.model.Extension(TOTAL_INTAKE_EXTENSION_URL);
        if (t.hasNutrient())
          ext.addExtension("nutrient", org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(t.getNutrient()));
        if (t.hasAmount())
          ext.addExtension("amount", org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Quantity50_N.convertQuantity(t.getAmount()));
        if (t.hasEnergy())
          ext.addExtension("energy", org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Quantity50_N.convertQuantity(t.getEnergy()));
        tgt.addExtension(ext);
      }
    }
    if (src.hasNotConsumedItem()) {
      tgt.setNotConsumed(true);
      if (src.getNotConsumedItemFirstRep().hasReason())
        tgt.setNotConsumedReason(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getNotConsumedItemFirstRep().getReason()));
      if (src.getNotConsumedItemFirstRep().hasSchedule())
        tgt.setSchedule(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Timing50_N.convertTiming(src.getNotConsumedItemFirstRep().getSchedule()));
      if (src.getNotConsumedItemFirstRep().hasAmount())
        tgt.setAmount(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Quantity50_N.convertQuantity(src.getNotConsumedItemFirstRep().getAmount()));
    }
    return tgt;
  }

  public static org.hl7.fhir.model.core.NutritionIntake.NutritionIntakePerformerComponent convertNutritionIntakePerformerComponent(org.hl7.fhir.r5.model.NutritionIntake.NutritionIntakePerformerComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.NutritionIntake.NutritionIntakePerformerComponent tgt = new org.hl7.fhir.model.core.NutritionIntake.NutritionIntakePerformerComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasFunction())
      tgt.setFunction(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getFunction()));
    if (src.hasActor())
      tgt.setActor(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getActor()));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.NutritionIntake.NutritionIntakePerformerComponent convertNutritionIntakePerformerComponent(org.hl7.fhir.model.core.NutritionIntake.NutritionIntakePerformerComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.NutritionIntake.NutritionIntakePerformerComponent tgt = new org.hl7.fhir.r5.model.NutritionIntake.NutritionIntakePerformerComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasFunction())
      tgt.setFunction(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getFunction()));
    if (src.hasActor())
      tgt.setActor(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getActor()));
    return tgt;
  }

}
