package org.hl7.fhir.convertors.conv50_N.resources50_N;

import org.hl7.fhir.convertors.context.ConversionContext50_N;
import org.hl7.fhir.exceptions.FHIRException;

// generated by the converter generator: R5 <-> R6 (6.0.0-ballot5)
// the R5 side is asserted from the R6 definitions - compile errors mark real version differences

public class RelatedPerson50_N {

  // RelatedPerson.role is new in R6 - carried in R5 as a cross-version extension
  public static final String ROLE_EXTENSION_URL = "http://hl7.org/fhir/6.0/StructureDefinition/extension-RelatedPerson.role";

  public static org.hl7.fhir.model.core.RelatedPerson convertRelatedPerson(org.hl7.fhir.r5.model.RelatedPerson src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.RelatedPerson tgt = new org.hl7.fhir.model.core.RelatedPerson();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyDomainResource(src, tgt, ROLE_EXTENSION_URL);
    for (org.hl7.fhir.r5.model.Identifier t : src.getIdentifier())
      tgt.getIdentifierList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Identifier50_N.convertIdentifier(t));
    if (src.hasActive())
      tgt.setActiveElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Boolean50_N.convertBoolean(src.getActiveElement()));
    if (src.hasPatient())
      tgt.setPatient(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getPatient()));
    for (org.hl7.fhir.r5.model.CodeableConcept t : src.getRelationship())
      tgt.getRelationshipList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    for (org.hl7.fhir.r5.model.Extension t : src.getExtensionsByUrl(ROLE_EXTENSION_URL))
      tgt.getRoleList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept((org.hl7.fhir.r5.model.CodeableConcept) t.getValue()));
    for (org.hl7.fhir.r5.model.HumanName t : src.getName())
      tgt.getNameList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.HumanName50_N.convertHumanName(t));
    for (org.hl7.fhir.r5.model.ContactPoint t : src.getTelecom())
      tgt.getTelecomList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.ContactPoint50_N.convertContactPoint(t));
    if (src.hasGender())
      tgt.setGenderElement(org.hl7.fhir.convertors.conv50_N.resources50_N.Enumerations50_N.convertAdministrativeGender(src.getGenderElement()));
    if (src.hasBirthDate())
      tgt.setBirthDateElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Date50_N.convertDate(src.getBirthDateElement()));
    for (org.hl7.fhir.r5.model.Address t : src.getAddress())
      tgt.getAddressList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Address50_N.convertAddress(t));
    for (org.hl7.fhir.r5.model.Attachment t : src.getPhoto())
      tgt.getPhotoList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Attachment50_N.convertAttachment(t));
    if (src.hasPeriod())
      tgt.setPeriod(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Period50_N.convertPeriod(src.getPeriod()));
    for (org.hl7.fhir.r5.model.RelatedPerson.RelatedPersonCommunicationComponent t : src.getCommunication())
      tgt.getCommunicationList().add(convertRelatedPersonCommunicationComponent(t));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.RelatedPerson convertRelatedPerson(org.hl7.fhir.model.core.RelatedPerson src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.RelatedPerson tgt = new org.hl7.fhir.r5.model.RelatedPerson();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyDomainResource(src, tgt);
    for (org.hl7.fhir.model.core.Identifier t : src.getIdentifierList())
      tgt.getIdentifier().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Identifier50_N.convertIdentifier(t));
    if (src.hasActive())
      tgt.setActiveElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Boolean50_N.convertBoolean(src.getActiveElement()));
    if (src.hasPatient())
      tgt.setPatient(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getPatient()));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getRelationshipList())
      tgt.getRelationship().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getRoleList())
      tgt.addExtension(ROLE_EXTENSION_URL, org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    for (org.hl7.fhir.model.core.HumanName t : src.getNameList())
      tgt.getName().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.HumanName50_N.convertHumanName(t));
    for (org.hl7.fhir.model.core.ContactPoint t : src.getTelecomList())
      tgt.getTelecom().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.ContactPoint50_N.convertContactPoint(t));
    if (src.hasGender())
      tgt.setGenderElement(org.hl7.fhir.convertors.conv50_N.resources50_N.Enumerations50_N.convertAdministrativeGender(src.getGenderElement()));
    if (src.hasBirthDate())
      tgt.setBirthDateElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Date50_N.convertDate(src.getBirthDateElement()));
    for (org.hl7.fhir.model.core.Address t : src.getAddressList())
      tgt.getAddress().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Address50_N.convertAddress(t));
    for (org.hl7.fhir.model.core.Attachment t : src.getPhotoList())
      tgt.getPhoto().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Attachment50_N.convertAttachment(t));
    if (src.hasPeriod())
      tgt.setPeriod(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Period50_N.convertPeriod(src.getPeriod()));
    for (org.hl7.fhir.model.core.RelatedPerson.RelatedPersonCommunicationComponent t : src.getCommunicationList())
      tgt.getCommunication().add(convertRelatedPersonCommunicationComponent(t));
    return tgt;
  }

  public static org.hl7.fhir.model.core.RelatedPerson.RelatedPersonCommunicationComponent convertRelatedPersonCommunicationComponent(org.hl7.fhir.r5.model.RelatedPerson.RelatedPersonCommunicationComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.RelatedPerson.RelatedPersonCommunicationComponent tgt = new org.hl7.fhir.model.core.RelatedPerson.RelatedPersonCommunicationComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasLanguage())
      tgt.setLanguage(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getLanguage()));
    if (src.hasPreferred())
      tgt.setPreferredElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Boolean50_N.convertBoolean(src.getPreferredElement()));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.RelatedPerson.RelatedPersonCommunicationComponent convertRelatedPersonCommunicationComponent(org.hl7.fhir.model.core.RelatedPerson.RelatedPersonCommunicationComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.RelatedPerson.RelatedPersonCommunicationComponent tgt = new org.hl7.fhir.r5.model.RelatedPerson.RelatedPersonCommunicationComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasLanguage())
      tgt.setLanguage(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getLanguage()));
    if (src.hasPreferred())
      tgt.setPreferredElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Boolean50_N.convertBoolean(src.getPreferredElement()));
    return tgt;
  }

}
