package org.hl7.fhir.convertors.conv50_N.resources50_N;

import org.hl7.fhir.convertors.context.ConversionContext50_N;
import org.hl7.fhir.exceptions.FHIRException;
import org.hl7.fhir.r5.model.ResearchSubject;

// generated by the converter generator: R5 <-> R6 (6.0.0-ballot5)
// the R5 side is asserted from the R6 definitions - compile errors mark real version differences

public class ResearchSubject50_N {

  // R5 ResearchSubject.progress.type, carried on the R6 subjectState / subjectMilestone as a cross-version extension
  public static final String PROGRESS_TYPE_EXTENSION_URL = "http://hl7.org/fhir/5.0/StructureDefinition/extension-ResearchSubject.progress.type";
  // R5 comparison group ids, carried in R6 as cross-version extensions
  public static final String ASSIGNED_COMPARISON_GROUP_EXTENSION_URL = "http://hl7.org/fhir/5.0/StructureDefinition/extension-ResearchSubject.assignedComparisonGroup";
  public static final String ACTUAL_COMPARISON_GROUP_EXTENSION_URL = "http://hl7.org/fhir/5.0/StructureDefinition/extension-ResearchSubject.actualComparisonGroup";
  // R6 ResearchSubject.comparisonGroup, carried in R5 as a cross-version extension (no attempt 
  // is made to map between it and the R5 assigned/actualComparisonGroup ids)
  public static final String COMPARISON_GROUP_EXTENSION_URL = "http://hl7.org/fhir/6.0/StructureDefinition/extension-ResearchSubject.comparisonGroup";

  public static org.hl7.fhir.model.core.ResearchSubject convertResearchSubject(org.hl7.fhir.r5.model.ResearchSubject src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.ResearchSubject tgt = new org.hl7.fhir.model.core.ResearchSubject();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyDomainResource(src, tgt, COMPARISON_GROUP_EXTENSION_URL);
    for (org.hl7.fhir.r5.model.Identifier t : src.getIdentifier())
      tgt.getIdentifierList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Identifier50_N.convertIdentifier(t));
    if (src.hasStatus())
      tgt.setStatusElement(org.hl7.fhir.convertors.conv50_N.resources50_N.Enumerations50_N.convertPublicationStatus(src.getStatusElement()));
    if (src.hasPeriod())
      tgt.setPeriod(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Period50_N.convertPeriod(src.getPeriod()));
    if (src.hasStudy())
      tgt.setStudy(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getStudy()));
    if (src.hasSubject())
      tgt.setSubject(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getSubject()));
    for (ResearchSubject.ResearchSubjectProgressComponent t : src.getProgress()) {
      if (t.getType().hasCoding("http://terminology.hl7.org/CodeSystem/research-subject-state-type", "Milestone")) {
        tgt.getSubjectMilestoneList().add(convertResearchSubjectSubjectMilestoneComponent(t));
      } else {
        tgt.getSubjectStateList().add(convertResearchSubjectSubjectStateComponent(t));
      }
    }
    if (src.hasAssignedComparisonGroup())
      tgt.addExtension(ASSIGNED_COMPARISON_GROUP_EXTENSION_URL, org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Id50_N.convertId(src.getAssignedComparisonGroupElement()));
    if (src.hasActualComparisonGroup())
      tgt.addExtension(ACTUAL_COMPARISON_GROUP_EXTENSION_URL, org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Id50_N.convertId(src.getActualComparisonGroupElement()));
    for (org.hl7.fhir.r5.model.Extension t : src.getExtensionsByUrl(COMPARISON_GROUP_EXTENSION_URL))
      tgt.getComparisonGroupList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference((org.hl7.fhir.r5.model.CodeableReference) t.getValue()));
    for (org.hl7.fhir.r5.model.Reference t : src.getConsent())
      tgt.getConsentList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.ResearchSubject convertResearchSubject(org.hl7.fhir.model.core.ResearchSubject src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.ResearchSubject tgt = new org.hl7.fhir.r5.model.ResearchSubject();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyDomainResource(src, tgt, ASSIGNED_COMPARISON_GROUP_EXTENSION_URL, ACTUAL_COMPARISON_GROUP_EXTENSION_URL);
    for (org.hl7.fhir.model.core.Identifier t : src.getIdentifierList())
      tgt.getIdentifier().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Identifier50_N.convertIdentifier(t));
    if (src.hasStatus())
      tgt.setStatusElement(org.hl7.fhir.convertors.conv50_N.resources50_N.Enumerations50_N.convertPublicationStatus(src.getStatusElement()));
    if (src.hasPeriod())
      tgt.setPeriod(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Period50_N.convertPeriod(src.getPeriod()));
    if (src.hasStudy())
      tgt.setStudy(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getStudy()));
    if (src.hasSubject())
      tgt.setSubject(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(src.getSubject()));
    for (org.hl7.fhir.model.core.ResearchSubject.ResearchSubjectSubjectStateComponent t : src.getSubjectStateList())
      tgt.getProgress().add(convertResearchSubjectSubjectStateComponent(t));
    for (org.hl7.fhir.model.core.ResearchSubject.ResearchSubjectSubjectMilestoneComponent t : src.getSubjectMilestoneList())
      tgt.getProgress().add(convertResearchSubjectSubjectMilestoneComponent(t));
    if (src.hasExtension(ASSIGNED_COMPARISON_GROUP_EXTENSION_URL))
      tgt.setAssignedComparisonGroupElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Id50_N.convertId((org.hl7.fhir.model.core.IdType) src.getExtensionByUrl(ASSIGNED_COMPARISON_GROUP_EXTENSION_URL).getValue()));
    if (src.hasExtension(ACTUAL_COMPARISON_GROUP_EXTENSION_URL))
      tgt.setActualComparisonGroupElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.Id50_N.convertId((org.hl7.fhir.model.core.IdType) src.getExtensionByUrl(ACTUAL_COMPARISON_GROUP_EXTENSION_URL).getValue()));
    for (org.hl7.fhir.model.core.CodeableReference t : src.getComparisonGroupList())
      tgt.addExtension(COMPARISON_GROUP_EXTENSION_URL, org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(t));
    for (org.hl7.fhir.model.core.Reference t : src.getConsentList())
      tgt.getConsent().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.special50_N.Reference50_N.convertReference(t));
    return tgt;
  }

  public static org.hl7.fhir.model.core.ResearchSubject.ResearchSubjectSubjectStateComponent convertResearchSubjectSubjectStateComponent(org.hl7.fhir.r5.model.ResearchSubject.ResearchSubjectProgressComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.ResearchSubject.ResearchSubjectSubjectStateComponent tgt = new org.hl7.fhir.model.core.ResearchSubject.ResearchSubjectSubjectStateComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasType())
      tgt.addExtension(PROGRESS_TYPE_EXTENSION_URL, org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    if (src.hasSubjectState())
      tgt.setCode(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getSubjectState()));
    if (src.hasStartDate())
      tgt.setStartDateElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.DateTime50_N.convertDateTime(src.getStartDateElement()));
    if (src.hasEndDate())
      tgt.setEndDateElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.DateTime50_N.convertDateTime(src.getEndDateElement()));
    if (src.hasReason())
      tgt.setReason(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getReason()));
    return tgt;
  }

  public static ResearchSubject.ResearchSubjectProgressComponent convertResearchSubjectSubjectStateComponent(org.hl7.fhir.model.core.ResearchSubject.ResearchSubjectSubjectStateComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.ResearchSubject.ResearchSubjectProgressComponent tgt = new org.hl7.fhir.r5.model.ResearchSubject.ResearchSubjectProgressComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt, PROGRESS_TYPE_EXTENSION_URL);
    if (src.hasExtension(PROGRESS_TYPE_EXTENSION_URL))
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept((org.hl7.fhir.model.core.CodeableConcept) src.getExtensionByUrl(PROGRESS_TYPE_EXTENSION_URL).getValue()));
    if (src.hasCode())
      tgt.setSubjectState(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getCode()));
    if (src.hasStartDate())
      tgt.setStartDateElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.DateTime50_N.convertDateTime(src.getStartDateElement()));
    if (src.hasEndDate())
      tgt.setEndDateElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.DateTime50_N.convertDateTime(src.getEndDateElement()));
    if (src.hasReason())
      tgt.setReason(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getReason()));
    return tgt;
  }

  public static org.hl7.fhir.model.core.ResearchSubject.ResearchSubjectSubjectMilestoneComponent convertResearchSubjectSubjectMilestoneComponent(ResearchSubject.ResearchSubjectProgressComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.ResearchSubject.ResearchSubjectSubjectMilestoneComponent tgt = new org.hl7.fhir.model.core.ResearchSubject.ResearchSubjectSubjectMilestoneComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt);
    if (src.hasType())
      tgt.addExtension(PROGRESS_TYPE_EXTENSION_URL, org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getType()));
    if (src.hasMilestone())
      tgt.setMilestone(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getMilestone()));
    if (src.hasStartDate())
      tgt.setDateElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.DateTime50_N.convertDateTime(src.getStartDateElement()));
    if (src.hasReason())
      tgt.getReasonList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getReason()));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.ResearchSubject.ResearchSubjectProgressComponent convertResearchSubjectSubjectMilestoneComponent(org.hl7.fhir.model.core.ResearchSubject.ResearchSubjectSubjectMilestoneComponent src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.ResearchSubject.ResearchSubjectProgressComponent tgt = new org.hl7.fhir.r5.model.ResearchSubject.ResearchSubjectProgressComponent();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyBackboneElement(src, tgt, PROGRESS_TYPE_EXTENSION_URL);
    if (src.hasExtension(PROGRESS_TYPE_EXTENSION_URL))
      tgt.setType(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept((org.hl7.fhir.model.core.CodeableConcept) src.getExtensionByUrl(PROGRESS_TYPE_EXTENSION_URL).getValue()));
    else
      // so that the state/milestone discrimination in convertResearchSubject survives a round trip
      tgt.getType().addCoding().setSystem("http://terminology.hl7.org/CodeSystem/research-subject-state-type").setCode("Milestone");
    if (src.hasMilestone())
      tgt.setMilestone(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(src.getMilestone()));
    if (src.hasDate())
      tgt.setStartDateElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.DateTime50_N.convertDateTime(src.getDateElement()));
    // note: R5 progress.reason is 0..1 where R6 subjectMilestone.reason is 0..* - if there are multiple, the last wins
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getReasonList())
      tgt.setReason(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    return tgt;
  }

}
