package org.hl7.fhir.convertors.conv50_N.resources50_N;

import org.hl7.fhir.convertors.context.ConversionContext50_N;
import org.hl7.fhir.exceptions.FHIRException;

// generated by the converter generator: R5 <-> R6 (6.0.0-ballot5)
// the R5 side is asserted from the R6 definitions - compile errors mark real version differences

public class Substance50_N {

  public static org.hl7.fhir.model.core.Substance convertSubstance(org.hl7.fhir.r5.model.Substance src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.model.core.Substance tgt = new org.hl7.fhir.model.core.Substance();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyDomainResource(src, tgt);
    for (org.hl7.fhir.r5.model.Identifier t : src.getIdentifier())
      tgt.getIdentifierList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Identifier50_N.convertIdentifier(t));
    if (src.hasStatus())
      tgt.setStatusElement(convertFHIRSubstanceStatus(src.getStatusElement()));
    for (org.hl7.fhir.r5.model.CodeableConcept t : src.getCategory())
      tgt.getCategoryList().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    if (src.hasCode())
      tgt.setCode(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(src.getCode()));
    if (src.hasDescription())
      tgt.setDescriptionElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getDescriptionElement()));
    if (src.hasExpiry())
      tgt.setExpiryElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.DateTime50_N.convertDateTime(src.getExpiryElement()));
    if (src.hasQuantity())
      tgt.setQuantity(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Quantity50_N.convertQuantity(src.getQuantity()));
    return tgt;
  }

  public static org.hl7.fhir.r5.model.Substance convertSubstance(org.hl7.fhir.model.core.Substance src) throws FHIRException {
    if (src == null)
      return null;
    org.hl7.fhir.r5.model.Substance tgt = new org.hl7.fhir.r5.model.Substance();
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyDomainResource(src, tgt);
    for (org.hl7.fhir.model.core.Identifier t : src.getIdentifierList())
      tgt.getIdentifier().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Identifier50_N.convertIdentifier(t));
    if (src.hasStatus())
      tgt.setStatusElement(convertFHIRSubstanceStatus(src.getStatusElement()));
    for (org.hl7.fhir.model.core.CodeableConcept t : src.getCategoryList())
      tgt.getCategory().add(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableConcept50_N.convertCodeableConcept(t));
    if (src.hasCode())
      tgt.setCode(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.CodeableReference50_N.convertCodeableReference(src.getCode()));
    if (src.hasDescription())
      tgt.setDescriptionElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.MarkDown50_N.convertMarkDown(src.getDescriptionElement()));
    if (src.hasExpiry())
      tgt.setExpiryElement(org.hl7.fhir.convertors.conv50_N.datatypes50_N.primitive50_N.DateTime50_N.convertDateTime(src.getExpiryElement()));
    if (src.hasQuantity())
      tgt.setQuantity(org.hl7.fhir.convertors.conv50_N.datatypes50_N.general50_N.Quantity50_N.convertQuantity(src.getQuantity()));
    return tgt;
  }

  static public org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.Substance.FHIRSubstanceStatus> convertFHIRSubstanceStatus(org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.Substance.FHIRSubstanceStatus> src) throws FHIRException {
    if (src == null || src.isEmpty())
      return null;
    org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.Substance.FHIRSubstanceStatus> tgt = new org.hl7.fhir.model.core.Enumeration<>(new org.hl7.fhir.model.core.Substance.FHIRSubstanceStatusEnumFactory());
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyElement(src, tgt);
    if (src.getValue() == null) {
      tgt.setValue(null);
    } else {
      switch (src.getValue()) {
        case ACTIVE:
          tgt.setValue(org.hl7.fhir.model.core.Substance.FHIRSubstanceStatus.ACTIVE);
          break;
        case INACTIVE:
          tgt.setValue(org.hl7.fhir.model.core.Substance.FHIRSubstanceStatus.INACTIVE);
          break;
        case ENTEREDINERROR:
          tgt.setValue(org.hl7.fhir.model.core.Substance.FHIRSubstanceStatus.ENTEREDINERROR);
          break;
        default:
          tgt.setValue(org.hl7.fhir.model.core.Substance.FHIRSubstanceStatus.NULL);
          break;
      }
    }
    return tgt;
  }

  static public org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.Substance.FHIRSubstanceStatus> convertFHIRSubstanceStatus(org.hl7.fhir.model.core.Enumeration<org.hl7.fhir.model.core.Substance.FHIRSubstanceStatus> src) throws FHIRException {
    if (src == null || src.isEmpty())
      return null;
    org.hl7.fhir.r5.model.Enumeration<org.hl7.fhir.r5.model.Substance.FHIRSubstanceStatus> tgt = new org.hl7.fhir.r5.model.Enumeration<>(new org.hl7.fhir.r5.model.Substance.FHIRSubstanceStatusEnumFactory());
    ConversionContext50_N.INSTANCE.getVersionConvertor_50_N().copyElement(src, tgt);
    if (src.getValue() == null) {
      tgt.setValue(null);
    } else {
      switch (src.getValue()) {
        case ACTIVE:
          tgt.setValue(org.hl7.fhir.r5.model.Substance.FHIRSubstanceStatus.ACTIVE);
          break;
        case INACTIVE:
          tgt.setValue(org.hl7.fhir.r5.model.Substance.FHIRSubstanceStatus.INACTIVE);
          break;
        case ENTEREDINERROR:
          tgt.setValue(org.hl7.fhir.r5.model.Substance.FHIRSubstanceStatus.ENTEREDINERROR);
          break;
        default:
          tgt.setValue(org.hl7.fhir.r5.model.Substance.FHIRSubstanceStatus.NULL);
          break;
      }
    }
    return tgt;
  }

}
