name: Crowdin Action

on:
  push: # instantly push new source strings to Crowdin for translators
    branches: [ master ]
    paths: '**.po'
  workflow_dispatch:

  schedule: # check for translations from Crowdin every 12h
    - cron: '0 */12 * * *'

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          export_only_approved: false
          localization_branch_name: l10n_crowdin_translations_${{ github.ref_name }}

          create_pull_request: true
          pull_request_title: 'New Crowdin translations'
          pull_request_body: 'New Crowdin pull request with translations'
          pull_request_base_branch_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.CROWDIN_GITUSER_PAT }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
