# This workflow runs the license-maven-plugin to collect the licenses of compiled and runtime dependencies in all this
# project's modules. It will ignore test and provided dependencies.

name: License Check

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:


permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Only read access to repository contents
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Collect module licenses
        run: mvn clean install -DskipTests
      - name: Collect module licenses
        run: mvn license:add-third-party -Dlicense.includedScopes=compile,runtime
      - name: Aggregate licenses
        run: mvn license:aggregate-add-third-party -Dlicense.includedScopes=compile,runtime
      - name: Set script permissions
        run: chmod u+x .github/workflows/license-check/license-check.sh
      - name: Run script
        run: .github/workflows/license-check/license-check.sh
        #continue-on-error: true
